### ISSUE TITLE
Show only year of events in the public page

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1019]
I think it would be a great improvement, to make it possible to show only the year of an event to the public. At moment I can set it only for events like birt, marriage, death to be shown public or not.
But I want to show them, but not with the exact, but only the year.

**Comment by eric215** [comment]
Could you please clarify, perhaps with an example?   I'm not sure I understand what you're looking for.

If you know the exact date for an event or fact, why wouldn't you want it seen by the public?  My website, small as it is, gets regular traffic from visitors.  If the information I present is less accurate than what they may find elsewhere, then they will likely lose interest in my site.   In many cases I have been able to find more accurate information than we had on our older typewritten family histories.

**Comment by fisharebest** [comment]
This is not an easy change.

The same code/format is used everywhere - and you do not want to change *all* the dates.

For example, you will still need the full date on the calendar, etc.

The links to the calendar will also need to change, so that they point to the year (not the day/month/year).

This would require a lot of work, a lot of complexity - and little benefit.

Sorry, but I don't plan to implement this.

**Comment by HonkXL** [comment]
Ok. I understand! I think you can close this issue. Thank you.
