### ISSUE TITLE
Webtrees log can not handle IPv6

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#1023]
When I use Webtrees from a computer that uses IPv6, I only see
127.0.0.1
as IP address in the logs (I mean the internal log of Webtrees, not the Apache-Log).
I think IPv6 should be supported.

**Comment by fisharebest** [comment]
On my apple laptop, I see `::1` in the `ip_address` column of the table `wt_logs`.

So, it seems to work for me...

**Comment by fisharebest** [comment]
Go to `Control panel` => `Website` => `Website information` and scroll down to `_SERVER["REMOTE_ADDR"]`.

What address do you see here?

**Comment by HonkXL** [comment]
I attached a screenshot of what I see in Website-Info and what I get in the Log.
![login](https://cloud.githubusercontent.com/assets/16715040/16261098/8e110f30-386a-11e6-9cc0-d76ce45de43f.jpg)

**Comment by HonkXL** [comment]
Maybe relevant: I use PHP 7.0.7.

**Comment by fisharebest** [comment]
This is the code that finds the IP address.

```
if (Filter::server('HTTP_CLIENT_IP') !== null) {
	define('WT_CLIENT_IP', Filter::server('HTTP_CLIENT_IP'));
} elseif (Filter::server('HTTP_X_FORWARDED_FOR') !== null) {
	define('WT_CLIENT_IP', Filter::server('HTTP_X_FORWARDED_FOR'));
} else {
	define('WT_CLIENT_IP', Filter::server('REMOTE_ADDR', WT_REGEX_IPV4, '127.0.0.1'));
}
```

Does your server set the headers `HTTP_CLIENT_IP` or `HTTP_X_FORWARDED_FOR`.

**Comment by fisharebest** [comment]
Ignore that.  I see the problem - `WT_REGEX_IPV4`

**Comment by fisharebest** [comment]
The ip_address column in the session table isn't long enough for IPv6.
However, we never read this column, and mobile users can change IP address during a session, so I'm not sure we need it here at all.

IIRC, the IPv4 restriction was added because of a conflict with the site-access-rules, which will need to be rewritten.

**Comment by kohtala** [comment]
I was wondering this same issue. I have 1.7.9.

Database seems to have wider ip_address fields as result of #1088, and it now logs IPv6 address for clients that came through proxy that set the Client-IP or X-Forwarded-For.

If the client reached server directly using IPv6, it still logs 127.0.0.1 instead of the real IPv6 REMOTE_ADDR.

I would expect to see the IPv6 address in the log.

**Comment by fisharebest** [comment]
@kohtala 

It is always better to create a new issue, than to comment on a closed one.

> I would expect to see the IPv6 address in the log.

This is a different problem to this one (cannot login).

**Comment by kohtala** [comment]
Isn't **this** issue the "cannot log"? The #1088 was the "cannot login" issue.

**Comment by marku5** [comment]
Yes, but *this* issue is already closed. Even when describing the same problem again it's better to open a new issue and refering to the old/closed one.

**Comment by kohtala** [comment]
Sorry. I come from background, where issues are preferred re-opened if they are found not fixed. I had not noticed you work differently.

I fully respect your work on Webtrees and your view on how you want to have this handled. I'll do whatever way you find most helpful. I created the issue #1203.

Thanks.
