### ISSUE TITLE
1 photo linked into 2 trees

### ISSUE THREAD

**Issue by carlluiz** [fisharebest/webtrees#1030]
Hi,
I created today a second tree, and a person of this family, of this second tree, asked me to insert a photo of her in this tree, but she also asked me to link this media file with to two other people of my family who are also in this photo. The problem is that the photo is in the second tree, but I found no option to link this picture to any person in my tree where the other two people are registered.
Can we link a single media file with two different trees without having to register the same photo twice?
Like... one photo registered once, but linking in two different trees?
Thanks.

**Comment by fisharebest** [comment]
We use the GEDCOM data format.  This does not allow us to link between different trees.

What is possible, however, is to have two media objects (genealogy records in the family tree) that use the same media file (file on disk).

This is because GEDCOM does not include media files - just the names of them.

To do this, you will need to configure both your family trees to use the same media folder (Control panel -> Family tree preferences).

IMHO, it would be good practice to keep the two trees separate, and have two copies of the photo.

**Comment by carlluiz** [comment]
Perfect, my friend... Webtrees is the best!
