### ISSUE TITLE
Microsoft supported browsers

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1036]
Given Microsoft's post on [12th Jan](https://www.microsoft.com/en-gb/WindowsForBusiness/End-of-IE-support) regarding end of support for every version of Internet Explorer before IE11, I wonder if we should adopt and publish a similar policy. After all, for older versions of windows (everything before 8.1) users could always install Chrome

**Comment by makitso** [comment]
I am not sure that we are doing anything special for these older versions of IE.  As for a policy, we have always been pretty general in this area.

**Comment by fisharebest** [comment]
> I wonder if we should adopt and publish a similar policy.

Formal policies like this have the problem that the future rarely looks like the past.

A lot of applications decided to support the latest and two previous versions of a browser.   On Chrome, this now means not supporting a 3 month old browser, and on IE, this now means supporting 10/11/Edge for eternity.

So, I'd prefer to adopt a more flexible and pragmatic approach, and drop support for older browser/servers based on things such as market-share and the difficulty in supporting a wide range of versions at the same time.

Since we stopping officially supporting IE <=8, we've had very few browser related problems.  We don't use many esoteric browser features, and modern browsers are all pretty good at rendering well-formed HTML5.

@ddrury - are there any specific problems with old IE that have prompted this question?

**Comment by ddrury** [comment]
I have no problems with older browser versions beyond what they do (or more to the point don't) support. 

During my recent work on the Googlemaps module I submitted some changes that used 
`display: flex` more in hope than expectation and was pleasantly surprised when you accepted it. This seems to me a tacit acceptance of the fact that any users of IE10 and below were no longer a blocker to use of the more recent CSS3 additions.

I therefore thought that by making our stance clear it would:

- Encourage users to upgrade
- Allow developers to use the new CSS3 modules in the clear knowledge that a broken display in these redundant browsers is not a barrier.
- Enable modification/simplification of existing code (a la googlemaps)

**Comment by fisharebest** [comment]
> I submitted some changes that used `display: flex` more in hope than expectation and was pleasantly surprised when you accepted it

I'll admit that I didn't really notice this.  I see from http://caniuse.com that based on browser market share, `flex` only has 80% support.

Perhaps we ought to wait until this percentage increases before deploying `flex` more widely?
I won't have access to IE until the week after next, so I can't see how it looks on IE.

**Comment by fisharebest** [comment]
The 1.8.0 release of webtrees looks like a good place to drop support for legacy browsers.

**Comment by makitso** [comment]
I would agree, whatever differences are minor.
