### ISSUE TITLE
If there is no gender, how do you edit it?

### ISSUE THREAD

**Issue by HanBrouwer** [fisharebest/webtrees#1051]
When you import a GEDCOM file that does not contain any gender/sex for an individual, webtrees uploads the .ged file as it is. It does not add any "missing tags" on upload.
If there is no "sex" tag at all, how can you edit it?

**Comment by wkitty42** [comment]
use the "edit raw gedcom" option and manually add it... make sure to use the proper format ;)

**Comment by BertKoor** [comment]
Menu - Edit Sex should be used for this. That did function as expected in v1.6.2, The next version I have tested is v1.7.2, and there no dialog is brought up after clicking this menu option. So it looks like a regression issue since v1.7.0 or there about.
Also see the forum discussion: https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-6/31437-solved-how-to-add-a-gender

**Comment by fisharebest** [comment]
The code for this exists - but it was not being called correctly.
