### ISSUE TITLE
"Files" menu in Weblate

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#1114]
I'm sorry, I'm not sure that issues in Weblate are reported here as well. Hope it's not a mistake.

As I see it, the `Files` menu in Weblate is changed.

The `X-Generator` of Weblate selecting  `Download original translation file (Gettext PO file)` first item in the menu is 2.5 while others are 2.8.

The following metadata in `.MO` and `.PO` files of Weblate 2.8 seems to be missing or incomplete:
`Report-Msgid-Bugs-To`
`PO-Revision-Date`
`Last-Translator`
`X-Poedit-Language`
`X-Poedit-SourceCharset`
`X-Poedit-SearchPath-0`
`X-Poedit-Basepath`
`X-Poedit-KeywordsList`

**Comment by fisharebest** [comment]
Weblate was recently upgraded from 2.5 to 2.8
If a .PO file shows 2.5, then it means that there have been no updated translations since the upgrade.

The X-Poedit-XXXX headers are created when a translator uses POEdit to edit the file.

These headers are ignored by Weblate/webtrees.

I don't think there is a problem here.
