### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#1120]
I installed webtrees on IIS and the timezones seem all screwed up.

The Server Information screen in the webtrees environment correctly shows "Default timezone America/Detroit".

But everytime I add a news article or a new user, the server adds 5 hours to the correct times, effectively showing only UTC times.

Changing the timezone in my user profile seems to have no effect.

**Comment by mpwt** [comment]
At least the Recent changes block not shows the correct time:
![bildschirmfoto 2016-10-09 um 13 52 00](https://cloud.githubusercontent.com/assets/16311627/19220260/700db668-8e29-11e6-9f3c-047bd5a219e7.png)
I made the visible changes two hours later at Central European Summer Time (MESZ/CEST/CEDT). At persons page webtrees shows the time stamp correct:
![bildschirmfoto 2016-10-09 um 14 09 20](https://cloud.githubusercontent.com/assets/16311627/19220275/043cc7d4-8e2a-11e6-8db3-6bfbc967f367.png)

My website preferences -> time zone is set to EUROPE/BERLIN ...

**Comment by fisharebest** [comment]
#865 fixed the timestamp columns in the database (pending changes, mail, news).

Timestamps are stored internally as a number - the number of seconds since 01 JAN 1970 UTC.
We can convert these to a local timezone.

> But everytime I add a news article or a new user, the server adds 5 hours to the correct times

Are you sure?  I tested this (news article) again, and it works OK for me.
If I change the timezone in my account, the displayed date/time changes correctly.

> At least the Recent changes block not shows the correct time:

This is a different problem, and may not be possible to fix.

Suppose you import a GEDCOM file that contains

```
1 CHAN
2 DATE 09 OCT 2016
3 TIME 18:42:23
```

We do not know the timezone of the change record, so we cannot convert it into the user's timezone.  Instead, we just display the unconverted date.

GEDCOM uses the same data format for the time of events such as birth and death.  Again, these have no timezone.  If we have the following GEDCOM data,

```
1 DEAT
2 DATE 09 OCT 2016
3 TIME 18:42:23
```

we cannot know if the person died at 18:42 in `UTC`, `Europe/Berlin` or `Europe/London`.

**Comment by mpwt** [comment]
> At least the Recent changes block not shows the correct time:

> This is a different problem, and may not be possible to fix.

Ok, it is a different problem. But it looks like a timezone problem because the difference is exactly two hours less than CEST (for my example).

Why uses this block a different time then saved. The correct changing time is saved in the database table "_change".

**Comment by fisharebest** [comment]
In the `wt_change` table, we record the timestamp when the change was made.
We need this timestamp so that we can apply changes in the correct order.

But this is NOT the same time that is stored in the GEDCOM data.  The GEDCOM data can contain *any* date or time.

For example, if the user selects the "do not update the CHAN record" option, then the GEDCOM will contain the old DATE/TIME.

The block contains data from the GEDCOM file.  If we import a GEDCOM file with CHAN records, we will not have any changes in `wt_change`.

**Comment by miqrogroove** [comment]
My bug report is not related to GEDCOM.  Perhaps there is some miscommunication in these two tickets.

My examples are as follows:

News post time.
User login time / User administration.
Add a user.

In all of the places where webtrees needs to store and retrieve the time "now" it is giving completely wrong information.

**Comment by fisharebest** [comment]
> My bug report is not related to GEDCOM. 

Your second post in this issue shows the recent change block - which is GEDCOM data.

> Perhaps there is some miscommunication in these two tickets.

But I flew home overnight last night, and have had little sleep, and I may also be a little confused...

> News post time.
> User login time / User administration.
> Add a user.

News post - I think this is fixed.  It works for me.
Last login time - agreed, I see this.
Add a user - I guess this is the "Date registered" column on the user administration page.

**Comment by mpwt** [comment]
Sorry, when I hijacked this post but I thought (and think) that the problem with the recent changes block is similar.

I don't understand why the recent changes block not uses the saved change time. It seems that there is a function which calculates anything. When I saved a change at 9:50 pm and webtrees saved it at 9:50 pm inside the database why the block displayes it at 7:50 pm. That is wrong and should be changed.
