### ISSUE TITLE
Search and privacy

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#1129]
See: https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-8/31683-search-and-privacy#61563

Searching a unique name for a person with a family record brings you to the family page where all boxes are private, but you are enabled to browse up the tree to the public boxes. This may be two or three generations/ancestors further.

This happens when the option 'show private relationships' is enabled.

**Comment by fisharebest** [comment]
We must perform all the search functions twice.

* we use MySQL to search the database to get a list of records.
* we use PHP to apply privacy filters on this list of records `XXX::canShowName()`.
* we apply the search filter a second time, to the list of private records.

The cause of the problem is that `Family::canShowName()` is always true.
If the spouses are private, the name of the family will be "Private + Private".

So, although the search results do not show any private data, they allow a visitor to "guess" names.

The same search function is also used in the `find.php` popup window.
