### ISSUE TITLE
Import GEMCOM date format

### ISSUE THREAD

**Issue by sebleclerc** [fisharebest/webtrees#1131]
I have imported my GEDCOM file which has this individual:
0 @I19@ INDI
1 NAME FNAME /LNAME/
2 GIVN FNAME FNAME
2 SURN LNAME
1 SEX F
1 BIRT
2 DATE 1986-07-05
2 CHAN
3 DATE 04 JAN 2012
4 TIME 20:07:24
1 CHAN
2 DATE 16 JAN 2013
3 TIME 11:47:11
1 FAMC @F7@

Inside the wt_dates table, these are the dates for 1986:
d_day	d_month	d_mon	d_year	d_julianday1	d_julianday2	d_fact	d_gid	d_file	d_type
0		0	                        1986	2446432	2446796	BIRT	I3711982863	1	@#DGREGORIAN@
0		0	                         1986	2446432	2446796	BIRT	I19	         1	@#DGREGORIAN@

It doesn't seem to import dates using the ISO format. Do I have to change all dates for webtrees to be able to parse them?

**Comment by fisharebest** [comment]
`2 DATE 1986-07-05`

This is not valid GEDCOM.  You can view the GEDCOM specification [here](https://wiki.webtrees.net/w/images-en/Ged551-5.pdf).

The only valid date format is `DD MMM YYYY`, so, you need `05 JUL 1986` instead of `1986-07-05`.

For invalid/unrecognisable dates, webtrees will look for a 4 digit number and assume this is a year.

Which application created this GEDCOM file?

Note: the user-interface will convert various date formats into GEDCOM data format as you type.  However, this only happens when you are editing/entering data.  The import process does not attempt to convert data.

**Comment by fisharebest** [comment]
BTW, if you use the "vi" text editor, then the following command may be useful...

`:%s/^2 DATE \([0-9][0-9][0-9][0-9]\)-01-\([0-9][0-9]\)$/2 DATE \2 JAN \1/`

**Comment by sebleclerc** [comment]
Well that makes sense. Thanks for the clarification.

I used MacFamilyTree as my genealogy app and entered all my dates as YYYY-MM-DD. I want to try something else because it got pricey. Also with webtrees I can give permission to family members to update and add info, which is a plus.

**Comment by sebleclerc** [comment]
And thanks a lot @fisharebest for the command! It was really helpful indeed!!
