### ISSUE TITLE
Performance - getNextId

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1132]
XREFs are alphanumeric strings.
Existing XREFs may be in any format.
Newly-created XREFs take the format PREFIX + INTEGER.

In order to find an unused value, we must query each value in turn (`i1000`, `i1001`, `i1002`, ... ) until we find an unused one.

If a large number of records already exist, we may need to make a large number of queries to find the next unused one.  This can be very slow on some systems.

Alternative implementations might include:

* fetching all XREFs into memory, and searching in PHP
* replacing the sequential IDs with a UUID style value

**Comment by tronsmit** [comment]
Can one keep track of the max used integer value (or the next available one) for a class of XREF values? I would imagine that would be possible after reading in a new Gedcom and knowing what the prefix is for the new tree. This would have to be recalculated after changing the prefix (in case it matches with one of the non webtree pre-existing generated formats). You can still test whether it is available, before using it with the existing algorithm.

This would lead to some wastage (but the amount can be estimated), and would be able to be fixed with a maintenance run to renumber XREFs.
