### ISSUE TITLE
app/Individuals.php: Estimated birth and death dates

### ISSUE THREAD

**Issue by arjanvs** [fisharebest/webtrees#1141]
The issue is probably more a feature request.

I discovered, that if I have one of the following facts:
- Death with data and age
- Marriage with data and ages

The birth date is not estimated based on those facts. It is still generally estimated based on the generations at hand.

**Comment by fisharebest** [comment]
We don't use data from the `AGE` tags to estimate date-of-birth because 99.9% of users will have already created a `BIRT` event already.

e.g. if you have a census that says that in 1891 a person was 19 years old and born in London, then you would have created a birth event, 1872/London.

Using `AGE` tag would slow things down for no appreciable benefit.

**Comment by arjanvs** [comment]
My suggestion was not to estimate, if a birth value is given.

In my case I have ancestor, he would be born in
* 1775 according to marriage
* 1778 according to death certificate
After some search I found he is born in 1777, but to get an initial estimate one could determine it from those events.

**Comment by fisharebest** [comment]
The estimated date is required to be fast.

It exists simply so that we can create an "approimately correct" sort order on lists of individuals.

> 1778 according to death certificate

If you, as a genealogist, find a death certificate with an age, then I would expect you to create a birth record and use this death certificate as the source.

There is little point adding slow calculations to estimate data that the genealogist should have entered.
