### ISSUE TITLE
php 7 support

### ISSUE THREAD

**Issue by jnbek** [fisharebest/webtrees#1143]
What's the status of php7 support? I have webtrees running with php56 and want to upgrade to the 7 series, but prior to doing so, I'd like to make sure it's going to work out of the box.

**Comment by fisharebest** [comment]
PHP7.0 is supported 100%.  All the servers at *.webtrees.net use PHP7.0 and all development takes place on PHP7.0.

PHP7.1 was only released a couple of weeks ago - i.e. *after* the latest release of webtrees.

There have been two bug reports related to PHP7.1.
One is already fixed.
The other is in a 3rd party library, and there is a simple workaround until it gets fixed.

We have been running our unit tests against PHP 7.1 since the first beta release.  However, the tests only cover the newer code (about 5%).

**Comment by fisharebest** [comment]
Incidently, I note that the [PHP7.1 release notes](http://php.net/ChangeLog-7.php#7.1.0) includes a fix for a [bug](https://bugs.php.net/bug.php?id=67976) that I raised ;-)

**Comment by jnbek** [comment]
well then, awesome and thanks! :)
