### ISSUE TITLE
Polish surnames

### ISSUE THREAD

**Issue by gasioreks** [fisharebest/webtrees#1164]
Webtrees support Polish male/female surnames but it is currently not perfect.

There is missing translation between surnames ending with "na"/"ny".
Attached files fixes this issue.

[polish_fix.zip](https://github.com/fisharebest/webtrees/files/681330/polish_fix.zip)

**Comment by fisharebest** [comment]
@wooc - can you look at this?

**Comment by wooc** [comment]
I had not added this to the code because it is not always true (I think it is about 50%). I've decided that user needs to choose which version of name is correct in this case. I know many variants of surname ending with "ny" that is typical male version but female version is the same. The current law in Poland says that women needs to decide which version of surname wants to have. In this case she is able to choose between for example Cudny or Cudna, Zielony or Zielona.

**Comment by gasioreks** [comment]
OK. I can stay with my locally fixed branch.
