### ISSUE TITLE
TODOs connected to sources are not listed in block 'research tasks'

### ISSUE THREAD

**Issue by marku5** [fisharebest/webtrees#1188]
TODOs connected to sources are not listed in block "research tasks"

Tasks added to individuals or families get listed.

webtrees 1.7.8

**Comment by marku5** [comment]
Could someone possible check if I'm wrong or this is a real bug? Thanks!

**Comment by fisharebest** [comment]
These were only ever designed to work on INDI and FAM records.

It's not really a bug.  It was designed this way.  It cannot easily be modified to work with other records.

This is because we extract the list from the genealogy facts/events - and these are only attached to families and individuals.

**Comment by marku5** [comment]
Thanks Greg!
Could you suggest any other option to have a list of comments which are attached to e.g. sources? (I.e. to "simulate " the _TODO-feature which is perfectly working for I and F.)

**Comment by ric2016** [comment]
Re: Last comment by marku5: 
I use shared notes for TODOs (mainly because I wasn't aware of the Research Tasks feature) - You can attach these to sources as well, and then display the list of sources for the respective shared note (via General Search). This is probably not that useful if you need different texts/notes for each source though.

**Comment by marku5** [comment]
@Richard, god idea. I'll give it a try.
@Greg: If you see this discussion as input for future code change free to close this issue.
