### ISSUE TITLE
Remove the "Primary" custom tag.

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1310]
webtrees has inherited support for `1 _PRIM Y/N` from phpGedView.  This custom tag and associated logic were copied from a desktop program.

This non-standard tag is not intuitive, and is not really necessary.

Much simpler logic would be:

1) Take the first level 1 media object.
2) If no level 1 media are found, take the first media object from the first fact/event that contains one.

This also follows the GEDCOM standard that says when multiple data is available in a GEDCOM record, the first one found should have higher precedence.

**Comment by JustCarmen** [comment]
After this change, can we still set an option to not use any of the media objects as primary? Lots of time I have a bunch of certificates attached to an individual which I do not set as primary, because I only use photos as the primary (highlighted) image.

And will it still be possible to change the sort order to set another object as the first (primary) object?

**Comment by fisharebest** [comment]
I'd actually prefer this.  i.e.

> Much simpler logic would be:
> 1. Take the first level 1 media object.

I only wanted to make a small change from the existing behaviour.

But I agree with you that images from facts are rarely good examples for a "portrait" image.
