### ISSUE TITLE
Can't add media item to new individual

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1387]
dev version: I am probably doing something stupid.  Added a new individual.  I then tried to add a photo of the person.  I thought I could go to the Media tab on the individual page but its grayed out.  What am I doing wrong?

**Comment by fisharebest** [comment]
The add media link was moved because of https://github.com/fisharebest/webtrees/issues/1338

It's now with the "primary" image, to the left of the names.

The thought was having notes/media/sources on separate tabs is confusing:

* Level2 notes/media/sources get duplicated.
* copy and paste functions are on different tabs.
* media and album tabs duplicate each other a lot.

So, I'm considering combining notes/media/sources into the facts+events tab....

**Comment by makitso** [comment]
Ahhhh, yes I see it -- thanks :-)
