### ISSUE TITLE
"Keep media objects" option is confusing, and probably not needed

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1392]
This option causes confusion and errors because people do not understand what it does or why they might need it.

Are there still desktop programs that cannot handle media?
Are there still people who round-trip between webtrees and such a program - AND who also add media objects in webtrees?

It cannot support media linked to facts (these are re-linked to individuals).

Perhaps we should finally delete this option?

**Comment by mburnicki** [comment]
I would appreciate if you could keep this option.

I've started to collect data about my ancestors using the gramps software, and only detected later that webtrees is a very nice software to visualize the GEDCOM database.

Actually, I've added photos only afterwards in webtrees because I'm still thinking about how to organize these on my local computer. This works nice right now, even if I upload an updated GEDCOM file the assigned photos are still available. As I understand it, the photos (or the reference to the photos) would be deleted if this option didn't exist, and there is no reference in the GEDCOM file.

**Comment by fisharebest** [comment]
OK - thanks for the feedback.

**Comment by fisharebest** [comment]
Another user has confirmed that they use this feature.
