### ISSUE TITLE
Bootstrap - Nuts and bolts

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1393]
The first thing I will say is that I don’t fully understand how bootstrap works as it dynamically changes screen sizes to match the device.  Having said that I do have some questions that perhaps you more knowledgeable folks can handle.

I have two examples of displays displays seem quite out of line with others.

One is my tablet in portrait mode 900 x 1280.  The other is my mobile phone in landscape mode 732 x 412.

Mobile phone:  In landscape mode, there is a lot of space waisted on the screen with white space.  Using the webtrees demo site, webtrees theme, home page as an example, about 25% of the horizontal screen is waisted.  This is caused by the bootstrap.mn.css .container @media (mix-width: 576px;} with a max-width: 540px;

Tablet:  Same thing, again a lot of waisted space due to bootstrap.mn.cs .container  @media (mix-width: 768px;} with a max-width: 720px;

So, my question is, who establishes these parameters for different size screens, us guys or the bootstrap folks?  Are we as developers expected to fiddle with these things or should be leave it alone.  

I guess the real reason I ask is that on My Page and the Home Page, there are a lot of optional blocks that have wide data in them.  There are different ways to handle these but the variable width’s on different displays makes it a moving target.

**Comment by fisharebest** [comment]
The "breakpoints" for different sized devices are set by bootstrap.  http://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints

XS: -575px
SM: 576-768px
MD: 769-992px
LG: 993-1200px
XL: 1200- px

These were updated from the previous version of bootstrap, and I'm guessing they were chosen with some care.

However, `bootstrap.min.css` is just a build of bootstrap with the default parameters.  By changing parameters in the `.scss` source files, it is possible to have different breakpoints, colors, columns, etc.

It is possible (and simple!) to disable these breakpoints completely (use class `container-fluid` instead of `container`).  However, this can actually require more work, as you need to design for an infinite number of widths, rather than just 5 widths.

> There are different ways to handle these but the variable width’s on different displays makes it a moving target.

There are two basic options for small devices.

1) show less data
2) order things vertically rather than horizontally.

For example, the list of common surnames.  For large devices, show female/male side-by-side.  For medium devices, stack them vertically.  For small devices, just show the names, not the totals.

We have the additional complexity in that the media queries are set on the width of the window.  We have blocks that can appear in two different sized columns, and we'd also want to have different layouts depending on both the window size and whether the block is a child of `.wt-main-blocks` or `.wt-side-blocks`.

**Comment by makitso** [comment]
Thanks Greg, that's more information than I had before.  I do find it interesting that bootstrap's definition of extra small is set to 575px and smaller in landscape mode.  If most mobile phones are used in portrait mode and have a width of 375-412  more granularity may be needed?
So, what does this mean for webtree, with all the different displays, will one size fit all?

**Comment by makitso** [comment]
After playing around, it seems to me that this layout would fit webtrees better:
Would you change the .scss source file to generate this or override?

`@media (min-width: 576px) {
	.container {
		max-width: 95%;
	}
}
@media (min-width: 768px) {
	.container {
		max-width: 95%;
	}
}
@media (min-width: 992px) {
	.container {
			max-width: 95%;
	}
}
@media (min-width: 1200px) {
	.container {
		max-width: 1140px;
 	}
}
`

**Comment by fisharebest** [comment]
> I do find it interesting that bootstrap's definition of extra small is set to 575px and smaller in landscape mode.

I found this site that lists the sizes of many common devices:  https://mydevice.io/devices/

575px would seem to fairly accurately differentiate between phones and tablets.

**Comment by melizaa** [comment]
I have a wide screen on my laptop (3200 x 1800) and my linked screen (1680 x 1050). I see a lot of 'margins' on the webtrees pages and the names etc. are written on several rows. 

Should't we also define at least XXL for 1920x1080 for Full HD screens?

**Comment by Amgine0** [comment]
> 575px would seem to fairly accurately differentiate between phones and tablets.

Not according to that list; by number of models listed you would potentially be mis-diagnosing 68% of phone models which are larger than 575. (Market share may dramatically change the actual number of devices mis-identified. e.g. there may be a lot more Samsung S2s than Apple 6s.)

On the other hand, there are no tablets listed smaller than 800px, and only one model at that size. <800px captures all phones except iPhone X on that list.

**Comment by melizaa** [comment]
I do not understand. 

On my Yoga 900 notebook's 4K UHD screen I see the Top 10 given names of male and female one under the other and the margins to the left and right are big.

I tried to use our desktop's 1920 x 1080 Full HD screen. The Top 10 given names of male and female are printed one under the other and the margins to the left and right are big.

I expect that webtrees will work as before on my notebook and on our desktop.

It is nice if handheld devices will also work.

**Comment by makitso** [comment]
Personally, I have gone back and forth on this screen width issue.  Right now, my personal site [http://www.skatekey.net/index.php?ctype=gedcom&ged=peters.ged](url) is a 2.0 with local mods, some of which I mentioned above.  Currently, I have it set up to fill the screen for each type of device -- large screen or mobile.

**Comment by melizaa** [comment]
Rob, your site looks great. How can I use your definitions?

**Comment by marku5** [comment]
> I expect that webtrees will work as before on my notebook and on our desktop.
>
> It is nice if handheld devices will also work.

May I express my support for this comment by @melizaa, as myself and all active users for my tree are PC/Laptop-users only when it comes to editing. Mobile (Tablet, Phone) is only sometimes used for reading.
