### ISSUE TITLE
NICK names - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1401]
I would like to print the NICK name on my site as we used to print between the Given name and the Surname. Almost all my site nick-names originate from given names. My users have seen the nicknames the old way for some 13 years. Several have problems when the site's look and feel changes.

Perhaps the administrators could be able to define for each site if the NICK names should print as they used to print or at the end of the name?

**Comment by JustCarmen** [comment]
I agree. The nickname should not be printed as part of the given names. The given names are a persons official names. The nickname is the name to indicate how the person actually was called. These two should not be mixed up in the given name part.

**Comment by fisharebest** [comment]
This functionality was removed because it cannot be made to work reliably.  Imagine we have

```
1 NAME aaa /bbb/ ccc
2 NICK ddd
```

If this is an English name, then we might jwant to display `aaa "ddd" /bbb/ ccc`.
If this is a Korean or Hungarian name, then we might want to display `aaa /bbb/ ccc "ddd"`.

Also, the `NAME` might already contain the `NICK`.  Earlier versions of GEDCOM placed the nickname between quotes in the name.

So, we should not try to add it it this name

```
1 NAME aaa "bbb" /ccc/
2 NICK bbb
```

But should we add it to this name?

```
1 NAME Jean-Marie /Leclerc/
2 NICK Marie
```

Personal names have much complexity.  If we attempt to automatically process them, we will always find exceptions and special cases.

The only solution is to simply display the name as it is entered.

It would be straightforward to write a batch-update plugin that adds the `NICK` to the `NAME` using the existing logic.

**Comment by JustCarmen** [comment]
wt 1.7.9
![image](https://user-images.githubusercontent.com/5641963/31566490-2bbbe8a8-b06b-11e7-9c01-8816ce58b3c1.png)

wt 2.0.0
![image](https://user-images.githubusercontent.com/5641963/31566501-35a3f3b0-b06b-11e7-8b6f-6ffea9ced4c7.png)

The first one is correct. Why not leave it as is?

> It would be straightforward to write a batch-update plugin that adds the NICK to the NAME using the existing logic.

Probably. But adding the NICK  to the NAME should not be the only option. I rather enter the names as found in the birth certificate or other official records. The NICK  is not retrieved from those records.

And if this is a language thing, why not add a configuration option to keep everybody happy.

**Comment by ric2016** [comment]
I agree - The logic should be left as it is. Or at least add a configuration option, as suggested.

By the way, if the nickname is part of the name, why enter it separately at all? You can already mark part of the given name as "Rufname" (via asterisk).

**Comment by fisharebest** [comment]
The GEDCOM 5.5 standard did not have name parts (`GIVN`, `SURN`, etc).  It only had the `NAME` record.

It said that the nickname should be written in quotation marks.  e.g.

`1 NAME Jack "The Hat" /McVitie/`

This was because there was nowhere else to store the nickname.

Since GEDCOM 5.5.1, we have name parts.  In the "Changes from 5.5" section, it says:

> Removed the convention of specifying a nickname in double quotes

If you want to store the nickname in the `NAME`, then you can.  5.5.1 allows this.

But this should not be automatic.

For example, it may be appropriate in some names, but not others.  e.g. some nicknames may be used only by close family.

Also, for diminutive names, these are better placed after the full name.  e.g. compare

`Hendrik Arie "Henk" /Honig/`

`Hendrik "Henk" Arie /Honig/`

**Comment by ric2016** [comment]
I don't get it - This is not about storing the nick name in the gedcom (or about changing the way it is stored), but about displaying the nick name. 

Several comments here indicate a preference for keeping everything as it was before, or at least making it configurable. This doesn't seem that complicated to me. Why can't we have this configuration option for everyone who was ok with the way things were?

**Comment by fisharebest** [comment]
> I don't get it - This is not about storing the nick name in the gedcom (or about changing the way it is stored), but about displaying the nick name.

It is about **AUTOMATICALLY** analysing a name and deciding where to insert a nickname.

This cannot be done automatically.  IMHO It is not possible.

Consider these two names.  How can a computer identify the name parts and correctly insert a nickname.

```
1 NAME Professor /Wagner/ Laslo
2 NICK "Lassy"
```

```
1 NAME Peter /Smith/ Junior
2 NICK "Pete"
```

> Why can't we have this configuration option for everyone who was ok with the way things were?

It was not OK for everyone.  It was not OK for users with Hungarian relatives, or any other place where given names come after the surname.

**Comment by ric2016** [comment]
> This cannot be done automatically. IMHO It is not possible.

But it's currently (1.7.9) done automatically. I get that it's maybe not possible to be correct in all cases - but these are edge cases many users do not care about!

> It was not OK for everyone.

I didn't say that. That's exactly why we request a configuration option - so that people can decide for themselves.

**Comment by Amgine0** [comment]
Since you are describing them as edge-cases, the largest cultural group would likely be Han Chinese speaking Mandarin, for whom /Surname/ 'Usename' Givenname 'Intimate_Nickname' would likely be the standard format. And by your logic that should be the default for everyone.

**Comment by ric2016** [comment]
> And by your logic that should be the default for everyone.

No, I didn't say that either - I (and others) would just prefer a configuration option for this! How is that so hard to understand?

**Comment by fisharebest** [comment]
> How is that so hard to understand?

I understand exactly what you want.  But it is not as simple as you think.

For example, we store the full name in the database (for sorting and searching).

We also need to match the name of an individual to a name in the database.
If you change the config, then many things (e.g. individual list) will break until you re-import your data.

**Comment by ric2016** [comment]
ok, now I finally get it. The 'full name' stored in the database includes (in 1.7.9) the nickname (taken from 2 NICK):
`Hendrik "Henk" Arie`

I agree this isn't a good idea. I always thought this was just about displaying the name (by including the nickname on-the-fly, whenever the name is printed). Maybe the two aspects could be separated? Not sure how this would work for searching though.

**Comment by ric2016** [comment]
> If you change the config, then many things (e.g. individual list) will break until you re-import your data.

By the way, how is this handled when upgrading from 1.x to 2.x? The format of the full name stored in the database table has changed with regard to the nickname; is it therefore advisable to re-import when upgrading?

**Comment by melizaa** [comment]
I have over 2000 individuals with one or two nicknames.

Could we add a utility that would add the nickname in ""-s to the end of the Given name and the Givenname in the Name and remove the nickname?

We should ensure that the name sequence is not changed.
Now, when I update two names online one after the other, the second name (Hebrew) becomes the first name.
