### ISSUE TITLE
dev - Charts do not honor current indi

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1608]
Locate any individual and then select a chart.  Instead of the individual represented in the chart, it's the default individual.

**Comment by fisharebest** [comment]
I think there is a duplicate issue for this.

I am in the middle of converting all the pages to use "HTTP controllers".  i.e. functions that take an HTTP request and return an HTTP response.

The existing code relies on global variables, and is very "monolithic".  I can't fix this until I have finished converting the remaining pages.  This is because we have some temporary code that bridges the new template system with the old theme system.

Once all the changes are made, I can update the themes to use the templates - and we will then be able to pass these "significant individual/family/surname" links to them.

**Comment by makitso** [comment]
Greg,  how you doing on this issue, it's kind of a pain.
