### ISSUE TITLE
Ability to select language and/or tab on URI.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#1624]
As discussed in
https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/31973-how-can-a-particular-tab-be-activated-with-a-link
it would be nice to have the ability to give someone a link (URI) that not only takes them to a particular webtrees page, but also controls the tab and/or language.

For the tab, it would have mnemonic value if the tab label and the URI component matched.  Since tab labels are can be in many languages, I suggest the language that has the largest number of users, with documentation for everyone else.

For language, I suggest the same strings used to name them in the code, e.g., en-US, pt-BR, jp, etc.

**Comment by magicsunday** [comment]
Why control language by url parameter?

Language should mainly depend on the locale settings of the used browser and only be overwritten if the user changes it by hand. I guess this behaviour is already implemented.

**Comment by WGroleau** [comment]
Because people want to be able to give someone else a link that "just works" instead of having to say, "Click here, then select your language from a menu in the upper right corner, and then click on the tab that says 'family'"

**Comment by fisharebest** [comment]
Raising two issues in one is always problematic.

Pre-selecting a tab using a URL fragment (`#sources`) is something we definitely need.

We cannot use a URL parameter (`?lang=de`) to select a language because it would result in search-engines spidering your site in every available language.

For some types of site, this might be desirable.  But for webtrees, it simply creates lots of duplicate content which creates a large server load and negatively affects SEO.

Using browser-negotiation (or IP/region detection) to select the initial language is pretty much the "industry standard".  If someone sees the wrong langauge on webtrees, I am sure they will see it on many other sites as well.

Perhaps the real problem is that the language menu is hard to find.  It is text-only.  An icon would certainly help.  There are a few that are becoming fairly well established.

**Comment by WGroleau** [comment]
I’ll go along with having an icon for the language menu.  But please, no flag of one country to select a language that’s spoken in more than one.

**Comment by fisharebest** [comment]
> no flag of one country to select a language that’s spoken in more than one

Agree 100%
