### ISSUE TITLE
Query on creating a chart view/route

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1654]
Hi Greg,
As a learning exercise, I'd like, within the openstreetmap module, to convert the Pedigree Map chart structure to use a view. I think I need to do the following:  

**create files**
app/Http/Controllers/PedigreeMapChartController.php
resources/views/pedigreemap-chart.php
resources/views/pedigreemap-page.php

**add**
'GET:pedigreemap'               => 'PedigreeMapChartController@page',
'GET:pedigreemap-chart'         => 'PedigreeMapChartController@chart',
to routes/web.php

**modify** function getChartMenu in openstreetmap module to point to routes/web/pedigreemap

I assume scripts should be loaded in a view? which one?
anything else?

**Comment by fisharebest** [comment]
> I think I need to do the following

That's basically it.

[The hard part of converting the old code to this structure is untangling code that mixes the logic and the layout.]

> I assume scripts should be loaded in a view? which one?

I've been putting JS in the same view to which it applies.  e.g. in `resources/views/pedigreemap-chart.php`

**Comment by ddrury** [comment]
Ta

**Comment by fisharebest** [comment]
FYI, I've created `ModuleController` as a replacement for `module.php`, which uses the new routing system for calling module functions.

e.g. this route: `route('module', ['action' => 'FooBar', 'module' => 'my_module'])`

will call either `MyModule::getFooBarAction()` or `MyModule::postFooBarAction()` depending on the HTTP verb used.

You'll probably want to use this instead of modifying `routes/web.php`

**Comment by fisharebest** [comment]
Hold that thought.  I've missed a load of stuff....

**Comment by fisharebest** [comment]
I'll need to leave this until after the remaining code is converted to use page-views, and the page headers are also replaced with templates.

**Comment by ddrury** [comment]
Good fun isn't it!

I've been wondering if it wouldn't be better instead of having one module that serves 3 things (Individual tab, Pedigree map & place hierarchy) to split this out into 3 separate modules and use the original module to just manage the admin functions & provide map assets to the other modules.

What do you think.
BTW, the changes you've started (above) would make it easy to keep one multipurpose module (as now)

**Comment by ddrury** [comment]
Well, converting the Pedigree Map to Route/View turned out to be quite simple, however I can't see how to do the config stuff. I think an AbstractModuleController is needed to provide functions like checkModuleIsActive and somehow provide a mechanism to get/set preferences

**Comment by ric2016** [comment]
I'm currently converting my custom modules so that they can be used in webtrees 2.x. I have a few related questions:

1. If I use a view in a custom module (or in fact any module), shouldn't its location be something other than 'resources/views/xyz.php', i.e. shouldn't it be located in the custom module's own folder? The path ('resources/views/') is hardcoded in `View.php` though. Are custom modules supposed to use their own adapted View class instead? Or should we add a constructor in `View.php` which allows a custom path?
 
2. Regarding the view data:

`@var mixed[] Data to be inserted into the view`

This makes it hard to determine what data is actually provided to the view - if e.g. a theme intends to extend a view, there is no way to determine the arguments and their types easily, certainly not by checking the view implementation. Or am I missing something here?

**Comment by fisharebest** [comment]
The intention is to migrate the code onto laravel

For webtrees 2.0, I am simply refactoring the code into a "laravel-like structure".

So, the "laravel" answer is that modules (aka [Laravel packages](https://laravel.com/docs/5.6/packages)) will need to add search paths for their own views, routes, etc.

But this functionality will not exist for 2.0.   (It does not exist in 1.7.9)

> certainly not by checking the view implementation

The view is just a PHP template - every variable in the view must be provided.  It should be easy to see them all.  I use [PhpStorm](https://www.jetbrains.com/phpstorm/), which highlights the first use of each variable.

Also, you can look at the parameters used by the core code.  Search for `view('view-name'`

Short answer - be patient.  I need to refactor 250,000 lines of spaghetti code into a modern structure.  I have completed most of the task.  There are just a few components left (searching, messages, place list, edit forms).  When these are complete, I can convert the themes from functions to templates and then we can release 2.0.0-alpha.

After that, the plan is to tidy the HTML/CSS and then release 2.0.0-beta.

I do understand that all these changes and instability make it difficult for third-party developers.
