### ISSUE TITLE
Hourglass chart data outside the page - demo-dev

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#1692]
Hourglass chart of 4 generations rightmost data prints outside the page. 

There is no bottom horisontal scroll-bar.

**Comment by makitso** [comment]
Unfortunately, the patch I submitted for this issue did not do the job.  Ideal, an overflow-y: visible; would be the optimal solution.  However, this is not possible due to use of overflow-x (forces visible to become auto).  As such, a vertical scroll bar is visible when not really needed unless you mouse over the pedigree popup.

**Comment by fisharebest** [comment]
If this is still a problem, can you post a URL or screendump so that I can see what is happening.  Thanks.

**Comment by melizaa** [comment]
We see still an unnecessary scroll bar.
![2018-08-13_01-10-21](https://user-images.githubusercontent.com/5202996/44006969-be222180-9e95-11e8-84d2-debfe69942c8.jpg)

**Comment by makitso** [comment]
Unfortunately, the patch I submitted, some time ago, for this issue did not do the job. Ideal, an overflow-y: visible; would be the optimal solution. However, this is not possible due to use of overflow-x (forces visible to become auto). As such, a vertical scroll bar is visible when not really needed unless you mouse over the pedigree popup.

**Comment by fisharebest** [comment]
The scrollbar was caused by the old menus in each chart box.

We've replaced them with bootstrap menus, which position themselves automatically.
