### ISSUE TITLE
A question of strategy

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#1715]
With regard to the OpenStreetMap module, pedigree map option, there are two ways to go - either extend `app/Http/Controllers/AbstractChartController `or use `app/Http/ModuleController` - as the function is wholly part of the module I felt the proper way to go was the latter, however this creates a problem.

 Within the Googlemaps module, the ancestors are obtained by instantiating an `app/ChartController `object and calling sosaAncestors(). I believe this controller is deprecated so looked for a different approach for OpenStreetMaps. I can't call `sosaStradonitzAncestors() `in any controller derived from `app/Http/Controllers/AbstractChartController` as it's a protected function so I've had to duplicate the code in the module.
 
 If I took the alternative route of extending AbstractChartController, I get a different problem insofar as the map data is obtained by a jQuery getJSON call (common to all map types) to the module so I'd have to change that code somehow.
 
 Any suggestions as to your preferred solution?

**Comment by fisharebest** [comment]
I'm almost at the stage of updating the existing modules, so I guess I'll come to this problem myself shortly...

The issue is one of fat-controllers versus thin-controllers.  Fat-controllers are ones that contain all the business logic (such as generating a list of ancestors).  Thin-controllers call other entities (often called "sevices" or "service providers") to handle the business logic.

The process of migrating the existing code to the route/controller/view structure has led to a fat-controller layout.

I was hoping not to have to deal with this until later, as it would just further delay the next release.

> Any suggestions as to your preferred solution?

For the sake of expediency, you could just duplicate the functions, and add an `@TODO` annotation in the comment.

**Comment by ddrury** [comment]
> For the sake of expediency, you could just duplicate the functions, and add an @TODO annotation in the comment.

That makes it easy, I just have to add the @TODO
