### ISSUE TITLE
More friendly URLs [2.0.0]

### ISSUE THREAD

**Issue by robert-scheck** [fisharebest/webtrees#1809]
Taking https://dev.webtrees.net/demo-dev/index.php?route=individual&xref=i1&ged=demo for example is not really a friendly URL, while I would treat something like https://dev.webtrees.net/demo-dev/demo/individual?xref=i1 or similar as way more friendly. Given at least the GED is anyway always (?) part of the URL, such route/rewrite handling should be not that complicated.

**Comment by fisharebest** [comment]
Step one is to convert all URLs to have a `route` parameter and to generate all URLs using a `route()`.

This is complete.

Step two will be to convert the `route()` function to generate pretty URLs.

This is planned for the future.  It will also require changes to the routing table `routes\web.php` to include the pretty URL in addition to the route name and controller/function.

Since webtrees must also run on systems without URL rewrites, the plan is for the `public` subfolder to be the target for pretty URLs, and the root folder to be the target for ugly URLs.

**Comment by JustCarmen** [comment]
Also see: https://github.com/fisharebest/webtrees/issues/1517

**Comment by fisharebest** [comment]
Please add any further comments to #1517
