### ISSUE TITLE
Security Issue -- browser still logged in to web site even after restart.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#1813]
Both Win 10 and Linux:
Log into my 2.0 production system.  I terminate browser, FF or Chrome.  I restart browser and to to my site and it shows that I am still logged in.

**Comment by fisharebest** [comment]
I recently replaced calls to `ini_set()` with calls to native PHP functions (because `ini_set()` is blocked on some servers).

There are two parameters called `lifetime`, and our webtrees "session lifetime" setting got applied to the wrong one.

(This change was made by accident, rather than by design...)

The session lifetime was previously being used to set the minimum time after which inactive sessions should be cleaned up.  It is now being used to set the session lifetime explicitly.

Before fixing it, I wonder if we still need this option in webtrees?

With the old code, you'd get logged out after whatever time was configured.  Is this actually needed/useful?

We could set the session lifetime to `0` - which would keep it active for as long as the browser is running - and then run the cleanup of inactive sessions to purge ones that are more than a few days old?

Thus you'd stay logged in for as long as you kept your browser open, provided you did something every couple of days.

**Comment by makitso** [comment]
IMO, the session should live as long as I have my browser open.  It should be destroyed when I close the browser.
