### ISSUE TITLE
$noterec not definded

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1837]
https://github.com/fisharebest/webtrees/blob/d058bf46217ff15e573597ec53da080010b97477/app/Functions/FunctionsPrintFacts.php#L1092

**Comment by fisharebest** [comment]
Looking through the code history, this bug was introduced in 2013.

Earlier versions attempted to print sources linked to shared notes on the notes tab.

IMHO:
* source provide evidence for genealogical facts,
* notes are comments or annotiations by the genealogist,
* so it does not make sense to add a source to a note.

I'll remove this
