### ISSUE TITLE
Can't find GEDCOM Export/Download

### ISSUE THREAD

**Issue by boydhako** [fisharebest/webtrees#1875]
Is there any way to export or download the data into a GEDCOM file?

Why? Interlinking between genealogy software like Ancestry.com and stuff.

**Comment by magicsunday** [comment]
Sure. Go to the `Control panel` => `Manage family trees`.

There you will find `Export a GEDCOM file`.

**Comment by boydhako** [comment]
Don't suppose there's some command line trickery to get it generate the GEDCOM file on the server is there? 

I'm trying to setup automated backups and distribution to the contributors via email and what not.

**Comment by magicsunday** [comment]
Maybe the database backup module http://www.justcarmen.nl/fancy-modules/fancy-database-backup/ help you a little bit?

**Comment by fisharebest** [comment]
> Don't suppose there's some command line trickery to get it generate the GEDCOM

Not at the moment.  Most of the functionality is closely tied in to HTTP requests and sessions/user authentication.  This also makes it difficult to write test scripts.

Which is why this type of "business logic" is currently being extracted into standalone ["services"](https://github.com/fisharebest/webtrees/tree/master/app/Services).

So, adding CLI functions like this will be possible soon.
