### ISSUE TITLE
MapProviders - code not currently used

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#1876]
The methods `getProviderStylesAction` and `getMapProviderData` in `PedigreeMapModule` (https://github.com/fisharebest/webtrees/blob/master/app/Module/PedigreeMapModule.php#L215) and `PlacesModule` (https://github.com/fisharebest/webtrees/blob/master/app/Module/PlacesModule.php#L171) or identical but seem not to be called anywhere. Is that right? Could they removed?

[](url)

**Comment by fisharebest** [comment]
The original mapping module (contributed by @ddrury) used [leaflet-providers](https://github.com/leaflet-extras/leaflet-providers) module to allow the maps to work with different map providers.

This package only works with open-source providers.

I commented it out because I want to look at this area more closely.

Ideally, we would have a "MapProviderInterface", with a number of different implementations.

In particular, it would be nice to support commercial map providers (such as google) as well as the free/open-source ones.
