### ISSUE TITLE
View names are not module specific

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2054]
In my module I named my template "fan-chart.phtml". But this collides with the existing resource (resources/views/fan-chart.phtml) although my template is module specific. If both modules (native and my own) are enabled the default module fails to render as it tries to load my modules template file! I could rename my template file of course but that will not solve the problem in my opinion.

**Comment by fisharebest** [comment]
The plan is to migrate to the Laravel framework, and the webtrees view system is a simple implementation of Laravel views.

Laravel uses namespaces for module views (see https://laravel.com/docs/master/packages#views).
Modules can choose to use their own namespace - or override the core views.

So, it is intentional that modules can override core views.  This is how I am planning to combine the theme system into the module system.

Updating the module system is next on my list.  I'll look at this as part of that task.

Until then, it will be simpler if you choose a unique name ;-)
