### ISSUE TITLE
Translation server gives error

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2112]
I get 502 Bad Gateway
for https://translate.webtrees.net/projects/webtrees/webtrees/

**Comment by magicsunday** [comment]
Any updates on this?

**Comment by fisharebest** [comment]
I have spent another day trying (and failing) to install this software.

If anybody wants to help....

**Comment by magicsunday** [comment]
What did you tried yet?

**Comment by fisharebest** [comment]
I follow the installation instructions https://docs.weblate.org/en/latest/admin/install.html

(I'm installing on an Ubuntu 18.04 server with nginx).

The result is usually a python stack dump that contains no keywords that would help in a google search.

**Comment by fisharebest** [comment]
I think I could have written a simple tool in PHP in less time than I have spent trying to install weblate.... ;-)

**Comment by magicsunday** [comment]
Same here. I get stuck while trying to run the server. :(

root@xxx:# pip install Django
Requirement already satisfied: Django in /usr/lib/python3/dist-packages (1.8.7)
root@xxx:# ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    from weblate.runner import main
  File "/weblate/__init__.py", line 23, in <module>
    from weblate.vcs.base import RepositoryException
  File "/weblate/vcs/base.py", line 33, in <module>
    from django.core.cache import cache
ImportError: No module named django.core.cache

**Comment by magicsunday** [comment]
May https://crowdin.com/ an alternative?

**Comment by fisharebest** [comment]
I have created a temporary translation server at http://weblate.iet.open.ac.uk/projects/webtrees/webtrees

This is actually an old "weblate" server that I created for some projects at work some years ago.

Since it is running a very old copy of the translation software, there are bugs that I cannot fix.
For example, I think that this version has problems with some search functions.

You will need to register again for this site.  Your login details on the old server cannot be transferred.

Also, there is no automatic synchronisation with github.  I need to do this manually, so there will be a delay before new translations appear.

Once I am happy that it is working, I will set up a redirect from the old URL to the new one.

**Comment by fisharebest** [comment]
I have set up a redirect from the old server https://translate.webtrees.net/projects/webtrees/ to the new server http://weblate.iet.open.ac.uk/projects/webtrees/

The old server uses HTTPS (and HTTP strict transport security), and the new server does not.  Therefore I cannot map the domain name to the new server.
