### ISSUE TITLE
Parents age on baptism/christening

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#2180]
We currently show the ages of parents on birth events.

Where no birth event exists, we could show them on of the other "start of life" events, such as baptism or christening.

**Comment by Amgine0** [comment]
+ adoption

**Comment by HRN-webtrees** [comment]
Note that baptism is not always a "start of life" event. To many people baptism is seen as an act identifying one as having accepted Jesus Christ as savior, and may happen late in life. And to many people there is a difference between christening and baptism.

**Comment by fisharebest** [comment]
In many cases `BIRT` and `DEAT` details are unknown - but other details such as `BAPM` and `BURI` *are* known.

> Note that baptism is not always a "start of life" event.

You are right, of course.  But showing an event which usually occured a few days later gives a better user experience than showing nothing.

For example, the individuals table, lifespan summaries, etc.

Here's the list from the code:

```
    // Gedcom tags which indicate the start of life.
    public const BIRTH_EVENTS = ['BIRT', 'CHR', 'BAPM', 'ADOP'];
    // Gedcom tags which indicate the end of life.
    public const DEATH_EVENTS = ['DEAT', 'BURI', 'CREM'];
```

**Comment by HRN-webtrees** [comment]
I think the problem here is the terms christening (CHR) and baptism (BAP), how they are undestood, used in different faiths, and translated in different languages.
I never thought of the difference until a few years ago, when I was "arrested" for using CHR for a baptism (I do have a few late 1800's baptists in my tree).
I was then thaught by a baptist that they do not baptise/christen children, and that there indeed is a difference between the two. Here in Norway you will need parents consent for baptism if under 15 years old. For this reason, baptism (of own free will) is an event that will take place later in life, and could in fact be closer to death than to birth. 
I guess most people use CHR/BAP interchangeably, but we must understand that some users see it differently. That's maybe why there are two different tags?

https://en.wikipedia.org/wiki/Believer%27s_baptism

Personally I use CHR (BAP for baptists only), and if date of birth is not known I will register as following: 
1 BIRT
2 DATE BEF 19 OCT 1755
1 CHR
2 DATE 19 OCT 1755

However, I guess there will be no consensus on the use of CHR vs BAP until there is consensus on faith ;)

**Comment by magicsunday** [comment]
As I understood:

CHR - a christian ceremony at which a baby is given a name and made a member of the christian church 
BAPM - a christian ceremony in which a person becomes a member of the christian church (later in life and on his own will)

**Comment by HRN-webtrees** [comment]
GEDCOM 5.5.1:

BAPL {BAPTISM-LDS}:=
The event of baptism performed at age eight or later by priesthood authority of the LDS Church.

BAPM {BAPTISM}:=
The event of baptism (not LDS), performed in infancy or later.

CHR {CHRISTENING}:=
The religious event (not LDS) of baptizing and/or naming a child.

 Anyway, I now see I misunderstood Greg's posting.
I was too quick, and thought the intention was to use date of christening/paptism to calculate age....

**Comment by Amgine0** [comment]
Please keep in mind that far less than half the people in the world are Christian, let alone Protestant, and Webtrees is probably intended to be a generalist genealogical software, and not a software which exactly aligns with the jargon of any specific faith or creed.

CHR is commonly used to apply to any documented public naming ceremony, particularly those shortly after birth.

BAPM is usually used to apply to any documented religious induction ceremony, particularly those shortly after birth.

**Comment by ric2016** [comment]
We had the BAPM/CHR-discussion before; bottom line is that these tags are simply not used consistently.

The best way to deal with them - in the context of the original issue - is probably to have an additional configuration option where the tree admin can decide explicitly which tags to use as additional "start of life" events.

**Comment by fisharebest** [comment]
This feature is likely to cause more problems that it solves.
