### ISSUE TITLE
2.0 – No longer able to make simple style changes to themes

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2219]
With the release of public-folder generated themes (github Commits on Feb 7, 2019) users of webtrees can no longer make simple style changes to their site – the /themes folder is no longer available. This is due in part to the fact that theme style’s are now generated by the npm framework and minified.  In addition, there is no longer a common.css file for putting style changes that are theme-wide.

Request that webtrees 2.0 add a _common.css in public/css folder and that a link be added to resources/views/layouts/default.phtml.

**Comment by fisharebest** [comment]
The compilation process does more than just combine/minify the files.  It provides automatic LTR/RTL mirroring and adds support for older browsers.

> users of webtrees can no longer make simple style changes to their site

If, for local development, you do not need support for RTL or older browsers, you can use the source files directly by changing the `stylesheets()` function to point to them.  e.g. for the Colors theme, change it from this:

```
    public function stylesheets(): array
    {
        return [
            asset('css/colors.min.css'),
            asset('css/colors/' . $this->palette . '.min.css'),
        ];
    }
```

to this:

```
    public function stylesheets(): array
    {
        return [
            asset('../resources/css/colors.css'),
            asset('../resources/css/colors/' . $this->palette . '.css'),
        ];
    }
```

Alternatively, create a custom theme, based on one of the original themes, which adds a extra CSS file to the `stylesheets()` function.  You'll get all the benefits of the compilation process plus your local mods.  I'll be providing more information on how to create custom themes shortly.  I might even add a module based on the popular "custom javascript" module which allows users to add any CSS or JS site using the control panel.

> there is no longer a common.css file

The "common CSS" file has been split into lots of separate files for easier maintenance.  These files contain *functional* or *behavioural* things, rather than *presentational* things.  The actual appearance should be goverened by the particular theme.

**Comment by makitso** [comment]
No offence intended but I do not fell this is a good answer. Creating a custom template is or may be beyond the skill of many site operators.  And, it does not address common theme changes.

> The "common CSS" file has been split into lots of separate files for easier maintenance.
But, not for webtrees site owners.  If and when 2.0 ever reaches production, site owners will not have a resources folder.  So, their out of luck.  This is not a position that is in the best interest of your customers.

**Comment by fisharebest** [comment]
I've added a new module (disabled by default) which gives you way to add CSS and JS using the control panel.

**Comment by makitso** [comment]
Nice!  This allows me to add the link for common.css
