### ISSUE TITLE
RTL dates - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2283]
I see wrong dates on rtl pages at least in the messages, news and journal blocks and on the pending changes page.

See a sample of the pending changes on the Hebrew page:
![2019-02-28_22-40-55](https://user-images.githubusercontent.com/5202996/53597264-65359400-3baa-11e9-8eb9-384eeefb9048.jpg)
and on the English page:
![2019-02-28_22-40-02](https://user-images.githubusercontent.com/5202996/53597307-7ed6db80-3baa-11e9-893a-662c6bdb045e.jpg)

**Comment by xmlf** [comment]
Webtrees log The date is also wrong, and the date of the pending change is much different. The pending change date is correct

**Comment by melizaa** [comment]
Also the Changes in the last n days prints the date in a wrong format in rtl pages.
I spoke of the Pending changes page, not the block.

The month is not translated in the . I see this also in the pending changes block.

**Comment by fisharebest** [comment]
I'm in the middle of converting to the [nesbot/carbon](https://carbon.nesbot.com/) library for timestamps.

I had to wait until yesterday for another package to get updated so that I can use version 2 of `carbon` (which has the localisation support that I need).

I did have another look at this over lunch, but I ran out of time.

**Comment by fisharebest** [comment]
I've just added the new timestamp handling library, which should fix these.
