### ISSUE TITLE
2.0.0-alpha.5 Missing message on sign-in block

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2327]
The text defined in Control panel / sign-in and registration is not shown on the home page "Sign in" block

**Comment by magicsunday** [comment]
This text has never been displayed there.

**Comment by fisharebest** [comment]
@ddrury - you did not say if you want/need this text to be displayed - or if you simply noticed that it was not there.  (I guess the latter?)

IMHO, this is not a very useful block.  But one possible use is to embed it in an HTML block.

HTML blocks cannot simply create `<form method="post">` elements, as they also need a CSRF token.

So, keeping it simple seems to make it more useful.

I'm going to close this, since it is "working as designed".  If you want to request a specific change, feel free to open a new issue.
