### ISSUE TITLE
2.0 - language problem

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2348]
I am not sure if this is a problem or not.   

Someone from Great Britain accessed my site and I think their browser was set to British English.
Now I only have American English {en-US) defined in resources/lang folder.  Did this generate the error below?

ErrorException: filemtime(): stat failed for /resources/lang/en-GB/messages.mo in file /app/I18N.php on line 388 Stack trace: 1. ErrorException->() /app/I18N.php:388 2. filemtime() /app/I18N.php:388 3. Fisharebest\Webtrees\I18N->init() /app/Http/Middleware/UseLocale.php:47 4. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:161 5. {closure}() /app/Http/Middleware/UseTree.php:58 6. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:161 7. {closure}() /app/Http/Middleware/UseSession.php:59 8. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:161 9. {closure}() /app/Http/Middleware/UseFilesystem.php:50 10. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:161 11. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48 12. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:161 13. {closure}() /index.php:178

**Comment by fisharebest** [comment]
The control panel only controls which languages are shown in menus, etc.

For new visitors, browser negotiation means that *all* languages are available for a user's first visit.

This way, I don't need to have Russian in my menu or configuration options - but a Russion visitor will still see my site in a language they understand.

The the same logic was used in 1.7.  The difference is that previously we looked for .MO files.  Now we look for language modules.  The build/release process creates a .MO file for each language module.

Now, your problem is that you are using a development build (which excludes .MO files).  With an official distribution, these would be included.

If you have `gettext` and `composer` installed, you can build all the .MO files with the command 

```php composer.php webtrees:mo```

Otherwise, you can download them from the demo server.  e.g. https://dev.webtrees.net/demo-dev/resources/lang/en-GB/messages.mo

**Comment by fisharebest** [comment]
BTW - part of the reason for this change is that having "langauge modules" means that we now have somewhere to store/group logic for things like

* default paper size
* starting day of the week in the calendar
* surname rules
* relationship name calculations
* etc.

**Comment by makitso** [comment]
I have 9 languages available for my site, 9 languages modules defined and 9 languages folders defined in resources.  So, I will get this error in the log file for any visitor who has a browser language not included in these 9?

**Comment by xmlf** [comment]
when the corresponding language module is not found, it should be displayed in the preferred language set by the control panel. This might be better.

**Comment by fisharebest** [comment]
> So, I will get this error in the log file for any visitor who has a browser language not included in these 9?

Yes.

I want to avoid lots of unecessary calls to `file_exists()`.

All the .MO files are included in the release builds - including `alpha`.

(You can download .alpha.5 and copy the .MO files from there.)

So, this will only be an issue for some who has installed using `git clone`.

**Comment by makitso** [comment]
OK, now I understand.  I was using the resources/lang file from github.  Now I am using the resources/language from the alpha release for my prod and  test sites.
