### ISSUE TITLE
error in the Website log - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2352]
I see in the last day's test log the following. Is it already solved?

ErrorException: filemtime(): stat failed for /resources/lang/cs/messages.mo in file /app/I18N.php on line 388 Stack trace: 1. ErrorException->() /app/I18N.php:388 2. filemtime() /app/I18N.php:388 3. Fisharebest\Webtrees\I18N->init() /app/Http/Controllers/UserController.php:80 4. Fisharebest\Webtrees\Http\Controllers\UserController->language() [internal]:0 5. ReflectionMethod->invoke() /app/Application.php:45 6. Fisharebest\Webtrees\Application->dispatch() /index.php:175 7. {closure}() /app/Module/HitCountFooterModule.php:185 8. Fisharebest\Webtrees\Module\HitCountFooterModule->handle() /index.php:161 9. {closure}() /app/Http/Middleware/CheckCsrf.php:60 10. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:161 11. {closure}() /app/Http/Middleware/UseTransaction.php:43 12. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:161 13. {closure}() /app/Http/Middleware/DebugBarData.php:41 14. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:161 15. {closure}() /app/Http/Middleware/BootModules.php:59 16. Fisharebest\Webtrees\Http\Middleware\BootModules->handle() /index.php:161 17. {closure}() /app/Http/Middleware/UseTheme.php:71 18. Fisharebest\Webtrees\Http\Middleware\UseTheme->handle() /index.php:161 19. {closure}() /app/Http/Middleware/UseLocale.php:52 20. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:161 21. {closure}() /app/Http/Middleware/UseTree.php:58 22. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:161 23. {closure}() /app/Http/Middleware/UseSession.php:59 24. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:161 25. {closure}() /app/Http/Middleware/UseFilesystem.php:50 26. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:161 27. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48 28. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:161 29. {closure}() /index.php:178

**Comment by fisharebest** [comment]
See https://github.com/fisharebest/webtrees/issues/2348

**Comment by magicsunday** [comment]
I guess https://github.com/fisharebest/webtrees/pull/2349 is obsolete if you dont want to use file_exists? May be webtrees should hide exception by default in all environments, to not expose internal data?

**Comment by fisharebest** [comment]
This is part of a bigger problem.

In general, you cannot always expect to download the source-code for a project and use it immediately.  There is often a build or installation process.

In particular, we should not include the `/vendor` folder in our source code.  Instead, a developer should use `composer install` to obtain these files.  We include them because we forked from a project PhpGedView which included them.  I would like to remove them from our source-code as well.

We also need `npm` to download and build our CSS and JS assets.  We store the compiled `.min.js` and `.min.css` files in our source code, and not the full `node_modules` folder (500MB).

This is probably acceptable.  The alternative is to have a 

I **do** want to make it easy for people to use the development code without having access to a full development environment.  But I also want to follow best practice.

One option might be to provide a `.zip` file containing all the compiled/downloaded assets - `/vendor`, the `.mo` files, the `.min.xx` files, etc.

I have been looking at ways to reduce our external dependencies.  I have found a PHP package that might replace `gettext`.

I want to think about this some more.

Until then, you wlll need to download the latest `.alpha.zip` and copy the `resources/lang/*/messages.mo` files to your working folder.

**Comment by fisharebest** [comment]
In the latest code:

* stable releases will contain `resources/lang/*/messages.php`.
* dev code will contain `resources/lang/*/messages.po` - and webtrees will automatically convert them to `messages.php` when they are first used.

It also means that after `messages.po` is updated (e.g. after `git pull`), then you can rebuild `messages.php` by deleting it.
