### ISSUE TITLE
Firefox chooses the wrong language file

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2359]
Although I fixed the browser language problem before, today I found that the firefox browser defaults to zh-CN, zh; q=0.8, zh-TW; q=0.7, zh-HK; q=0.5, en-US; =0.3,en;q=0.2.
So when browsing with Firefox, the English language is still displayed first.

**Comment by fisharebest** [comment]
Which version of firefox does this?

**Comment by xmlf** [comment]
All versions are like this.
Including the latest version I just downloaded from
https://www.mozilla.org/zh-CN/firefox/new/

![firefox](https://user-images.githubusercontent.com/26761596/56261223-c68ad580-610c-11e9-8507-1d74beea39d5.JPG)

**Comment by kexuebin** [comment]
Hello, how do you fix the default mobile browser and computer browser open in English.

**Comment by xmlf** [comment]
> Hello, how do you fix the default mobile browser and computer browser open in English.

你可以暂时使用中间件模块，通过客户浏览器语言进行判断，定义不同的locale。

**Comment by fisharebest** [comment]
According to the HTML standards, the correct codes are `zh-Hant` and `zh-Hans`.

* https://www.w3.org/International/geo/html-tech/tech-lang.html#ri20040429.113217290
> Where possible, use the codes zh-Hans and zh-Hant to refer to Simplified and Traditional Chinese

* https://en.wikipedia.org/wiki/IETF_language_tag
> zh-Hans and zh-Hant should be used instead of zh-CN and zh-HK. 

* https://tools.ietf.org/html/bcp47
> zh-Hant (Chinese written using the Traditional Chinese script)
> zh-Hans (Chinese written using the Simplified Chinese script)

etc.

------

Mozilla/firefox ignores the standards.  Instead, it uses `zh-CN` and `zh-TW`

https://product-details.mozilla.org/1.0/languages.json

------

webtrees has code to match `zh-CN` with `zh-Hans`.  Here are the tests:
https://github.com/fisharebest/localization/blob/master/test/LocaleTest.php#L159-L187

The code creates a lower-priority language.

If the user requests `zh-CN;q=1.0`, we assume the user also wants `zh-Hans-CN;q=0.5`;
If the user requests `zh-Hans-CN;q=0.5`, we assume the user also wants `zh-Hans;q=0.25`;

The problem is that Firefox also asks for `en-US;q=0.3` :-(

0.3 > 0.25.  So you get English...

**Comment by kexuebin** [comment]
Not only Firefox browser display English, UC mobile browser, Wechat browser, QQ mobile browser, Baidu mobile browser, Huawei browser display English.

**Comment by fisharebest** [comment]
For each of these browsers, can you visit "Control panel", "Server information" and tell me the value of

`$_SERVER['HTTP_ACCEPT_LANGUAGE']`

**Comment by kexuebin** [comment]
@fisharebest server information：$ _ SERVER [ 'HTTP_ACCEPT_LANGUAGE']	ZH-CN，ZH; Q = 0.9

**Comment by xmlf** [comment]
MQQBROWERS:zh-CN,zh-CN;q=0.8,zh-TW;q=0.6,en-US;q=0.4

Firefox:zh-CN, zh; q=0.8, zh-TW; q=0.7, zh-HK; q=0.5, en-US; =0.3,en;q=0.2

Chrome:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7

Safari:zh-cn

**Comment by fisharebest** [comment]
From the webtrees forum

> google：$ _ SERVER ZH-CN，ZH; Q = 0.9
> QQ移动浏览器：_SERVER zh-CN，zh-CN; q = 0.8，zh-CN; q = 0.6
> 华为移动浏览器：$ _ SERVER zh-CN，zh-CN ; q = 0.8，en-US; q = 0.6
> UC Mobile Brower：$ _ SERVER zh-Hans-CN，en-US; q = 0.8
> Baidu Mobile Brower：$ _ SERVER zh-CN ，EN-US; q = 0.9
