### ISSUE TITLE
Zoom icon does not change

### ISSUE THREAD

**Issue by maekclena** [fisharebest/webtrees#2422]
In chart boxes, the zoom in icon does not change once clicked. In the current release it changes to a zoom out icon.

**Comment by fisharebest** [comment]
Since this issue was opened, the behaviour has changed.

We no longer click on the icon a second time to "unzoom".

Instead, the full information is displayed in a popup.  The popup is dismissed by clicking anywhere on the screen (or pressing escape).

So there is no longer a need for an "unzoom" icon.
