### ISSUE TITLE
Error creating tree

### ISSUE THREAD

**Issue by adelatour11** [fisharebest/webtrees#2448]
When i create a tree in the latest beta version i have the following error, i have activated and deactivated jit on my mamp server, created an new database and i still have the same issue

```
preg_match(): JIT compilation failed: no more memory
0 @X1@ INDI
1 NAME Joe /BLOGGS/
1 SEX M
1 BIRT
2 DATE 01 JAN 1850
2 NOTE Edit this individual and replace their details with your own.
```

**Comment by fisharebest** [comment]
> When i create a tree in the latest beta version

It always helps to state the exact version. `beta.3` was released only a few hours ago.
The "latest version" may be different before this issue is investigated....

I've not come across this error before, but it looks to be specific to certain versions  of PHP.
Which version are you using?

> deactivated jit on my mamp server

Sorry for not trusting you (not trusting things is a key part of diagnosing software problems!), but can you confirm how you did and verified this.

e.g. you could have updated php.ini but failed to restart php, or the wrong php.ini, etc....

**Comment by adelatour11** [comment]
i was using php 7.3, i just changed to version 7.2.14 and it works fine now, thanks
