### ISSUE TITLE
Suggest:Standardize place input methods

### ISSUE THREAD

**Issue by xmlf** [fisharebest/webtrees#2460]
When adding or editing an individual, you need to enter the “Place" where the event occurred. "Place" in gedcom have strict standard format requirements, and when users enter "Place' through " input fields, " they often do not conform to standard formats.
Suggestion: By dividing a text field into multiple fields, let the user input separately, without causing confusion!
For example：
____ village ____ town ____ county ____ city ____ province ___ country
This can be used to greatly reduce the learning cost of ordinary users.

**Comment by fisharebest** [comment]
Every part of the world uses a different hierarchy.  To allow for every possible subdivision, we would need 10 (or 20?) input fields.  Historical records may use subdivisions that do not exist today.  e.g. "Duchy", "Kingdom", etc.

Also, it forces uses to know/understand the hierarchy.  For example, if I want to enter "Bavaria, Germany", then is Bavaria a state?  a province?  a district?  With separate fields, I cannot enter the data until I consult wikipedia....

Also, this would break the auto-complete function.  At the moment, if I type "Peterb", then my site will suggest "Peterborough, Cambridgeshire, England".  I do not need to type the rest.  With separate fields, this becomes difficult/confusing.

The GEDCOM specification allows us to label the parts of each place.  e.g.

```
1 BIRT
2 PLAC Peterborough, Cambridgeshire, England
3 FORM Town, County, Country
```

However, this feature is largely abandoned.  I do not know of any genealogy software that uses it.

IMHO, we cannot standardize place inputs because place names are not standard.
