### ISSUE TITLE
No button to create new archive in create source dialog (2.0.0 beta 3)

### ISSUE THREAD

**Issue by norpan** [fisharebest/webtrees#2503]
There is no button to create an archive in the create source dialog. In fact, it's not clear how you are to create a new archive. There is no obvious button in the archive list either.

**Comment by fisharebest** [comment]
> There is no button to create an archive in the create source dialog

This is intentional.  It would require a new dialog inside the existing dialog.
"Nested" dialogs are not supported by our UI framework.

> In fact, it's not clear how you are to create a new archive.

Visit the source page.  At the bottom is an "add new fact" option.
You can then select an existing archive or create a new one.

Also, the control panel (family tree preferences) has a section to add a new repository.
The ability to add unlinked records is restricted to administrators, as it is frequently used in error by inexperienced users.
