### ISSUE TITLE
I see CKEditor™ on rtl pages with TM to the left - 2.0.0

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2513]
I copied the ltr text to the rtl text.

![image](https://user-images.githubusercontent.com/5202996/61581102-862f5f00-ab22-11e9-9554-58c837a82a93.png)

**Comment by fisharebest** [comment]
It seems that the browser is treating `™` as a non-directional character instead of LTR text, and therefore places it **after** `CKEditor`.

If the product name was written in RTL text, then this would be the correct behaviour.

I guess that the simplest solution is to change the translation from `CKEditor™` to `™CKEditor`.

**Comment by melizaa** [comment]
I see the TM to the right/left on the all modules page and to the left/right on the admin control panel page. One page shows it correctly and the other wrongly, it does not matter how I update the text.

**Comment by fisharebest** [comment]
I have upgraded the translation software at https://translate.webtrees.net

The latest version allows us to insert LTR/RTL control characters into the translation.

We can use this to fix many of the RTL layout issues.

There is a guide to these control characters here
https://www.w3.org/International/questions/qa-bidi-unicode-controls.en

There are many cases where we attempt to fix RTL issues in the code using HTML markup.
It will be more reliable and efficient to fix them using control characters.

In this case, we have a weak character at the boundary of LTR/RTL text.
The fix it to add a LRM after the ™ character, so that it is included in the LTR run of text.
e.g. `CKEditor™<LRM>`

The translation server should automatically push its changes to github every 24 hours, so this fix will not appear immediately.
