### ISSUE TITLE
Send moderation emails with generic address

### ISSUE THREAD

**Issue by dverdin** [fisharebest/webtrees#2575]
Dear all,
I might have missed something, but just in case, I'll ask here.

When I accept a account creation on my instance, a mail is sent to the requester. The From field of the mail contains my own email, not the generic email I defined in the site configuration.

I defined a DMARC policy with "p=reject" for my own mail domain. As the Webtrees server is not included in my SPF records, the mail is rejected by the destination servers who respect my policy.

If it was only me, it would not be such a big deal. I can change my own SPF record. However, for people using hotmail ot aol email addressses, their mderation mails will always be rejected.

A workaround would be to send mail with a From: field being the one defined in the web site configuration, the one used to send automatic messages.

Regards,

David

**Comment by fisharebest** [comment]
Implement this at the same time as #1945...

**Comment by dverdin** [comment]
Ah yes, I see the problem.
In such a situation, could it be possible to default to the server administrator email ?

**Comment by fisharebest** [comment]
> default to the server administrator

There can be more than one administrator...

**Comment by fisharebest** [comment]
See also #1238

**Comment by fisharebest** [comment]
We have the following potential email participants

* **Site** - as specified in the STMP settings page, either a valid address or a no-reply address.
* **NoReply** -  always `no-reply@localhost`
* **Tree** - the genealogy contact of the tree (when viewing a genealogy page), or the **Site** otherwise.

Note that using `Cc:` is problematic, as messages are localised for each recipient.

If we must always set `From:` header to the **Site** address, then we must set the `Reply-to` header to one of the above.

The idea is that new users should receive messages that they can simply reply-to if they are confused.

Here is my first draft.  It probably needs reviewing....

| Message | From | To | Reply-to |
| ------- | ------- | ------- | ------- |
| Registration | **Site** | new user | **Tree** |
| Registration | **Site** | admins |  **NoReply** |
| Email verified | **Site** | new user | **Tree** |
| Email verified | **Site** | admins |  **NoReply** |
| Account approved | **Site** | new user |  **Tree** |
| Password reset | **Site** | the user | **NoReply** |
| Broadcast message | **Site** | all users | the sender |
| Visitor message | **Site** | **Tree** | the visitor |
| Visitor message copy | **Site** | the visitor | **Tree**|
| Member messages | **Site** | any user | the member |
