### ISSUE TITLE
Error when upgrading to 2.0.0beta4

### ISSUE THREAD

**Issue by norpan** [fisharebest/webtrees#2578]
I upgraded via the web interface, and now I get the following:
Fatal error: Interface 'Symfony\Contracts\Translation\LocaleAwareInterface' not found in /customers/0/f/b/familjen.eu/httpd.www/webtrees/vendor/symfony/translation/TranslatorInterface.php on line 24

**Comment by fisharebest** [comment]
The error message suggests that your upgrade was incomplete, and that you have a mix of old/new files.

These files no longer exist in `symfony/translation` and have moved to `symfony/translation-contracts` (since beta.4).

Can you copy all the files to your server again, and see if that fixes the problem?

**Comment by norpan** [comment]
Yes, I will try that. As I said, I used the web based upgrade that suggested itself.

**Comment by fisharebest** [comment]
> I used the web based upgrade that suggested itself.

It is broken in beta.3 and beta.4 - and does not copy all the files.

Therefore you will also need to upgrade manually next time.

**Comment by norpan** [comment]
Thanks, it does seem to work now.
