### ISSUE TITLE
Form POST request gets redirected to a GET request

### ISSUE THREAD

**Issue by magicsunday** [fisharebest/webtrees#2693]
After submitting a chart form, for instance https://dev.webtrees.net/demo-dev/tree/demo/hourglass-3-1/i34 the POST request gets redirected (302) to a GET request, resulting in duplicate loading of the page.

![issue-2693-01](https://user-images.githubusercontent.com/564393/67546747-5c776c80-f6fd-11e9-883a-aaa290469820.png)

**Comment by fisharebest** [comment]
This is intentional.

Previously, all parameters were in the query string.
A form could use a GET request and form-fields to generate an updated URL.
e.g.

OLD: index.php?xref=I123
NEW: index.php?xref=X456

When the parameters are part of the query string, this is not possible

OLD: chart/X123
NEW: chart/X456

The page is loaded with 2 GET requests.
One loads the page/form.  The other uses Javascript to load the chart.
This technique is used to prevent robots from fetching low-value, high-cost pages.
