### ISSUE TITLE
github - Slide show controls do not react to RTL languages

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2776]
![image](https://user-images.githubusercontent.com/5147603/68977640-ed4ddf00-07b5-11ea-8698-aba81862dc2c.png)

**Comment by fisharebest** [comment]
I just tried this on the demo site, and it worked for me.  Both the start/stop icon and also the next icon.

Do you see any error messages in your browser's console?

**Comment by makitso** [comment]
Perhaps I am not expressing myself correctly.  Prior to the Refactor Icon changes made two days ago, the controls for Hebrew looked like this:
![image](https://user-images.githubusercontent.com/5147603/69000523-4d17b900-088e-11ea-8628-42c697de9701.png)
After the patch the controls for Hebrew look like this:
![image](https://user-images.githubusercontent.com/5147603/69000527-61f44c80-088e-11ea-9818-cbcbc3ee93d6.png)

**Comment by fisharebest** [comment]
Ah, OK.  By "not react", I thought you meant they did not react to clicks.

According to all the online resources I can find, media player controls should always be LTR, even on RTL pages.  This is because the physical "real world" equivalents (e.g. buttons on video players) use LTR icons.

e.g.

https://material.io/design/usability/bidirectionality.html#mirroring-elements
https://www.smashingmagazine.com/2017/11/right-to-left-mobile-design/

**Comment by makitso** [comment]
Interesting links and I see what they say about media controls.  However, If I were a native RTL language person I might react differently.  I have reached out to Meliza and asked for her input on this.

**Comment by melizaa** [comment]
Greg is correct. The media player controls should be the same on RTL and LTR pages, the same as numbers.
