### ISSUE TITLE
Do not show login page at initial connection when user table is empty

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#2793]
Version: 1.7 and 2.0

## The problem
I try to make a Docker image of Webtrees.
See https://github.com/Salokyn/webtrees/tree/docker-1.7/docker
Or https://github.com/Salokyn/webtrees/tree/docker-2.0/docker

At first start of the docker stack, DB is initialized with user and password in `db` container.
Then I create a `config.php.ini` with DB credentials in `app` container.

When I first connect to Webtrees it asks me to log in, but there's no user in DB yet. Webtrees assume a user (admin) has alredy been created when `config.ini.php` exists.

## What I suggest
The setup process could be split in several steps that could be resumed automatically depending on how setup process is already completed:
1. Setup DB and create `config.ini.php`, if not already done;
2. Create tables and first user (admin), if not already done and previous step is OK;
3. Create the first tree, if not already done and previous step is OK.

**Comment by fisharebest** [comment]
> Webtrees assume a user (admin) has alredy been created when config.ini.php exists.

I'm pretty sure most web applications work the same way (and for the same reason);

By providing the DB connection credentials, you are proving that you are the owner of the site, and thus authorized to create the admin account.

It is why we create the database schema and the admin account in a single request.

Otherwise you create an empty database - and then the first random visitor to your site gets the ability to create an admin account...


I have no experience with Docker, but I looked at your scripts.

It uses a variable `$BASE_URL`.
Where does this come from?
If you prompt the user for it, can you also prompt the user for the admin username/password?
You can then insert the user account directly into the database...

**Comment by Salokyn** [comment]
> Otherwise you create an empty database - and then the first random visitor to your site gets the ability to create an admin account...

Good point !

> It uses a variable $BASE_URL
> Where does this come from?

It is provided to docker when running the container so it create environment variables.

> If you prompt the user for it, can you also prompt the user for the admin username/password?
You can then insert the user account directly into the database...

Absolutely. Though I did not find yet a way to do it  by calling existing php code through CLI.

**Comment by fisharebest** [comment]
> It is provided to docker when running the container so it create environment variables.

So I guess you can use the same technique to provide the desired admin account details.

> Though I did not find yet a way to do it by calling existing php code through CLI.

Create a MySQL dump from a clean install.  It will contain all the tables and an admin user with `user_id` = `1`.

Your setup script should
* create `data/config.ini.php`
* import `mysql-dump.sql`
* obtain the required credentials (username/email/password) and create a suitable password hash.
* update the database

Here are the relevant lines from an installation script that I used once.

```
WTCRYPT=$(php -r "echo crypt('$WTPASSWORD', '');")

cat mysqldump.sql | mysql --database=$DBNAME

echo "UPDATE wt_user SET user_name='$USERNAME', email='$EMAIL', real_name='$REALNAME', password='$WTCRYPT' WHERE user_id=1" | mysql --database=$DBNAME
```

**Comment by Salokyn** [comment]
Thank you, I updated my scripts that way.
