### ISSUE TITLE
Github - thoughts about map icons

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2803]
Just a thought, do we really need an icon library? Couldn't we create our own? see [Leaflet custom icons](https://leafletjs.com/examples/custom-icons/). Now I'm no graphic artist but it should be easy to create a set of plain coloured icons and the only place where we really use icons with the little pictures embedded is on the individual places tab (It'll definitely take longer for me to create those!).

If I started looking at this, what would be the best way of organising things, i.e
- a separate view for icons or put the appropriate code in the using view
- where would be the best place for the images

**Comment by fisharebest** [comment]
We have the"fact icons" that are shown on the xenea theme.  Would these be a good place to start?

**Comment by fisharebest** [comment]
Just noticed the timestamp of this issue - before I posted the "fix" for beautifymarkers/FA5.

Not sure if the issue assumed we didn't have a fix...

The [custom icons link](https://leafletjs.com/examples/custom-icons/) suggests that icons need to be URLs of images (rather than CSS or anything else).

If you want to work on this, I would create these icons in something like `/resources/img/places-tab-icons/` and add a route/function to the module `getFactIconAction` which just returns the icon.
