### ISSUE TITLE
Search results are not related to the query

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#2809]
While searching for an individual name, results are always far away of my keywords or query.

**Comment by fisharebest** [comment]
> While searching for an individual name

The "General search" will find records that contain the text anywhere, in any field.

Are you 100% certain that the search text does exist in the search result.

Can you give an example?

**Comment by mrqd9** [comment]
Attaching screenshot of my search
My query was for "Hussain" there are 5+ individual with name Hussain in the family tree. 
But here is the result
![Screenshot_20191202-210624_Chrome](https://user-images.githubusercontent.com/56225476/69972859-70a65900-1548-11ea-9aef-010fd89ea178.jpg)
![Screenshot_20191202-210732_Chrome](https://user-images.githubusercontent.com/56225476/69972878-77cd6700-1548-11ea-987a-c0a47b515f87.jpg)

**Comment by fisharebest** [comment]
Visit one of these individuals.

Look at the GEDCOM data. (Edit, Edit raw GEDCOM).

Does "Hussain" exist in this text?

**Comment by fisharebest** [comment]
Is your name Hussain?

Were you the last person to edit these records?

Do they show

```
1 CHAN
2 _WT_USER Hussain
```

**Comment by mrqd9** [comment]
> 1 CHAN
> 2 _WT_USER Hussain

Correct..

**Comment by fisharebest** [comment]
I guess the code is working exactly as designed - although in your case, it isn't helpful.

**Comment by t-karcher** [comment]
I have the same issue: My last name is part of my username, so searching it will bring up all elements with myself being the last editor. Which is especially confusing for others since I decided to hide (via privacy settings) the latest change info from normal users.

I don't see a simple fix, but maybe you could implement one of these enhancement ideas in one of the next releases?
1) Add an option to exclude tags like _WT_USER from the default search
2) If the user account is linked to an individual in the current tree, save the XREF instead of the user name ("2 _WT_USER @ X123 @" instead of "2 _WT_USER username")
