### ISSUE TITLE
github - marriage shown as partner before login

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2811]
Not sure this is an issue or not.
Before logging in the wife is shown as a partner and after logging in the wife is shown as wife.

![image](https://user-images.githubusercontent.com/5147603/69965774-38643380-14d2-11ea-8fed-a40f385843e7.png)

![image](https://user-images.githubusercontent.com/5147603/69965702-0e127600-14d2-11ea-9e76-8d797c0ca8c0.png)

**Comment by fisharebest** [comment]
Until we log in, we can't see the (private) family record, so we can't know that a `MARR` event exists.

So, I guess this is working as expected...

Now we have two functions that bypass privacy;

* show private names
* show private relationships

We could bypass the privacy logic here as well, to expose the MARR/DIV records so that we can choose between "partner", "husband", "ex-wife", etc.

I'm not totally convinced that we should.

Your thoughts?

**Comment by makitso** [comment]
If it were up to me I would bypass the privacy for this as well.
