### ISSUE TITLE
Control panel renders poorly in Safari

### ISSUE THREAD

**Issue by triantos** [fisharebest/webtrees#2813]
I'm running 2.0.0beta5. On Safari 13.0.3 on Mac, the control panel UI is basically unusable. When I looked at the elements in Safari's inspector, I see that the computed height is coming in very small compared to what it gets computed to on Firefox. Specifically, it's the height of the div of class "card mb-4". For one of my sections ("Family Trees") Safari calculated that div to have a height of 53px and on Firefox I see 273px. I'm happy to provide screenshots, etc. if needed.

**Comment by fisharebest** [comment]
Same as https://github.com/fisharebest/webtrees/issues/2291 - which was reported on Chrome 72 and 73

It was fixed by replacing bootstrap's `display: flex` with `display: block`.

A later change to route-naming has unintentionally broken that workaround.

However, the current versions of Chrome don't suffer from the problem, and the lack of workaround has gone unnoticed.

**Comment by triantos** [comment]
I'm officially impressed with your response time. :-)
