### ISSUE TITLE
Better documentation for 1.7 to 2.0 migration?

### ISSUE THREAD

**Issue by mpaluchowski** [fisharebest/webtrees#2837]
I went through a migration from 1.7 to 2.0.0 final today and it went anything but smoothly. I wish the documentation would be improved. Right now it's fragmented. There should be an explicit section somewhere, listing step-by-step what to do to go from 1.7 to 2.0, since this is a pretty serious change.

The `README.md` has an Upgrading section, but it speaks of an automated process (which isn't available for this migration), and the manual one is generic. It asks to copy over the files from the new version, but doesn't mention the vast differences in file structure between the two versions. Will the 1.7 files be removed? Or do I need to do it manually? Which files do I keep?

There's an automated database migration when you run 2.0 on a 1.7 database, but that's not mentioned anywhere. It should probably be a step that requires confirmation before it starts, especially since it's irreversible. (I had my migration explode on some database model issue -- one field was too short and causing trim errors -- and after a few tries of database restore & migrate, fell back to a fresh install and manually migrating some of the data).

Finally, there are [upgrade notes](https://webtrees.github.io/upgrade), but they're hardly actionable. What exactly should I do about each one of them? Should I do them before or after 2.0 is installed and running?

I could help out with the writing, but I don't enough about the process to put together the content :disappointed:

**Comment by fisharebest** [comment]
In theory, upgrading is a simple matter of copying the new files to the server.

Since we cannot assume we have write access to the filesystem, webtrees cannot rely on old files being deleted.  While it is generally good practice to delete old files, it is certainly not essential.

Visiting the site while the upgrade is in progress will almost certainly give a fatal (scary but harmless) error.  But this affects visitors, not the site owner.  So using the `offline.txt` file is a friendly thing to do, but again not essential.

> and it went anything but smoothly

I'm curious to know what problems you (and others) had during the upgrade.

Perhaps it was something that I could fix with a code change..

I agree the fragmented documentation sucks.

The wiki site is dying slowly.  It uses a multi-lingual setup that doesn't seem to be supported anymore, so I can't upgrade it.  The Joomla project site is also outdated, but we cannot upgrade because it uses a custom theme.

I'd like to move all non-forum pages to a static site at github (currently https://webtrees.github.io) and point www.webtrees.net to it.  But I can't do this until the site has some styling/design - and my design skills are pretty much zero.

> it speaks of an automated process (which isn't available for this migration)

This is deliberate.  This is a major upgrade, and people may have problems that I had not considered.  It was therefore mentioned on the fourm in a way that would attract experienced users.

I'm hoping that this initial group of users would report any issues so that I can refine the upgrade process and documentation.

**Comment by fisharebest** [comment]
> I could help out with the writing, but I don't enough about the process to put together the content

If you'd like to propose changes/addtions/etc. to the text, please do so on the site's issue tracker:

https://github.com/webtrees/webtrees.github.io/issues
