### ISSUE TITLE
Can't push a commit to github

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#2861]
Just tried to push a commit and am getting the following error message 

> refusing to allow an OAuth App to create or update workflow `.github/workflows/phpcs.yaml` without `workflow` scope

I notice you made a change to workflows a week or so ago. Is this the culprit and what can I do?

**Comment by fisharebest** [comment]
I *think* the error means that since my repository has enabled actions, then your fork also needs to enable them.

FYI, there are three actions
* code style check
* static analysis
* unit tests

https://github.community/t5/GitHub-Actions/Refusing-to-allow-an-integration-to-create-or-update/td-p/32472

**Comment by ddrury** [comment]
Hm,
Must be a windows thing. I just tried pushing from the Ubuntu shell on windows and it worked, however I'm now getting a raft of emails telling me all the unit tests are failing!

**Comment by ddrury** [comment]
I think it must have been something to do with cached credentials because this morning I could push from my windows client. Hey ho
