### ISSUE TITLE
Private user name from my pre 2.0.0 wt live system found in search engine  

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2904]
One of my users complained that when he searches his name in Google, he sees the link to his father’s record on my site. He updated his father’s data on September 1, 2019, and he sees his user name in the extra information.

My site is not supposed to show data of people who are alive to site visitors or to distant relatives. We should neither show to visitors or distant relatives user data of users who are alive.

I assume that the same happens in 2.0.1.

**Comment by fisharebest** [comment]
If I understand correctly, one of your users is using their real-name as their user-name.

The "last change" event shows the username of the person who edited it.

So you have something like this:

```
1 CHAN
2 DATE 22 DEC 2019
2 _WT_USER Greg Roach
```

instead of something like this:

```
1 CHAN
2 DATE 22 DEC 2019
2 _WT_USER fisharebest
```

I presume the username (i.e. the real name) is sufficiently unique that it can be found using google.

If this is correct (please confirm), then I guess we should hide the _WT_USER attribute for visitors.

**Comment by fisharebest** [comment]
Correction.

I should have checked the code first.

It shows the real name, not the username.

Perhaps we could show just the username for visitors, and the real-name for logged-in users.

**Comment by xmlf** [comment]
I think you can see the real name in the search results, which is currently better.Tell the visitor that the site has this person, but you cannot view the details. Only registered and passed seriously.

**Comment by melizaa** [comment]
I do not think that we should show the user name to my site visitors and to distant relatives in the same way that we do not show the names and data to visitors and distant relatives.

**Comment by melizaa** [comment]
I have users who use their name as their user name, so showing the username is not the solution.

**Comment by melizaa** [comment]
I have added the changes to my pre 2.0.0 production system. Thanks!
