### ISSUE TITLE
2.0.1 upgrade process deletion step displays "This form has expired"

### ISSUE THREAD

**Issue by mpaluchowski** [fisharebest/webtrees#2914]
I just ran the upgrade from 2.0.0 to 2.0.1 via the automated process. It seems to have gone well, but at the step named "Delete old files..." the updater rendered the regular page with the login form and a message saying "This form has expired. Try again.", as visible below. I was also logged out of the website.

![Screenshot from 2019-12-27 07-16-03](https://user-images.githubusercontent.com/727642/71504197-c8e72700-2878-11ea-8bc1-2fe0d7dd289f.png)

**Comment by fisharebest** [comment]
It is safe to ignore this.

In order to fix #2844, I needed to change the cookie name.
This will log you out as soon as you start using the new code.

**However, the upgrader runs using code from your old version.**

The upgrader in 2.0.0 attempts to run a final "cleanup" step after the installation is complete.

This can't now happen - as we'll be logged out before it runs.

There is no way to properly fix this without a time machine :-(

It's a one-off thing.  It affects approx 100 people who are using the 2.0.0 release.

**Comment by mpaluchowski** [comment]
Is there any manual cleanup I should do instead?

**Comment by fisharebest** [comment]
> Is there any manual cleanup I should do instead?

No.  The cleanup is now merged into the previous step (copy files).
