### ISSUE TITLE
V2: Some mediaobjects shown as fact

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#2930]
I am currently testing V2. I noticed that some of the media objects are shown as a seperate fact. See attached screenshot or my [testsite](https://www.bfle.nl/testboom/index.php?route=%2Ftestboom%2Ftree%2Ftree1%2Findividual%2FI44%2FJacobus%2520Weber).

Any idea what is causing this behaviour? Is it a bug?

![Screenshot_2019-12-31 Jacobus Weber 1760–1831 – Stamboom Weber Morel](https://user-images.githubusercontent.com/25879600/71618415-c0b42200-2bbf-11ea-8885-0219dadf9c6a.png)

**Comment by fisharebest** [comment]
The tabs and sidebars can declare that they handle specific GEDCOM facts.

For example, the "Sources tab" handles the `SOUR` fact, and the "Extra information sidebar" handles the `CHAN` fact.

The "Facts and evenst" tab displays all the facts that are not handled by other tabs/sidebars.

The "Album tab" does not declare that it handles the `OBJE` facts.

This is because it does not (yet) provide all the functions that you would need.  For example, it does not allow you to delete links to media objects.

When this feature (and others???) is added, it can take responsibility for the `OBJE` facts.

**Comment by SnarfW** [comment]
Thank you for your explanation. Indeed in the family record there is an extra `1 OBJE` to this image.

I just checked the demo server: [https://dev.webtrees.net/demo-dev/tree/demo/individual/i35/Elizabeth%20Angela%20Marguerite%20Bowes-Lyon](https://dev.webtrees.net/demo-dev/tree/demo/individual/i35/Elizabeth%20Angela%20Marguerite%20Bowes-Lyon). In this record there is also a `1 OBJE @m23@`. Why is this media object not listed in the "Facts and events" tab?

**Comment by fisharebest** [comment]
> Why is this media object not listed in the "Facts and events" tab?

Because this site uses the "Media" tab.

The media tab "claims responsibility" for `1 OBJE`

The album tab does not.

(The album tab requires more work).

**Comment by SnarfW** [comment]
OK, now I understand. I will enabeling the "Media" tab...

Not sure, should I close this issue? It seems that still some work has to be done on the Album tab

**Comment by fisharebest** [comment]
> Not sure, should I close this issue?

Leave it open.
