### ISSUE TITLE
V2: Highlighted image

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#2931]
The current release V2.01 has the option to mark a media object as 'hightlighted image: never' `1 _PRIM N`. Currently this has no effect, image is still shown.

**Comment by fisharebest** [comment]
This is a deliberate change.

`_PRIM` is a custom tag.  It is interpreted differently by different applications.  It is also invalid GEDCOM because tags can only indicate positive things (`1 _PRIM Y`), not negative things (`1 _PRIM N`).

webtrees 2.0 removes the dependency on some custom tags.

The "profile image" for an individual is now chosen as the *first* image linked to the individual.

On the indivdiual page, there is a "re-order media" option.


Also, perhaps this is not a photo of the individual.  Perhaps it is an image from an event (e.g. gravestone).

In this case, the image should be linked to the event - not to the individual.  There is a tool in the control panel to help update these links.

**Comment by SnarfW** [comment]
Personally, I feel that you are maybe a bit to strict on the custom GEDCOM tags... No program/site will function without any custom tags.
I have a tree with over 4000 media objects, most of them are linked to a fact but certainly not all of them. So upgrade to V2 would require a lot of work for me.

But anyway: in the current release you can set a value for the highlighted image, so I was expecting it to work. So either this option should be completely removed, or the site should follow this setting. 

![Screenshot_2019-12-31 Princess Elizabeth aged 3, 1929 – webtrees](https://user-images.githubusercontent.com/25879600/71624451-f585a080-2be2-11ea-91d6-d0064b6885dc.png)

**Comment by fisharebest** [comment]
Work is underway on a module to convert custom `1 _PRIM Y` tags.
