### ISSUE TITLE
Notes shown as fact

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#2940]
In V1.7 I have added notes to the records of persons. Since I do not want to share these note with visitors I have set the access level of the Tab Notes to 'show to members'. 
When I have the same settings in V2, visitors will, however, see the notes as facts in the facts and events tab, so they are not hidden. Is this a bug, similar to the album tab as discussed in issue 2930 ?

**Comment by fisharebest** [comment]
> I have set the access level of the Tab Notes to 'show to members'.

You are hiding the "tab", not the facts.

You should also add a privacy restriction for `NOTE` records.

**Comment by SnarfW** [comment]
But setting privacvy restrictions for 1 NOTE records is not required in V1.7! Notes that are only shown in the tab notes do not suddenly appear in the fact and events tab when you log out and have  visitors rights.
So again a difference in behaviour between both versions. I understand that you want to make an automatic upgrade from v1.7 to 2 available. I feel that due to the numerous differences in behaviour between both versions you should not do this...   

Furthermore in both versions it is only possible to set privacy restrictions by modifting the raw gedcom, Webtrees has no other way to set this.

**Comment by fisharebest** [comment]
>  I feel that due to the numerous differences in behaviour between both versions you should not do this...

I've added this to the upgrade documentation.

I don't plan to automatically upgrade from 1.7 to 2.0 until I have finished a "pre-upgrade check" for 1.7.  It will check for things like this, and provide a link to the documentation.

> Furthermore in both versions it is only possible to set privacy restrictions by modifting the raw gedcom, Webtrees has no other way to set this.

What do you mean?

You can add privacy restrictions the same as other facts and events...

**Comment by SnarfW** [comment]
Is it a deliberate choose to have a different behaviour between both versions? Since it will be impossible to manually check all media, note records I will most probable not upgrade. I hoped that v2 would be backward compatible with v1.7.

Just to be sure you understand my comment. A record like:
```
0 @I1@ 
1 NAME Given /SurnameTest/
2 GIVN Given
2 SURN SurnameTest
1 BIRT Y
1 DEAT Y
1 NOTE bla bla
1 SOUR @S1@
2 DATA
3 TEXT some text
1 OBJE @M1@
```

Gives the following view in v1.7 when only the Facts and Events tab is shown for visitors:

![afbeelding](https://user-images.githubusercontent.com/25879600/71746245-afdc0880-2e6c-11ea-802f-9f2c71614279.png)

In v2 visitors see this:

![afbeelding](https://user-images.githubusercontent.com/25879600/71747059-f92d5780-2e6e-11ea-97e5-867f1c053113.png)

The source remains hidden, but the media object and note are suddenly shown as fact. When I sign in both are not shown in the facts and events, but are only shown on the tabs media and notes:

![afbeelding](https://user-images.githubusercontent.com/25879600/71747212-5b865800-2e6f-11ea-88de-69cfafa20eec.png)

**Comment by SnarfW** [comment]
> What do you mean? You can add privacy restrictions the same as other facts and events...

See screenshot, a field to set a privacy restriction is not available when you edit a note:

![afbeelding](https://user-images.githubusercontent.com/25879600/71747329-af913c80-2e6f-11ea-9d30-9b97c2eb9512.png)

**Comment by vytux-com** [comment]
You can add a restriction to ALL notes by editing privacy in tree settings and then add this.

![Screenshot_20200104-081420](https://user-images.githubusercontent.com/5370583/71749747-6ae6bf00-2eca-11ea-8f21-6be04c23225f.png)
Sorry but I could only do this on mobile currently so the screenshot is not the best.

**Comment by fisharebest** [comment]
> See screenshot, a field to set a privacy restriction is not available when you edit a note:

Ah.  You are trying to create

1 NOTE foo bar
2 RESN privacy

This isn't valid GEDCOM.

You can use the privacy settings.  You want to select "Note" in the second column.

(The first column would be to add a rule for a specific shared note record).

**Comment by SnarfW** [comment]
> This isn't valid GEDCOM

OK I understand this part. 
However, I do not understand is that the behaviour in V2 is (by design?) different from V1.7. Upgrading would be so much easier when both versions behave the same.

**Comment by fisharebest** [comment]
Yes - the change was intentional.

It was done to make existing behaviour more consistent.  For example, we already do this with things like the "Extra information" sidebar.  Disable the sidebar, and the information that it shows gets moved to the facts/events tab.

It was also done to enable other tabs to take over the display of certain facts.  For example, you could have a "Census" tab which shows all the census events, and perhaps has extra functionality to show missing censuses.

> Upgrading would be so much easier when both versions behave the same.

There are many differences between 1.7 and 2.0.  https://webtrees.github.io/upgrade/

If there were no differences, the release would have been 1.8 rather than 2.0.

**Comment by SnarfW** [comment]
> Yes - the change was intentional.

I still cannot understand the logic behind this. In the control panal you use the term "access level" to show or hide a tab. By using this term "access level" you expect to give or deny acces to the tab and all content. Exactly the same phrase "access level" is used to set the privacy restricitons!
In the current situation, I cannot think of a reason why you want to show or hide a tab for visitors when the info of the tab is always shown. Currently it would be more logic to only have the possibility to show or hide a tab irrespective of the type of visitor/user.

> the release would have been 1.8 rather than 2.0.

For me it feels like using a different program, instead of a new version. 
I have been using Webtrees for at least the last 5 years. By using the possibilities (like setting privacy restrictions on tabs, or using _PRIMARY Y tag for photo's) of the previous versions I now have a GEDCOM/database which is very hard to upgrade to version 2 and probable would require me to check almost every page and media-object...   I find this a bit disappointing, it feels like being punished for using the available functions of the previous versions.

**Comment by fisharebest** [comment]
> you use the term "access level" 

It is just being applied more literally and more consistently.

We already have two different tabs that show media links (album and media). If we set the media tab to be "member only", and the album tab to be "vistors", then which of these access levels should apply to media links.  If the tab visibility also affected the data visibility, then media links would be both hidden and shown at the same time.

Also, notes on events  (as opposed to notes on individuals) were always shown on the facts tab as well as the notes tab.  Hiding the notes tab never hid these notes.

And as I said before, you can achieve the behaiour you want by changing one setting in the control panel.

> Currently it would be more logic to only have the possibility to show or hide a tab irrespective of the type of visitor/user.

For some tabs, it may make sense to have different access levels.  For others (such as this one), less so.  But one of the goals for 2.0 was to make everything as modular as possible, which means that all modules get the same interface (i.e. config options). 

It allows you to create tabs that pull out certain types of fact.  I mentioned censuses earlier, but you might also want a tab that pulls out all the LDS events.  If there's a special tab for a type of data, it is shown there.  Otherwise it goes with everything else.

> (like setting privacy restrictions on tabs, or using _PRIMARY Y tag for photo's)

An import tool is currently being written to convert `1 _PRIM Y` tags into sorted links.  See #2942

**Comment by fisharebest** [comment]
The [1.7-2.0 upgrade documentation](http://localhost:4000/upgrade/2.0/) has been updated to make these changes clear.
