### ISSUE TITLE
2.0 All records have an ID begining with X

### ISSUE THREAD

**Issue by Salokyn** [fisharebest/webtrees#2951]
Usasually, in GEDCOM files, families get an ID of the form `Fnn`, individials get an ID of the for `Inn`, sources `Snn`, repos `Rnn` and so on.
Since I use Webtrees 2.0, all records IDs have the form `Xnn`.

Is that wanted ?

As far as I remember this letter could be changed in WT1.7 config panel, but I can't find the same on WT2.0.

**Comment by fisharebest** [comment]
> Is that wanted ?

Yes.  This change was intentional.

I causes lots of confusion with 1
O causes lots of confusion with 0
S causes lots of confusion with 5

Also, it is permitted to create family records that begin with I and individual records that begin with F.  This can also create confusion.

The IDs are not important.
