### ISSUE TITLE
The entries in the yearly calendar, are not sorted. 2.0.2 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#2967]
![image](https://user-images.githubusercontent.com/5202996/72246485-7b4e1680-35fb-11ea-8c06-616c82cb6993.png)

In pre 2.0 they were sorted by the date.

**Comment by fisharebest** [comment]
The facts are initially sorted by anniversary date.

But they are then grouped by individual, so that if an individual has two events in the same year, then they are shown together.

This is typically for death/burial and birth/baptism.
It would also include someone who was born/died in the same year.

(Although in your example, you have two events with the same date.)

But if we sort by date, we won't be able to group.
