### ISSUE TITLE
I get warning in "Import custom thumbnails from webtrees version 1" - 2.0.2

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3016]
I see in the test systems
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by fisharebest** [comment]
Can you post the error message.

See here for instructions on how to find it.

https://webtrees.github.io/faq/xhr/

**Comment by melizaa** [comment]
I have over 8,000 media files in my test test system.
I changed now the number of records to display to 500.
For page 2 I see the warning text and Status 504.
![image](https://user-images.githubusercontent.com/5202996/73126049-88cdae00-3fb6-11ea-847e-65b997ea0697.png)

I do not see an error message.

**Comment by fisharebest** [comment]
> I changed now the number of records to display to 500.

Choose a smaller number.

The screenshot shows that the request timed out after one minute.

The calculation of the comparison% requires a **lot** of image processing.
We must take two images, create "fingerprints" of each, and then compare the fingerprints.
For large images, this can take several seconds.

NOTE: we store these fingerprints in a cache.  But a bug (now fixed) in 2.0.1 means that the cache is cleared frequently.

The only way to fix this issue is to remove the option to change the number of records to show.
