### ISSUE TITLE
V2 Feature request

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3032]
In version 1.7, blocks that potentially contained a lot of data, eg _On this day_, _Upcoming events_ had an option to set a scrollbar to limit the size of the block. Version 2 no longer has this option and I'd like to see it re-instated

**Comment by fisharebest** [comment]
This was removed intentionally.  See #773 and #1320 

The scrollable area needs to be somewhat smaller than the screen height.
Otherwise users with small screens (e.g. mobile) won't be able to scroll past it.
i.e. if all they can see is the scrollable area, they can't send scroll events to the surrounding page.

A suggestion to limit the number of items shown was made in #2954

I'm currently thinking that records over a threshold (10? 15?) would be initially hidden, and then revealed with a link/button.
