### ISSUE TITLE
Census assitant - adding rows, not saving rows

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3058]
1. When adding a new row, everything i entred disapear - only the date which came from an individual remain.

2. After savig, only rows with individuals from my webtree are saved, other rows disapear.

3. Clicking on the "head" icon deletes every row, but the selected individual

Screenshots on
https://www.webtrees.net/index.php/en/forum/help-for-2-0/34060-census-assistent

**Comment by Salokyn** [comment]
:+1:

**Comment by ro-la** [comment]
It seems the update has solved only the point 2 of this bug. 1 and 3 remains.

A new bug - when the first column is blank, then the second become the first. Perhaps the lines should start with a "|", when it starts with "blank|xx|" xx is displayed in the first, not in the second column.

Ladislav

**Comment by fisharebest** [comment]
> It seems the update has solved only the point 2 of this bug. 1 and 3 remains.

Issues can be open or closed.  They cannot be 1/3 closed and 2/3 open.

When a fix is submitted, the issue is closed automatically.

It is best to create a separate issue for each problem.

> 3 remains.

This is working as designed.  If you change the "head of household", the relationship column will be wrong for all the other rows.

You should select the head first.

> A new bug

Please create a new issue.  There is no charge - you can create as many as you need ;-)

**Comment by ro-la** [comment]
OK. I created some new issues :-)

Regardind Census of Slovakia 1869 - have you received my email of 2020-02-26 with a corrected php-file?

Thanks 

Ladislav

**Comment by fisharebest** [comment]
> have you received my email of 2020-02-26 with a corrected php-file?

I am in the middle of changing email provider.  Perhaps not.

Create a github issue for it?
