### ISSUE TITLE
Census assitant - adding rows

### ISSUE THREAD

**Issue by ro-la** [fisharebest/webtrees#3104]
When adding a new row (empty or not), everything i entered disapear - only data which came from an individual already stored in webtrees remain.

This was reported also in the closed issue: https://github.com/fisharebest/webtrees/issues/3058

Ladislav

**Comment by fisharebest** [comment]
The fix for #3058 works for me.

Here are screenshots from the demo site.  Two individuals (from the tree) and one individual (not from the tree).

<img width="909" alt="Screenshot 2020-03-07 at 13 39 59" src="https://user-images.githubusercontent.com/2306088/76144522-55804380-6079-11ea-84f5-f503f80125f4.png">

<img width="782" alt="Screenshot 2020-03-07 at 13 40 12" src="https://user-images.githubusercontent.com/2306088/76144524-57e29d80-6079-11ea-8e07-17747e394f27.png">

Can you give more details of your problem?

**Comment by ro-la** [comment]
I am adding the first row - King Edward VII. Then I write into occupation the word "king". 
Now, when I add Queen Victoria, the word "king" disapears.

The only possibility how to craete a complete transcription is to add all persons from the family tree, for every person which is not in the family tree an empty row and only after this you cann add data from the census. 

Ladislav
