### ISSUE TITLE
Upgrade wizard final step: PCLZIP_ERR_BAD_FORMAT

### ISSUE THREAD

**Issue by laryn** [fisharebest/webtrees#3112]
> Unzip webtrees-1.7.16.zip to a temporary folder…
> An error occurred when unzipping the file.
> PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

I'm trying to use the upgrade wizard to upgrade to 1.7.16 until I get a chance to look over the instructions for manually upgrading to 2.0 -- but the final step fails with this notification. 

![Screen Shot 2020-03-09 at 9 14 56 AM](https://user-images.githubusercontent.com/871421/76221149-9b0e4f00-61e6-11ea-8cb8-8273e7a7f673.jpg)

**Comment by fisharebest** [comment]
It would appear that the .ZIP file is incomplete/corrupt.

The "directory" of a .ZIP file is stored at the end, and an incomplete file would give the error message you see.

You should be able to find the downloaded .ZIP file in your `/data/` folder.

It should be 33253485 bytes long.

Maybe your server has difficulty connecting to the download server?
Maybe there are network problems?
Maybe your disk is full?
Maybe something else?

If you have tried several times and get the same error, then you should try the manual upgrade.

https://webtrees.github.io/upgrade/automatic/
https://webtrees.github.io/upgrade/manual/

**Comment by laryn** [comment]
Ah, I found the `.zip` file in the `/data/` folder -- it is actually a `302 found` response that includes HTML to redirect to an AWS URL, but instead the response itself is being saved as though it were the zip file.

Sounds potentially similar to [an issue I saw on another project](https://github.com/backdrop/backdrop-issues/issues/3488).

**Comment by fisharebest** [comment]
What version of webtrees were you upgrading *from*?

**Comment by laryn** [comment]
I was on `1.7.14`. (The upgrade to `2.0.2` seems to have gone very smoothly).

**Comment by fisharebest** [comment]
Do you have the file (containing the 302 response)?

The code does check for redirects - perhaps this is sometimes being sent in an unexpected format?

**Comment by laryn** [comment]
Here's the file. I've added the `.txt` extension (this file was called `webtrees-1.7.16.zip` on the server).
[webtrees-1.7.16.zip.txt](https://github.com/fisharebest/webtrees/files/4309140/webtrees-1.7.16.zip.txt)

**Comment by fisharebest** [comment]
This file starts with `/1.1 302 Found`...

This is not a valid HTTP response.  The code is looking for `HTTP/1.1 302 Found`

**Comment by laryn** [comment]
Strange! Unfortunately I have nothing of value to contribute to the discussion. 😕

**Comment by fisharebest** [comment]
webtrees 1.7 uses our own code to fetch external files.

webtrees 2.0 uses a third-party library `guzzle` to do this.
It is hopefully better at handling errors like this.

It is a major change, and we cannot back-port it to 1.7 because the library won't run on the old versions of PHP.

So, since we already issued an update with a fix, I think we can close this one.

If anyone else has the same problem, they will hopefully find this issue, and know to do a manual upgrade.

**Comment by joximu** [comment]
I had the same today and digged into it.

The actual downloaded file began with HTTP/1 - but the first 4 Bytes were cut by the download-routine...

```
HTTP/1.1 302 Found
date: Fri, 28 Feb 2020 08:18:21 GMT
content-type: text/html; charset=utf-8
server: GitHub.com
status: 302 Found
vary: X-PJAX, Accept-Encoding, Accept, X-Requested-With
location: https://github-production-release-asset-2e65be.s3.amazonaws.com/11836349.....
```

The problem lies in "location:" instead of "Location:"... the latter is grepped

```
            if (preg_match('/^HTTP\/1.[01] 30[123].+\nLocation: ([^\r\n]+)/s', $response, $match)) {
                fclose($fp);

```

but with the small L the redirect is not recognized....

I hope someone reads this and can reopen the issue...

/Joxi

**Comment by fisharebest** [comment]
Thanks for this!

I have updated the code to match `L` and `l`.
