### ISSUE TITLE
2.03 relationship between two persons runs in endless loop

### ISSUE THREAD

**Issue by ramu98** [fisharebest/webtrees#3165]
**Find the closest relationships check**

all indivisual person search OK.

**Find all possible relationships check**

### **Ver.1.7 no error**

My homepage deals with the mix of historical figures and businessmen. So the importance of this option is very high. If anyone knows how to solve the problem, please respond. Thank you.

**MY Server Info**
CPU : PHENOM II X4 945 (AM3 3.0GHz HTT 2000MHz L2 512KBx4 L3 6MB 125W/95W)
RAM : 8GB

DATABASE SERVER
MariaDB
10.3.22-MariaDB-0+deb10u1 - Debian 10

nginx/1.14.2
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
PHP extension: mysqli curl  mbstring 
PHP version: 7.3.14-1 ~ deb10u1

**Comment by t-karcher** [comment]
This seems to be the same issue as the one reported in #2849

**Comment by ramu98** [comment]
Before I wrote the above, I read # 2849.
# 2849 The content did not help, so I asked for help again.
I wonder if there is a way to change MariaDB settings. However, I am familiar with Linux's basic settings and basic commands, and I have enough server management knowledge to be able to view and set the manual when adding a new app. So I need help.

**Comment by Gunnar-GO** [comment]
how long the 1.7 needed to show the results?

the #2849 mainly quoted, that the runtime is longer than php runtime on server (most scripts throw away after 30-60 sec). i don't see there anything that refers to sql.

The possible problem is the complexity: the more entries the more possible connections. maybe it needs an further optimisation, its a variant of the travelling salesman problem with tousands of entries. May you look inside Dijkstra's algorithm for ideas.

**Comment by ramu98** [comment]
In version 1.7, the result was within 20 seconds.
Currently, the database of people is about 5,700, and almost all of the characters can be seen in charts from a close relationship to 27 stages.
In the 2.03 version, the All option outputs the results only in close relations.
Complex relationships are infinite loops. To see if this is a timeout error,
I tried setting the time limit to 1200 seconds (20 minutes) in the php.ini file,
The server was only overloaded, with no results.
It seems that programmers will know what is causing this problem.
Thanks for the feedback.

**Comment by fisharebest** [comment]
It is confusing to open the same issue twice, so I have closed #2849

> I wonder if there is a way to change MariaDB settings.

The search uses one simple database query (to find all the FAMS/FAMC links).
The database performance is not relevant here.

Finding the "shortest path" is a mathematically simple task.
With a large tree, we can do this in a few seconds.

But finding "all possible paths" is a mathematically difficult task.

Essentially, we are searching for paths in an "undirected, unweighted, cyclic graph".

* **undirected** means that all links work in two directions.  e.g. parent-child and child-parent.

* **unweighted** means that we treat all links equally.  In an earlier version, we experimented with applying weights, so that blood relationships were given preference to marriage relationships.
Thus if you married your cousin, it would find the cousin relationship before the marriage relationship.  This wasn't popular, so was abandonded.

* **cyclic** means that there are loops.  Loops typically happen when you marry a cousin. Many trees do not have loops.  For these, there is only ever one path between any two individuals.  From what you say, your tree has very many loops.

* **graph** means links between objects.  For us, this is parent/child/spouse/sibling links between individuals

These characteristics are important, because they tell us which algorithms we can use.

(It is probably worth adding that the logic to convert a relationship path into a "human name" for the relationship does not scale well, although it probably runs in polynomial time.  With lots of long paths, this might be a significant factor, although I haven't done any benchmarking).

We use Dijkstra because it can find the shortest path very quickly.  These are the two most important characteristics for most sites.

We then use it to find the "next" shortest paths.  The algorithm for this is to take each family on the shortest path, exclude it in turn from the tree, and look for the shortest path that does not include it.

If we can calculate the shortest path in 1 second, and it contains 10 steps, then we must run the algorithm again 10 times, for a total of 11 seconds.

Again, this is very achievable for large trees and small servers.  It also satisfies the use-case for most users.  e.g. X and Y are husband-wife, but they are also cousins.

This is one level "recursion".  You can control the recursion limit in the configuration.

For a second level of recursion, we must exclude each family on each new path.  If there are lots of paths, this number can increase rapidly.

Your data has lots of loops, **and** you want to find all possible paths.

Other algorithms exist.  According to wikipedia, the [Floyd-Warshall algorithm](https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm) may be suitable for your particular data - although the articles says that for sparse graphs (ones with few cycles), repeated use of Dijkstra is a better options (which is what we do).

It is also worth noting that algorithms use two difference resources.  Processing and memory.  An algorithm may be faster - but require more memory than is generally available to web processes.

I have been trying to research where this task falls in the [P-NP classification](https://en.wikipedia.org/wiki/NP-hardness).  I found one statement that it is NP-hard, but without any information to support it.

**Comment by ramu98** [comment]
Thank you :)

**Comment by dawansv** [comment]
Changing the recursion to 1 really helped me as mine was running for ever as well. I am laughing because just doing a match between my great-great-great paternal grandfather and I, it found no less than 6 other relationships with only 1 recursion, the reason being that I have a very large family (just my father had 7 siblings) and I now realize that so many of my relatives by marriage are also 4 or 5 gen blood relative. So you might need to add a warning for those that have one of these "just-go-marry-your-third-cousin" type of families that were pretty popular in part of Europe to lower the recursion setting !
