### ISSUE TITLE
Linking to a custom image from a stylesheet

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3184]
I am trying to replace an image in css but I can't get it to work

This is my file structure:
![image](https://user-images.githubusercontent.com/5641963/79630607-1272bf00-8153-11ea-93e5-9c11fffc5410.png)

And this is the code in theme.css:

`.icon-pedigree {
    content: url(images/pedigree.png);
}`

This doesn't work and I can't figure out why. What am I doing wrong???

**Comment by fisharebest** [comment]
Hi Carmen,

This doesn't work because the URLs are relative to the stylesheet - and the URL for the stylesheet is different for pretty/ugly URLs.

Also, files in `/resources` may not be accessible.
Only the files in `/public` and `index.php` are guaranteed to be accessible.

This is why modules have the `assetUrl()` function.  It allows them to serve static files using `index.php`.

There are several solutions.

1) Embed the images in the stylesheet, using "data URLs".
This is the technique used by webtrees, and is recommended.
In the core code, the css and image files from `/resources` are processed to create the css files in `/public`.

2) if this is just for your own site, then use the full/absolute URL for the image

3) Create the stylesheet using a PHP view.  e.g. resources/views/style.css.phtml
You can now embed placeholders for the URLs (using the `assetUrl()` function.
This is less efficient, but would give you more flexibility as you can change images dynamically, etc.

**Comment by JustCarmen** [comment]
Thanks, clear. I think I will go for option 1 but option 3 might be interesting too.
