### ISSUE TITLE
FlashMessages and Session concurrency

### ISSUE THREAD

**Issue by ric2016** [fisharebest/webtrees#3186]
While attempting to set a flash message from a custom module via the FlashMessages class, I observe inconsistent behavior: The message seems to get lost sometimes.

I think this is due to the fact that I have multiple parallel requests (e.g. ajax requests, requests for assets etc.) using the same php session, which is apparently not locked:

In the UseSession middleware, the session is loaded first, then the request is handled, and finally the session is persisted. Because there is no locking (which I do not suggest as a general solution, as it would effectively prevent executing requests in parallel), it is possible that different requests overwrite each other's session state, in particular the flash messages.

(more on session locking e.g. [here](https://ma.ttias.be/php-session-locking-prevent-sessions-blocking-in-requests/).)

Any ideas how to handle this better?

**Comment by fisharebest** [comment]
> Any ideas how to handle this better?

Maybe replace the database session storage with an apcu backend?

**Comment by fisharebest** [comment]
It seems that very few servers have apc/apcu installed.

**Comment by ric2016** [comment]
I'm not sure that the problem would be solved by replacing the session storage - The main problem is that a session is persisted without checking for concurrent modifications. Therefore, regardless of the storage engine, these session updates should preferably be done in a 'safe' manner. We could also persist the flash messages separately. Or just advise against ajax requests updating the flash/messages/ the session in general?

**Comment by fisharebest** [comment]
> I'm not sure that the problem would be solved by replacing the session storage

I was thinking of using APCU for the flash messages, not for the session.

> Or just advise against ajax requests updating the flash/messages/ the session in general?

Much of the core code relies on this.

When we close a session, we update two columns in the database - `session_time` and `session_data`.  We could modify this logic so that we only write `session_data` if it has been changed.

This would reduce (but not eliminate) the problem.  Two requests that both update the session data can still conflict - but requests that do not update it will not.

For performance reasons, perhaps we could only update the session time if more than x seconds have elapsed since the last update?

----------

We store very little data in the session.  Some of it (language, theme) could be moved into cookies.

**Comment by fisharebest** [comment]
Does this latest code improve things for you?

**Comment by ric2016** [comment]
Yes, the flash messages appear consistently now.

It is still possible theoretically to overwrite concurrent changes to session_data though, like this:

Thread 1: read $data from session_data
Thread 2: read $data from session_data (same content as read by Thread 1)
Thread 1: modify $data = $data1 (e.g. add Flash Message A)
Thread 2: modify $data = $data2 (e.g. add Flash Message B)
Thread 1: write $data ($data1) as session_data
Thread 2: write $data ($data2) as session_data, overwriting changes in $data1 (which Thread 2 has never seen)

But this may be negligible in practice.
