### ISSUE TITLE
Export shouldn't overwrite

### ISSUE THREAD

**Issue by Gunnar-GO** [fisharebest/webtrees#3217]
If i export a tree at server, it will be named as %tree%.ged. That would replace older files.

It better should be %TREE%%DATE%%TIME%.ged to avoid, that older backups are overwritten.

Like automaticly backups, while updates, are already doing it.

**Comment by fisharebest** [comment]
A common workflow is to export/import a tree.

This can be done to re-build search indexes, and fix other problems.

So, I would prefer the default option remains "overwrite existing file".

> to avoid, that older backups are overwritten

Export to GEDCOM file is not intended to be a backup.

Your backup files should not be stored on the same server as your live data.

**Comment by fisharebest** [comment]
I agree that users should be able to choose a different name, but I do not think that automatic timestamps are the correct solution.

1) it makes it a little more complicated to export/import
2) if you have a large GEDCOM file (e.g. 100's of MB), then it will become easy to fill the disk.
3) writing files to the server is not a recommended backup procedure.  See [here](https://www.reuters.com/article/us-france-ovh-fire-idUSKBN2B20NU) for a good example.

Instead, I have provided an option so that the user can add a timestamp (if they choose), or use the existing filename as a default.

**Comment by Gunnar-GO** [comment]
To 3. sync to an other device/server/NAS is an easy option, but same names will overwrite existing data.

i understand your workflow and the corresponding preference to overwrite, but _an option for adding a variable_ like %date% would be nice. Updates does it this way.
