### ISSUE TITLE
Import from GEDCOM. Undefined variable: tree

### ISSUE THREAD

**Issue by mariusz86** [fisharebest/webtrees#3231]
After importing from GEDCOM file I got "Undefined variable: tree" error and nothing has been imported.

Application runs on localhost without email configured.

Version 2.0.3

**Comment by fisharebest** [comment]
This has already been fixed in commit https://github.com/fisharebest/webtrees/commit/b8d23754c6d89b8e5c9d4bfe3bee6a91e4a29075

The underlying error is that your GEDCOM file is encoded using an unsupported encoding - probably `ANSEL`.

You can check this by viewing the GEDCOM file in a text editor, and looking for a line `1 CHAR <XXX>` near the beginning.

I have created an online tool to convert ANSEL (and most other encodings) to UTF-8.
https://dev.webtrees.net/ansel/
