### ISSUE TITLE
1.7.17 - Pedigree report view as pdf is blank, as html works fine

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3249]
In webtrees v2.0.3 the Pedigree report view as pdf or html both works fine, but in v1.7.17 only html view works fine: pdf view is empty.

**Comment by ddrury** [comment]
Works for me, so is it only the pedigree report? 
Anything in webtrees error log, browser developer tools, console or network tabs?

**Comment by TheDutchJewel** [comment]
I think it has something to do with the privacy settings:
If I check it on anyone born <100 years ago: pedigree report view as pdf is blank, as html works fine.
If I check it on anyone born >100 years ago: pedigree report view as pdf and as html works fine.

**Comment by ddrury** [comment]
Hm,
Checked with me (last time I checked I was still alive) and someone older than 120 both logged in and out and they all work.

**Comment by TheDutchJewel** [comment]
Where can I find the webtrees error log? I use webtrees local with XAMPP v7.3.17-0.

```
<!-- saved from url=(0316)http://localhost/webtrees/reportengine.php?action=run&report=modules_v3%2Fpedigree_report%2Freport.xml&varnames%5B%5D=pid&vars%5Bpid%5D=I11&type%5Bpid%5D=INDI&varnames%5B%5D=orientation&vars%5Borientation%5D=portrait&type%5Borientation%5D=&varnames%5B%5D=pageSize&vars%5BpageSize%5D=A4&type%5BpageSize%5D=&output=PDF -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div class="line-gutter-backdrop"></div>
<table>
<tbody>
<tr>
<td class="line-number" value="1"></td>
<td class="line-content">
<span class="html-end-of-file"></span>
</td>
</tr>
</tbody>
</table>
</body>
</html>
```

**Comment by fisharebest** [comment]
Due to lack of resources, the webtrees 1.7 branch is only going to receive fixes for security and data-integrity issues.  All development resources are devoted to the 2.0 branch.

The XML reports are scheduled to be replaced by the end of the year.  See #3250 

So, even if it is a bug, it is not going to be fixed.

> Where can I find the webtrees error log?

Control panel -> Website logs

> I think it has something to do with the privacy settings:

I think you will be better off asking about this on the "webtrees 1.7" section of the forum.

You'll be able to find out if this affects anyone else or just your site.

**Comment by TheDutchJewel** [comment]
Here is the webserver log:
```
D:\xampp\htdocs\webtrees\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php:2002 array_map(): Expected parameter 2 to be an array, bool given
#0 unknown:unknown ErrorException("array_map(): Expected parameter 2 to be an array, bool given")
#1 \vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php:2002 array_map([array], false)
#2 \vendor\tecnickcom\tcpdf\tcpdf.php:4056 UTF8StringToArray('W. ?. de Winter', true, [array])
#3 \app\Report\ReportPdfText.php:102 GetStringWidth('W. ?. de Winter')
#4 \app\Report\ReportPdfTextbox.php:168 getWidth([ReportTcpdf])
#5 \app\Report\ReportTcpdf.php:90 render([ReportTcpdf])
#6 \app\Report\ReportPdf.php:132 body()
#7 \app\Report\ReportParserGenerate.php:340 run()
#8 \app\Report\ReportParserGenerate.php:183 docEndHandler()
#9 unknown:unknown endElement([resource], 'Doc')
#10 \app\Report\ReportParserBase.php:45 xml_parse([resource], '"><var var="I18N::translate(\'B…', false)
#11 \app\Report\ReportParserGenerate.php:131 __construct('modules_v3/pedigree_report/rep…')
#12 \reportengine.php:282 __construct('modules_v3/pedigree_report/rep…', [ReportPdf], [array])
```

There seems to be a problem with the processing of the name Wilhelmus ‘Wim’ de Winter:
1 NAME Wilhelmus /de Winter/
2 NICK Wim

**Comment by fisharebest** [comment]
webtrees sets the PHP encoding to `UTF-8`.

It looks like the TCPDF library is setting it to `ASCII`.

This breaks the substring calculations in webtrees.

My guess is a bug in the TCPDF library - which is abandoned.  There is no point tracking the bug down or reporting it.

I note that the section of the report-generator that triggers the bug has been rewritten in 2.0, which is why we don't trigger it there.

This is more luck than judgement!
