### ISSUE TITLE
Warning when adding an already existing media file

### ISSUE THREAD

**Issue by HRN65** [fisharebest/webtrees#3251]
When adding a media file that already exists in the media folder, the file is created with a new unique filename. Would it be possible to have a warning to avoid such doublets, like in 1.7?

**Comment by fisharebest** [comment]
So, if a user uploads a file called `john-smith.jpg`, and there is already a file with that name, what behaviour do you want?

The upload is rejected and the user told to choose another filename?

>  like in 1.7?

I'm afraid I haven't looked at the 1.7 code in a long time, and my own site used a modified version to choose unique filenames - so I have no idea what 1.7 did in this situation.  You'll need to tell me.

**Comment by HRN65** [comment]
In 1.7 there was a simple message "The file already exists"

**Comment by fisharebest** [comment]
Telling the user that "the filename is already used" doesn't help them.

They don't know what filenames are available.
They may not have uploaded the other file.,

We don't want to put barriers in the way of our users when they contribute data.

If two different users want to upload a photo called `mum-and-dad.jpeg`, then we should let them.

The "unique filename" system does that.  The unique filename is a digital fingerprint of the contents.

What I have fixed is an error when you upload another file with the same contents (and hence the same fingerprint and same unique filename).  In this case, we now re-use the existing media file, rather than giving an error.

From the user's perspective, it should now "just work" without any additional effort.

**Comment by HRN65** [comment]
> If two different users want to upload a photo called mum-and-dad.jpeg, then we should let them.
> 
I fylly agree. 
But, working on a small geographic area, I have thousands of images of parish records, listing many individuals/families in same record (image). Until 2.0 I aleways got a warning if a media file already existed when adding new individuals to my tree (And this happened a lot). Now I have to search the media list before adding a new file, to avoid multiple copies of the same file. 
Not only will multiple copies require more resources and storage space, but even worse; the media files will have different XREF's, thus connected to only one individual, when in fact it could be 15.

Would it be possible to have a warning like "Filename already exist. The file will be saved with a new unique filename"
This will allow users to make a choice; save or abort uploading the file.
