### ISSUE TITLE
Disturbed graphics at Control panel/ All modules

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3265]
A bunch of few icons covered the screen

Screen shot from chrome android. 
![20200519_024344](https://user-images.githubusercontent.com/56225476/82260651-4a9c3600-997b-11ea-9932-6063c393f6fc.jpg)

**Comment by ro-la** [comment]
In the "historic" modules there  should be a flag icon (at least I think). Does not work (for me) in Firefox and Chrome. 

The page https://emojipedia.org/flag-austria/ is displyed in firefox correctly, in chrome(based) not.


Screenshot from Firefox - also the icons in the bottom rows are missing.

Ladislav

![image](https://user-images.githubusercontent.com/60657963/82264530-5aa91b00-9965-11ea-80b2-a6a8670c22b0.png)

**Comment by fisharebest** [comment]
On the forum is a report of the "bell" icon having the same problem on one of the home page blocks.

The pattern would seem to be a font-awesome icon inside a `<th>` element, when rendered in Chrome.

**Comment by fisharebest** [comment]
@ro-la - the flag emoji is a different problem.  Perhaps creaate a new issue for it?

**Comment by mrqd9** [comment]
#3264

**Comment by fisharebest** [comment]
3264 is a different problem (wrong record types for recent changes block).

**Comment by mrqd9** [comment]
#3262 earlier reported same issue

**Comment by ddrury** [comment]
Greg,
Don't know how far you've got with this but it seems this is the rule that causes the problem
```
[dir="ltr"] table.dataTable.table-sm > thead > tr > th :not(.sorting_disabled) {
    padding-right: 20px;
}
```

**Comment by fisharebest** [comment]
> Don't know how far you've got with this

So far - nowhere ;-)

That rule looks like it is making space for the sort indicators in sortable columns in datatables.

I'll take a look.  Thanks for the tip.

**Comment by fisharebest** [comment]
It seems to me that this should be `th:not()`, rather than `th :not()`.

It is applying to everything **within** the `<th>`, when I think it should be applying **to** the `<th>`

**Comment by ddrury** [comment]
Is this a newly updated file?

**Comment by fisharebest** [comment]
> Is this a newly updated file?

No - but we recently updated bootstrap from 4.4 to 4.5...

**Comment by ddrury** [comment]
For that definition I can't see an interaction with bootstrap though

On 19 May 2020, at 21:49, Greg Roach <notifications@github.com> wrote:

Is this a newly updated file?

No - but we recently updated bootstrap from 4.4 to 4.5...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/fisharebest/webtrees/issues/3265#issuecomment-631074435">https://github.com/fisharebest/webtrees/issues/3265#issuecomment-631074435</a>", "url": "<a href="https://github.com/fisharebest/webtrees/issues/3265#issuecomment-631074435">https://github.com/fisharebest/webtrees/issues/3265#issuecomment-631074435</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by fisharebest** [comment]
I've created an issue and PR at the datatables-bs4 project:

https://github.com/DataTables/DataTablesSrc/issues/165

**Comment by fisharebest** [comment]
I've created a fix for this.

It works for me - but I would appreciate some testing/feedback before I close this issue.

**Comment by fisharebest** [comment]
My patch has been accepted by the datatables project.

**Comment by mrqd9** [comment]
Added your Remedy `[dir=ltr] table.dataTable.table-sm>thead>tr>th :not(.sorting_disabled){padding-right:0}[dir=rtl] table.dataTable.table-sm>thead>tr>th :not(.sorting_disabled){padding-left:0}[dir=ltr] table.dataTable.table-sm>thead>tr>th .btn-group-sm>.btn{padding-right:.5rem}[dir=rtl] table.dataTable.table-sm>thead>tr>th .btn-group-sm>.btn{padding-left:.5rem}[dir=ltr] table.dataTable.table-sm>thead>tr>th:not(.sorting_disabled){padding-right:20px}[dir=rtl] table.dataTable.table-sm>thead>tr>th:not(.sorting_disabled){padding-left:20px;
}` to Custom CSS and JS, except admin area everything seems ok.

**Comment by mrqd9** [comment]
https://github.com/fisharebest/webtrees/commit/7c45a75abda00d289352a0d81a6fd94fce7babe8
No effect on control panel.

**Comment by ddrury** [comment]
Custom CSS & JS module only affects user pages. You need to load the latest files from Github

**Comment by mrqd9** [comment]
> You need to load the latest files from Github

Still no effect...

**Comment by ddrury** [comment]
Clear browser cache?

**Comment by mrqd9** [comment]
Cleared cache ok now. ✅

**Comment by fisharebest** [comment]
This has been fixed.  See #3280
