### ISSUE TITLE
2.0.4. Cannot delete a person and a marriage.

### ISSUE THREAD

**Issue by singalen** [fisharebest/webtrees#3313]
A duplicate person was added in a duplicate marriage.
We're trying to delete it, but person and marriage stay there.
How can I diagnose the problem?

**Comment by fisharebest** [comment]
Perhaps you did not delete the individual?

A common mistake is to delete the *name* instead of deleting the indivdiual.
This leaves you with an indidivual without a name - which displays as "... ...".

If this is not the cause, please provide more information.
e.g. what exactly you do/click/type
It can help if you provide screenshots.

**Comment by singalen** [comment]
You are right, that was it. Thank you!

**Comment by singalen** [comment]
But the user insists that they did try to delete a person and a marriage multiple times, and it never worked.
The user is not user id=1, but does have Admin permissions and Manager role for that tree. Could it work differently for users without 
Deletion did work when I tried it under user id=1.

**Comment by fisharebest** [comment]
> Could it work differently for users without

No.  But some accounts have "automatically accept changes".

Perhaps the user did not userstand why they could still see the deleted record?

**Comment by singalen** [comment]
The user does have a "Automatically accept changes made by this user" checked.
They declined to create another excess person and test deleting it, so probably guessing is vain now.
