### ISSUE TITLE
Users can select languages not supported on the website -  2.0.5-dev 

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#3336]
On My account - Language it is possible to select any of the wt languages, even if they are not supported by the website.
We should only show the languages that are enabled for the website.

**Comment by fisharebest** [comment]
The control panel allows the admin to decide which languages are shown in the language menu.

But all languages are available to all users.  This includes:

* automatic detection of languages for first-time visitors
* a user's account preferences

This was an intentional design decision.

> We should only show the languages that are enabled for the website.

These two things are only visible to the actual user.  Why would we restrict them?

**Comment by melizaa** [comment]
I upload to my live site and to my future test site only a couple of languages.
They are the languages that I have decided in the control panel to allow the site users to use.
Only they are the languages that users should be able to select.

By allowing users to select other languages they have expectations to see the site in the language that they select, but this is not possible.

Lately one new user to my live site selected French and another Russian.
I do not know these languages. 
They should not be able to select these languages.

**Comment by fisharebest** [comment]
The way to achieve this is not by deleting (or not uploading) the language files.

Instead, you should comment out the unwanted languages here:

https://github.com/fisharebest/webtrees/blob/master/app/Services/ModuleService.php#L338-L405

**Comment by melizaa** [comment]
Thanks! It does what I wanted.
