### ISSUE TITLE
Add option to prevent trees from adding places to DB

### ISSUE THREAD

**Issue by t-karcher** [fisharebest/webtrees#3337]
Today I got aware of the issue that every place in every tree will automatically and instantly be added to the map data table (/admin/map-data) as soon as it's displayed in a facts tab.

So all these place, even when they're not mentioned in my main tree, but some test tree or an imported external tree, will eventually congest my list of places with unwanted entries.

Therefore, I'd appreciate an option to turn off the automatic creation of places in the tree settings.

**Comment by fisharebest** [comment]
> every place in every tree will automatically and instantly be added to the map data table (/admin/map-data) as soon as it's displayed in a facts tab

Previously, an admin needed to manually import places from a tree into the (global) map data.

If you have 10 or 20 trees, then you needed to import each of these separately.

This was a confusing step, and there were many forum posts where we had to explain the difference between a "place" (in your tree) and a "location" (in the map data).

So it was re-designed to create locations automatically from the places.

The assumption is that every place record has a corresponding location record.

(Locations are permanent, whereas places can be deleted/created - as happens when you re-import a GEDCOM file).

This happens in two places.

1) where we use a location on a map (place hierarchy, individual page, pedigree map, etc.)
2) all missing locations are generated when we view the admin page.

> option to turn off the automatic creation of places

I don't want to return to the old system of manual imports.

> congest my list of places with unwanted entries

If the places exist in any of your trees, then they are assumed to be "wanted".
