### ISSUE TITLE
Schema 45 upgrade

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3379]
I notice this has been created but is not being applied - is this there in advance of further work?

**Comment by fisharebest** [comment]
It got committed by mistake.  It was left there because it is harmless.

(FYI, there is also an unused schema update in wt1.7 to create a "repositories" table.)

The plan is to store the co-ordinates as floating point numbers (rather than GEDCOM strings), which would greatly simplify several DB queries.  Specifically, you could find the approximate area covered by a place by looking at the min/max long/lat for all its children (and grandchildren).  It would also clear the confusion over null / empty-strings in the long/lat columns.

**Comment by ddrury** [comment]
Good,

I think I mentioned that I hoped this would happen on Slack some time go
