### ISSUE TITLE
A question of sex!

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3438]
resources\views\individual-sex.phtml line 29 is `<span class="label"><?= I18N::translate('Gender') ?></span>` but Gender is translated as 'Sex', isn't that back to front? I'd prefer 'Sex' to be translated as 'Gender'

**Comment by fisharebest** [comment]
It is the GEDCOM `SEX` record.
My birth certificate says "Sex: boy".
My passport says "Sex: male".

IMHO, "Sex" is the technically correct label for this field - at least in British English.

However, cultural sensitivities are different across the atlantic, and the text was changed to Gender for American English a long time ago.

IIRC, there was an ISP that would not allow URLs which contained the word `sex`, which prevented PGV users from editing the field.

Since translations are from `en-US` to other languages, the `en-GB` translation has "Gender" -> "Sex".

Looking at translations for other langauges, far more translate it to a word that looks like "sex" than a word that looks like "gender".

> I'd prefer 'Sex' to be translated as 'Gender'

Trivial to do this with a module.  There is an example in `/modules_v4/`.

**Comment by ddrury** [comment]
OK, I accept you're correct, but if you want to open a can of worms (I categorically don't) have a look at https://www.ons.gov.uk/economy/environmentalaccounts/articles/whatisthedifferencebetweensexandgender/2019-02-21
