### ISSUE TITLE
Non-Shared Notes Look Weird in 2.0.7

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3444]
When browsing the Media List and one of the objects has a note where the first line is long, it shows me the new expansion arrow and an excerpt of the first line.  But when I expand the note, the first line is repeated in full after the excerpt.

It looks weird to display the first line twice.

It is especially weird for a normal note.  These are not shared notes and I don't use any particular format in my regular notes.    There is no link or any other useful reason to display the first line of a regular note twice.

Same problem seen where the media appears in an individual's fact or media tab.

When I click through to the media object's Details page, the note displays correctly.

To make this even more confusing, it's happening on some media notes and not others.

It seems that regardless of how long the first line may be, it only gets excerpted when the note has more than one line.  So in some cases I have an excerpt that gets expanded with a duplicate line, and in other cases I have a note that wraps around two or three times with no excerpt at all.

**Comment by fisharebest** [comment]
We use the same layout for inline and shared notes - because to do otherwise also looks "weird".

This change was the solution to #3289 and #3246

Notes may consist of just a link.
Therefore we cannot use the text of the note as a link to it.
Hence we need a name/link to the note in addition to the contents of the note.

The note "name" is inline text.
The full note content is block text (e.g. contains paragraphs and tables), and therefore needs to be left-aligned.

> It seems that regardless of how long the first line may be, it only gets excerpted when the note has more than one line. 

Yes, because if the note only contains 1 line, then we know it can't contain block-level text.

We need to display:
* inline and shared notes
* that may contain a single-line or block text
* that may be initially expanded or collapsed
* with a link to shared notes.

Going back to your original point

> It looks weird to display the first line twice.

I did try hiding the first (abridged) line when we expand to show the entire note.
IMHO, having it disappear at the same time as the full note appeared was worse than showing it twice.

If you can come up with a better design, then please do.

**Comment by miqrogroove** [comment]
https://www.jqueryscript.net/demo/clip-overflowing-read-more/

**Comment by miqrogroove** [comment]
This one is nice too https://www.jqueryscript.net/demo/toggle-long-text-dreadmore/

**Comment by fisharebest** [comment]
Neither of these solve the problem.

For a shared note, we need a link-target that is *NOT* the formatted note.
This is because the formatted note can consist entirely of a link.

So, instead of the first line (the note's "name"), we'd need some other link text.

e.g. Collapsed, the note's title is a link to the note

```
Note: <Lorem ipsum>
```

Expanded, we need something else to click on.

```
Note: <click here to view the note>
Lorem ipsum
dolor sit amet
```

Now, I know you refered explicitly to *inline* notes - but surely we need to render them both the same?

**Comment by miqrogroove** [comment]
> Now, I know you refered explicitly to _inline_ notes - but surely we need to render them both the same?

Honestly, this is just getting into the weeds of technical details.

I suggested a different way to preview a note that looks better.

If you want some notes to be linked and others not linked, then they will never render "both the same".

If it were up to me, I would use the demo toggle for all notes and then link the phrase "Shared note" as needed.

**Comment by ric2016** [comment]
I don't like the current solution much either.

I second the suggestion to use the label "Shared Note" for the link to the note, and not duplicate any displayed content.

**Comment by tronsmit** [comment]
>So, instead of the first line (the note's "name"), we'd need some other link text.

Agreed, but instead of collapsing the whole note, only collapse the note text (or use -read more- after n-lines)


Note:
[+]Lorem ipsum

and

Shared note: \<View note record\>
[+]Lorem ipsum

keeps both note displays identical regardless of note expansion logic and does not duplicate the first line of the note

**Comment by ric2016** [comment]
The current solution handles all complex cases properly.

I think if we just add the following modification, the simple cases would also be improved:

1. Do not show the first line of the expanded note, if it would be rendered exactly as the note's title.
2. If as a consequence of 1., the expanded note would display empty, do not show the expansion icon at all.

This would display basic single-line non-formatted shared notes as:

```
Shared Note: <line 1>
```

Multi-line non-formatted shared notes as (collapsed):

```
Shared Note: <line 1>
```

Expanded: 

```
Shared Note: <line 1>
line 2
line 3
```

And formatted shared notes (or shared notes with a link in the first line) in the same way as in the current solution, i.e.  collapsed:
```
Shared Note: <line 1 with link to @I123@>
```

Expanded: 

```
Shared Note: <line 1 with link to @I123@>
line 1 with link to Some Individual
line 2
line 3
```

and so on. Similar for regular notes.

**Comment by fisharebest** [comment]
> Do not show the first line of the expanded note, if it would be rendered exactly as the note's title.
> If as a consequence of 1., the expanded note would display empty, do not show the expansion icon at all.

Done
