### ISSUE TITLE
Scrollbars appear on place autocomplete on hover

### ISSUE THREAD

**Issue by mnoorenberghe** [fisharebest/webtrees#349]
This blocks clicking on the last item.

`overflow-x: hidden;` on the `<ul>` fixes this.
![screen shot 2015-01-04 at 1 45 08 pm](https://cloud.githubusercontent.com/assets/601139/5607052/f341c0a0-9417-11e4-9a86-29bfda6e8a3a.png)

Side note: It's tedious to fix this in each theme so could we fix the theme branch so there is a common stylesheet for each theme and then the theme's own stylesheet just overrides defaults. It would make themes much easier to maintain.

**Comment by fisharebest** [comment]
> `overflow-x: hidden;` on the `<ul>` fixes this.

In my testing, this is not quite enough.  We need to replace `.ui-autocomplete { overflow-y: auto; }` with `.ui-autocomplete { overflow-x: hidden; overflow-y: scroll; }`, otherwise hovering can cause the vertical scrollbar to appear/disappear, which can cause entries to switch from one to two rows.

This fix probably wants to wait until Rob has finished re-organising the theme CSS.

> Side note: It's tedious to fix this in each theme so could we fix the theme branch so there is a common stylesheet for each theme and then the theme's own stylesheet just overrides defaults.

I think we should make greater use of 3rd party CSS frameworks/libraries (e.g. bootstrap), and build themes on top of that.  This would provide the common/shared functionality.
