### ISSUE TITLE
[Request] Time ranges in the date field like BET hh:mm AND hh:mm

### ISSUE THREAD

**Issue by bmhm** [fisharebest/webtrees#3521]
Hi,

the german webtrees (and phpgedview) mailing lists discussed the unexpected bahaviour differences between the date and the time fields.

The date field takes arguments like "BET" to denote a time frame on which dates something happened.

The time field does not have such a function and will not guide the user through the expected formats.

## steps to reproduce

Enter a date in a record, e.g. death
Enter a time frame for the time, e.g. `BET 18:00 and 19:00`.

## actual behaviour 

The input is marked as invalid withouth much explanation.

## desired/expected behaviour

1. The time field should explain why the value was rejected
  (e.g. currently, only a specific time is allowed -- no (BET) time frames, ABT, etc.)
2. in a future version (maybe another issue, RFC) can allow the input of time frames.

**Comment by fisharebest** [comment]
> The time field should explain why the value was rejected

The time field has placeholder text which shows the two acceptable formats

<img width="611" alt="Screenshot 2020-09-20 at 21 57 55" src="https://user-images.githubusercontent.com/2306088/93722137-7b3fe680-fb8c-11ea-87dd-d172559c917b.png">

`INDI:BIRT:DATE:TIME` and `INDI:DEAT:DATE:TIME` are not standard GEDCOM fields.

`TIME` should only be used in the `HEAD` record and in `CHAN` events.

webtrees supports them in birth/death because they are created by other applications.

> in a future version (maybe another issue, RFC) can allow the input of time frames.

In webtrees 2.1.0, support for custom tags is being moved to modules.
This means it will be simple to create a module that allows you to change the way these fields are used.

**Comment by bmhm** [comment]
Thanks, Greg. I agree that should be enough. Although it is not visible after typing the first letter. 

Anyway, I will redefine this issue to a feature request, but I guess it can be a lower priority.

**Comment by marku5** [comment]
I would opt **against** adding this option into the basecode to be as much be compliant as possible to the GEDCOM-standard. Therefore this shall not be a feature request. Just my 2 cents.

If a separate module (which does not need to be activated if not wanted) implements this feature (as above described by Greg) I wouldn't care.

**Comment by bmhm** [comment]
Yeah, maybe this should go into the gedcom standard first.
A module could add a comment field, I guess?

**Comment by fisharebest** [comment]
I will reject this feature-request.

We should encourage people to create data that follows the GEDCOM standard.  This ensures it is safe, portable, etc.

We should not encourage people to create/use non-standard tags and data.

The correct place to store times of events is in notes.

However, in webtrees-2.1, we will have a system that allows others to create modules that will provide these features.
