### ISSUE TITLE
Fr: link to new release of custom module

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#3543]
When a new release of a custom module is available this text appears in control panel:
![image](https://user-images.githubusercontent.com/5641963/95787913-c1472080-0cda-11eb-8d57-59d31806e019.png)
It would be nice if this text contains the link to the download page where one can find the new release.

Note: this is not the same link as set in the module as 'customModuleSupportUrl' or 'customModuleLatestVersionUrl()', so a third link need to be set in the module file.

But I think this would be a convenient enhancement!

**Comment by ric2016** [comment]
Somewhat related: Would it be useful to extend the information obtained via customModuleLatestVersionUrl (e.g. by using json):

There are cases where a new version of a custom module also requires an update of webtrees itself; and conversely, an update of webtrees may break the currently installed version of a custom module. In order to handle this, we'd require a list of versions of a custom module, each with a minimal required and maximal supported webtrees version.

While we're at it, we could also add a changelog of important changes to each version, so that users can decide beforehand whether to upgrade immediately.

In the example above, this could be displayed like this:
"An upgrade is available.
Justlight - 2.0.7.2 - 2.0.9 (requires webtrees 2.0.9 or later).
Changelog (2.0.8): Minor bugfixes and I18N."
Changelog (2.0.9): Some layout adjustments."

The max. supported webtrees version should probably be shown as a warning elsewhere.

Or am I overthinking this?
(My hope was that there would be less 'breaking changes' per webtrees release, but we don't seem to be quite there yet)

**Comment by JustCarmen** [comment]
No, I think this would be very handy. It is not unlikely that a new webtrees version will be break a current version of a custom module. Even a little change could cause that. I've just experienced it myself that the latest webtrees version immediately broke the Fancy Imagebar by renaming a function it was depending on. So the latest version of that module only works with the latest version of webtrees, while earlier versions won't work. So I think it would be a good idea to provide more information to the user.

**Comment by ric2016** [comment]
Greg, any thoughts? I could create a PR for this. We could use a format like this:
(releaseUrl would be the original feature request)

```
[
	{
		"version":"2.0.9.0",
		"recommendedWebtreesVersion":"2.0.9",
		"minRequiredWebtreesVersion":"2.0.9",
		"maxSupportedWebtreesVersion":"2.0.10",
		"changelog":"Minor bugfixes and I18N.",
		"releaseUrl":"https://abc.de/2.0.9.0"
	},
	{
		"version":"2.0.10.0",
		"recommendedWebtreesVersion":"2.0.10",
		"minRequiredWebtreesVersion":"2.0.9",
		"maxSupportedWebtreesVersion":"2.0.10",
		"changelog":"Some layout adjustments.",
		"releaseUrl":"https://abc.de/2.0.10"
	}
]
```

Webtrees would then scan the list and attempt to find the currently installed version of the module, and suggest an update based on further available versions that are compatible with the current webtrees version, listing all changelogs from in-between versions, and using the release url as a link.

**Comment by fisharebest** [comment]
I'd actually like to go a bit further.

Eventually, I want to move modules to from `/modules_v4` to `/data/modules` (as this is the only place that webtrees can write files).

It means that it can install/upgrade/remove modules via the control panel.

**Comment by ric2016** [comment]
ok, but that is probably something for 2.1 or (much) later? And it doesn't really change the fact that additional information is required - compatibility of custom modules will still be an issue.

I'd prefer to do something about that now - the proposed information can later be used to install and upgrade modules directly.

**Comment by ric2016** [comment]
After the experience with the 2.0.12 release, I'm now overriding the update wizard in my custom modules, so that at least a warning is displayed in case of incompatible custom modules. If this turns out to be useful (it may require some further fine-tuning), I'd be happy to contribute this to the webtrees core.

![wizard](https://user-images.githubusercontent.com/18174787/111210308-61c4a800-85cd-11eb-9a97-04ed3407c391.png)

**Comment by fisharebest** [comment]
See https://github.com/fisharebest/webtrees/issues/3783

**Comment by ric2016** [comment]
Sounds good, but this is still not addressed there yet:

> And it doesn't really change the fact that additional information is required - compatibility of custom modules will still be an issue.

**Comment by fisharebest** [comment]
> Sounds good, but this is still not addressed there yet:

Perhaps I wasn't clear.  Issue #3783 is a place to suggest enhancements - so we can consider them all together.
