### ISSUE TITLE
Lists/Fishes does not work with dotless i

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#3567]
When clicking on a surname in the list of surnames normally opens the list of all individuals with this surname. This does not work if the surname contains a dotless i, like in "aydın". The generated URL contains the upper case version: "AYDIN" in the query string. This does not work, the lower case version containing "aydın" is ok.
See example in webtrees forum: https://www.webtrees.net/index.php/en/forum/help-for-2-0/35061-language-issue#81083

**Comment by ric2016** [comment]
It seems that a specific collation should be used for the respective query ([see here for more](https://stackoverflow.com/questions/59211363/mysql-does-not-treat-%C4%B1-as-i)).

Currently, a locale-specific collation is used (maybe this is for ordering, or are there other reasons?), which usually doesn't handle the dotless i correctly when matching case-insensitively (note that it works if Turkish is selected as language).

Easiest solution may be to use a proper fixed collation for the query itself, and the locale-specific collation only for ordering. Alternatively, handle the upper-casing for the query parameter differently? I'm not sure why this is done anyway.

**Comment by fisharebest** [comment]
I created a tree with two individuals:
`dotless /Aydın/`
`dotted /Aydin/`

The individual list of "A" shows:

Turkish - two different surnames.
English - one surname with two variations.

This is working as designed.

For Turkish, the two different links show two different lists - one for dotted and one for dotless.

This is working as designed.

For English, the list of surnames only includes the dotted i.

This is incorrect, and appears to be caused by the MySQL collation rules.

We use `utf8_unicode_ci`.

```
mysql> select 'I' collate utf8mb4_unicode_ci = 'ı';
+---------------------------------------+
| 'I' collate utf8mb4_unicode_ci = 'ı'  |
+---------------------------------------+
|                                     0 |
+---------------------------------------+
```

If we switch to `utf8_general_ci`, then we get correct matching of dotted/dotless "i"s.

```
mysql> select 'I' collate utf8mb4_general_ci = 'ı';
+---------------------------------------+
| 'I' collate utf8mb4_general_ci = 'ı'  |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
```

BUT - `utf8_general_ci` does not support multi-character equivalences.  e.g. `æ = ae`, `ẞ = SS`, etc.

So, it is not possible to select a collation rule that will match dotless i and also match more common characters at the same time.

The code does work for Turkish.
