### ISSUE TITLE
2.0.10-Default language settings do not work

### ISSUE THREAD

**Issue by DaPoHou** [fisharebest/webtrees#3586]
I have set the language to Simplified Chinese in the Control Panel - Website Preferences.
However, the pages visited by Google search engine are still in English.

**Comment by vytux-com** [comment]
The default language setting is overridden by the clients request.

If the user has set his browser / os preference to english he will get an English page.

Guessing Google prefers english over Chinese and Baidu would do the opposite and fetch the Chinese version even if site 'default' was English

**Comment by DaPoHou** [comment]
Google search does not carry any language tags when accessed.
So it should be accessed according to the language in the control panel.

**Comment by DaPoHou** [comment]
I find that this may be the problem.
The $tree value is always empty.
https://github.com/fisharebest/webtrees/blob/b77f2e9399d0c7e5a5dfcef91d84237029afb7d6/app/Http/Middleware/UseLanguage.php#L99

**Comment by ric2016** [comment]
> I find that this may be the problem.
> The $tree value is always empty.

The reason for this seems to be that the 'tree' request attribute is initialized in [`Router.php`](https://github.com/fisharebest/webtrees/blob/b77f2e9399d0c7e5a5dfcef91d84237029afb7d6/app/Http/Middleware/Router.php#L137), which is Middleware that is initialized after `UseLanguage.php`, see the order [here](https://github.com/fisharebest/webtrees/blob/b77f2e9399d0c7e5a5dfcef91d84237029afb7d6/app/Webtrees.php#L112).

Moving `UseLanguage` to a position after `Router` may fix this issue - There may be other middleware in-between that is dependent on the language though (via `I18N.php`), so this has to be checked first. Due to all this global state, it is not immediately clear what the actual dependencies are unfortunately.

**Comment by fisharebest** [comment]
In old versions of webtrees, you set a language for each tree.

But now, you set a language for the site.

This code needs to be updated to use the **site** setting - not the **tree** setting.
