### ISSUE TITLE
"Do not have permission message" not always accurate.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#3612]
Edited a SOUR record, then used the browser "back" three times to return to the individual.

The first "back" would have been to the edit form.  I think a second edit should be allowed, but even if not, the message "you do not have permission to view this page" is a bit confusing for an admin to see.  After I get to the individual page, I see the same message if I use the "forward" links in the browser.

**Comment by ric2016** [comment]
(This occurs for other facts as well, not only for source facts)

The easiest fix seems to be to use a specific FactNotFoundException with a proper error message, instead of the generic HttpNotFoundException.

> I think a second edit should be allowed

This is tricky and probably too much effort.
The reason for the current behavior is that facts have no fixed identifier within a gedcom record. Therefore, a hash of the fact's content is used as the identifier. Once a fact is edited, the identifier therefore changes and you can't go back (unless you edit a second time, restoring the original content. Note that in that case the back button all the way back to the first edit works).

(We could attempt to identify a fact based on its position within the gedcom record instead, but this is problematic in case facts are added or removed. The navigation would probably be even more confusing.)

**Comment by WGroleau** [comment]
How facts are found is not relevant.  It was NOT a fact record, it was a zero-level SOUR for which (AFAIK) should be the unchanged xref.   Besides, if the xref did change, it should say "can't find the record" instead of saying the admin is not allowed to see it.

**Comment by ric2016** [comment]
@WGroleau you seem to misunderstand this - Sources have facts as well (there is even a block which says "Fact or event"). Also look a the url of the edit dialog, it has the xref of the source and then another id for the respective fact (source note or source text or whatever you edit), with pretty urls enabled it is something like `http://localhost/webtrees/tree/tree1/edit-fact/S176/aafb994c1a9483ab880005ea3223146c`.

**Comment by fisharebest** [comment]
> The easiest fix seems to be to use a specific FactNotFoundException with a proper error message, instead of the generic HttpNotFoundException.

The "not found" error page is a navigational dead-end.

The user will probably want to return to the record - but there is no link to it.

Instead, I think we should simply redirect back to the record.
