### ISSUE TITLE
Theme class bug

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#362]
Need to add showFull & talloffset parameters to url in function menuChartPedigree()

BTW do you want this sort of thing added here ?

**Comment by ddrury** [comment]
showfull also needed on other charts

**Comment by fisharebest** [comment]
The way these parameters are preserved between calls is a bit clumsy.  I think that user preferences would be better - a bit like the "show_marnm" settings in the individual list.  For visitors, we could store "user-preferences" in the session, rather than the database.

For the relatively small difference in size on screen, do we really need this option?

Alternatively, we could use JS hide/show or CSS to make this change - which means we wouldn't need to reload the page.

**Comment by ddrury** [comment]
Personally I never bother with the small display so losing that option wouldn't bother me, but if it's kept then I'd be inclined to go wth the JS/CSS solution

**Comment by fisharebest** [comment]
The "show full" was fixed in 5884aad9d and the orientation seems to be working now.
