### ISSUE TITLE
Create full name as required

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3625]
Add a module for generating full name of an individual as it required by a non-coder webtrees admin, 
Standard name format set by webtrees should be a default setting but with option to customize it, as standard name format has variation. 
Finally, this setting should be such that the name tags are in a custom sequence or absence.

**Comment by fisharebest** [comment]
You will need to provide examples.

I cannot understand your requirements from this description.

**Comment by mrqd9** [comment]
Actually I wanted to say that Displaying the full name should be customizable.
E.g: If I want to display names this order `NAME-PREFIX SURNAME GIVEN-NAME` there is no option to do that

**Comment by vytux-com** [comment]
But that only works if you want to support 1 country & language only.

My family is spread all over the world and thus have different name conventions

**Comment by fisharebest** [comment]
The name is always displayed *exactly* as it is stored in the `NAME` field.

So, you must store the name as `/SURN/ GIVN`, `GIVN /SURN/`, etc.

It is not possible to re-arrange existing names to have a different order, because you cannot distinguish `GIVN` from `NPFX` and `NSFX`.  e.g.

Greg /Roach/ Senior
Professor /Roach/ Greg

So, you must store the names in the correct order.

The `NAME` field is often completed automatically.  To edit it, you must click its edit icon.

TIP: if you select a language that uses `SURN /GIVN/`, (chinese, japanses, korean or hungarian), then webtrees will automatically create names in this order.

**Comment by mrqd9** [comment]
Thank you for your reply. 

> It is not possible to re-arrange existing names to have a different order,

I got it..
Before closing the issue I want to ask one more question, 
How can I set the name field to generate name like this `NPFX GIVN NSFX /SURN/` any jquery for this?

**Comment by fisharebest** [comment]
> How can I set the name field to generate name like this

The code is here:

https://github.com/fisharebest/webtrees/blob/2.0.11/resources/js/webtrees.js#L83-L102

Note that if you modify this file, you must run a script to recreate `webtrees.min.js`
You will need nodejs/npm.  Run these commands:

```
npm install
npm run production
```

**Comment by arsenyspb** [comment]
@fisharebest Hi Greg, Happy New Year! Bouncing this up to check. E.g. in Gramps, there's a Preference (per tree), - wondering if it's time to have a spike to establish a feature parity (global per server, per tree, per user override, or something like this).

![image](https://github.com/user-attachments/assets/1ca25746-b20a-433f-bd1d-b382171a4e6f)

If you have some time, can you hypothesize and write up what code paths one may tinker around at to implement this on Control Panel level?.. Sound like a user-friendly community contribution PR for the 2025 new year resolutions.
