### ISSUE TITLE
XRef-IDs now always start with X instead of I, F, M or S.

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3637]
It was great that XRef-IDs for Family started with F, for individuals with I and for media objects with M.
Now, since upgrading from 1.7.x to 2.x the XRef-IDs for all new objects starts with X - like X69 and so on.

It was better to have separate letters for different object types. I dislike the actual behaviour. I know it is correct according to GEDCOM standard, but all genealogical software I know handle it in the way that F, I, M and S are used.

**Comment by fisharebest** [comment]
> all genealogical software I know handle it in the way that F, I, M and S are used.

Except the ones that use `P` (person) instead of `I` (individual).
And the ones that use `O` (object) instead of `M` (media).
And the ones that use suffixes instead of prefixes...

There is a third-party module that allows you to specify your own prefixes.
https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf

**Comment by HonkXL** [comment]
Oh great - this seems to become a must-heave-plugin for me.
Only bad that I have to fix all bad XRefs no manualle. But I am happy that there are only around 200....
