### ISSUE TITLE
0 OBJE @X13224@ are reversed

### ISSUE THREAD

**Issue by phildtmm** [fisharebest/webtrees#3657]
I have two media folders associated with my tree.  When doing an export, the media is the primary folder has the above format (i.e. OJBE before the @X...@ identifier.  For the Fancy bar folder, the order is correct.  Example:
0 OBJE @X13227@                <-------PRIMARY FOLDER
1 FILE E:\DermottFT_Photos\P500082_509_788.jpg
2 FORM jpg
3 TITL GordonTrimble.jpg
0 @X13229@ OBJE                <-------FANCY BAR FOLDER
1 FILE E:\Fancy\P1030_674_908.jpg
2 FORM jpeg
3 TYPE photo
2 TITL Mary Jane Baker
1 CHAN
2 DATE 16 DEC 2020
3 TIME 14:08:51
2 _WT_USER phild

Webtrees version is 2.0.11

**Comment by fisharebest** [comment]
This was a bug in 2.0.10 (and also 2.0.9?).
It was fixed in b77f2e9399d0c7e5a5dfcef91d84237029afb7d6

It occurs when you import a GEDCOM file that uses inline media.
These were not correctly converted to media records.

Inline media are created by other applications.  So, this issue mostly affects people who use webtrees only to display data, and will be fixed automatically when they next import from the other application.

But if you need to fix the data in webtrees, use:

Control panel -> Family tree -> Data fixes -> Search and replace

Search method: Regular expression
Search for `^0 OBJE @([^@]*@`
Replace with `0 @$1@ OBJE`
Records: Media objects
