### ISSUE TITLE
continuous-integration/travis-ci/pr fails on pull request

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3670]
Comparing the content of vendor/bin on my local version of wt2 at https://github.com/fisharebest/webtrees/commit/b43e8d2bb2c20432b6d427f0f5d9a32679a9aa4f with fisharebest/webtrees reveals significant differences. I have the following additional files:
```
-a----        16/09/2019   4:09 pm            124 composer.bat                                                         
-a----        22/09/2020  11:06 am             34 doctrine-dbal                                                        
-a----        16/09/2019   4:09 pm            306 jsonlint                                                             
-a----        16/09/2019   4:09 pm            120 jsonlint.bat                                                         
-a----        16/09/2019   4:08 pm            325 php-coveralls                                                        
-a----        16/09/2019   4:08 pm            139 php-coveralls.bat                                                    
-a----        16/09/2019   4:09 pm            303 phpunit                                                              
-a----        16/09/2019   4:09 pm            117 phpunit.bat                                                          
-a----        16/09/2019   4:09 pm            323 validate-json                                                        
-a----        16/09/2019   4:09 pm            137 validate-json.bat                                                    
-a----        16/09/2019   4:08 pm            328 var-dump-server                                                      
-a----        16/09/2019   4:08 pm            142 var-dump-server.bat 
```

Just noticed on branch 2.1 that the vendor folder has been removed but .travis.yml still refers to it.

**Comment by fisharebest** [comment]
> I have the following additional files:

It is safe to delete them.  They are only needed to run the unit tests, and will be recreated automatically by `composer install` (see below).

> Just noticed on branch 2.1 that the vendor folder has been removed

Yes.  It is "bad practice" to include your dependencies (`vendor/*` and `node_modules/*`).
The former are included for historic reasons - when PGV started, there were just a few libraries, and no easy way to install them.

Now, we have package managers like `composer`.
If you are using the development version of the code, you are expected to install your dependencies `composer install --no-dev`.
If you want the development tools as well (e.g. the PHP debugbar), then `composer install --dev`.

Why change now?  We will be renaming the `master` branch to `main`, which is a breaking change - so two breaking changes together.

More documentation will follow at the time.

> travis-ci/pr fails on pull request

I noticed travis failing.  The test scripts are also run by github actions, so the tests are passing.
It is probably due to lack of support for older PHP versions on the travis environment.
I'll look at it when I merge the `2.1` branch, and drop support for older PHP.

**Comment by ddrury** [comment]
> I noticed travis failing

When I push a commit to github it passes because .travis.yml calls phpunit which exists in my repository but not yours
