### ISSUE TITLE
Clipping Cart Export - Error

### ISSUE THREAD

**Issue by kexuebin** [fisharebest/webtrees#3722]
Now the export format is:
0 @X3649@ OBJEmedia/ke/29ffc09db9db256514ea7d989ae80b1bc7bc717b.jpg
2 FORM jpeg
3 TYPE book

**Comment by fisharebest** [comment]
This was an error that happened during import.

The bug existed in webtrees 2.0.10
It was fixed in webtrees 2.0.11 - see b77f2e9399d0c7e5a5dfcef91d84237029afb7d6

The error is in code that converts "inline media" to "media objects".

webtrees does not use inline media.  During import, we convert it to media objects.

To fix this: Control panel -> Family tree -> Data fixes -> Search and replace

Search: `@ OBJEmedia/`
Replace: `@ OBJE\n1 FILE media/`
Type: Regular expression
