### ISSUE TITLE
displaying large pdf attachment - allowed memory size exhausted

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#3753]
I uploaded a pdf file with the size of 175 MB.
When I now want to display this file in webtrees, I receive this message:

Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1402625240 bytes)
/home/genealogie-weiland/domains/wt.genealogie-weiland.de/public_html/vendor/league/flysystem/src/Util/MimeType.php: 209

PHP memory limit is set to 1 GB, so it's much more than most shared hosters can offer. Why webtrees tries to allocate 1.4 GB of RAM while showing a 175 MB file?

Tested on CentOS 8.3 with PHP 7.4.16

**Comment by fisharebest** [comment]
This seems to be a bug in PHP.

We are using a standard PHP function to work out the mime-type of a file.

Here I am testing with a 200MB PDF file, and a 1GB memory limit…

```
php > echo memory_get_usage(), PHP_EOL;
389528
php > $x = file_get_contents('big.pdf');
php > echo memory_get_usage(), PHP_EOL;
200401824
php > $f = new finfo(FILEINFO_MIME_TYPE);
php > echo $f->buffer($x), PHP_EOL;
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1600088328 bytes) in php shell code on line 1

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1600088328 bytes) in php shell code on line 1
```

**Comment by fisharebest** [comment]
It seems this is a known bug in PHP - https://bugs.php.net/bug.php?id=78987

An internal function requires enough memory to hold 8 copies of the file.

It was reported and fixed in the upstream library on 2021-02-06

It should be fixed in a subsequent release of PHP.

I'm going to close this here, as there's nothing we can do - and a fixed version of PHP should be available soon...
