### ISSUE TITLE
Table wt_place_location vs. wt_placelocation

### ISSUE THREAD

**Issue by jpretired** [fisharebest/webtrees#3768]
in 2.0.12 there is wt_place_location, structure:
![image](https://user-images.githubusercontent.com/350656/110964109-1ef79b80-8353-11eb-8061-9ccd0e49822d.png)

in 2.0.11 there is wt_placelocation (different table name), structure:
![image](https://user-images.githubusercontent.com/350656/110964359-6716be00-8353-11eb-8b84-74fc3f256b93.png)

I suppose this is correct.
What is the right way to downgrade from 2.0.12 to 2.0.11 please?

**Comment by fisharebest** [comment]
> I suppose this is correct.

Yes, this is correct.

>What is the right way to downgrade from 2.0.12 to 2.0.11 please?

There is no downgrade procedure from 2.0.12 to 2.0.11.
For details, see https://webtrees.net/faq/downgrade/

Why do you want to downgrade?

**Comment by jpretired** [comment]
Because I like the idea of vesta shared places and I was testing it on my localhost test site with wt 2.0.11. Yesterday I upgraded to wt 2.0.12 and it seems to me that the latest release of vesta shared places module does not work correctly. So I wanted to go back to 2.0.11 and then repeat the upgrade to make sure it was processed correctly.
Now I see it was a silly idea. I will have to wait until the author of vesta modules supplies a new release. Am I right?

**Comment by fisharebest** [comment]
> I will have to wait until the author of vesta modules supplies a new release. Am I right?

Yes, I think that is the best solution.

The author of the vesta modules is usually very efficient when creating new versions.

**Comment by ric2016** [comment]
I'd like to avoid these issues in the future. If we were able to indicate target ranges for custom modules, as suggested in https://github.com/fisharebest/webtrees/issues/3543#issuecomment-707873598 , that would really be helpful. If there is no progress on that issue, I may have to disable the Vesta modules on any mismatching webtrees version number, and/or modify the webtrees update functionality in order to display a warning regarding updates. I'd rather have this functionality in webtrees itself!

**Comment by fisharebest** [comment]
This issue will be reviewed in #3783
