### ISSUE TITLE
Question: Is "Main" branch is 2.1.0?

### ISSUE THREAD

**Issue by mrqd9** [fisharebest/webtrees#3780]

**Comment by mrqd9** [comment]
On webtrees.net there are two live demos in menu


> Live demo - 2.1.0

> Live demo - dev

**Comment by fisharebest** [comment]
The `main` branch contains the latest development code.  It contains code that will soon become `2.1`.

There are separate branches for old versions - where we stopped supporting old versions of PHP.
These branches exist so that we can create patches/updates for this old code, if necessary.

Any other branch (`develop`, `test`, etc. is tempoary and should be ignored).


There are two demo sites:

* https://dev.webtrees.net/demo-stable/ is `2.0.13`
* https://dev.webtrees.net/demo-dev/ is `2.1.0-dev` (the `main` branch).
