### ISSUE TITLE
Silly request

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3802]
Whenever I make a commit to github, StyleCI generates a pull request for resources/lang/en-US/messages.php

```
return array (
return array(
two lines of code that githubs formatting goes haywire on
)
```

i.e replace the 2nd line with the first ie add space between 'array' and' ('

Can I change it please, it's driving me crazy

**Comment by fisharebest** [comment]
Hmm.  It doesn't flag these as problems for me.

Also, it doesn't send me pull-requests because I disabled in in the settings (https://github.styleci.io/repos/11836349/settings).

![Screenshot 2021-03-22 at 14 36 53](https://user-images.githubusercontent.com/2306088/112006889-0ee27780-8b1c-11eb-8352-74a5fb23c83d.png)

Perhaps you need to do this in your own style-ci settings?

**Comment by ddrury** [comment]
done - thanks
