### ISSUE TITLE
For info: Travis-CI always fails on pull requests

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3832]
See also closed issue  https://github.com/fisharebest/webtrees/issues/3670#issue-786095546.

The runs always fail with the message 

> No environment variables set

 and one of the required variables is GITHUB_OAUTH_TOKEN which I guess means travis cannot access github.

An externally raised PR creates a security issue and is discussed on the Travis CI website [building pull requests](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
)

**Comment by fisharebest** [comment]
I need to add my personal access token to get around github API limits.

I guess that travis will not let you see this token, as it would let you access github as me.

I have just pushed a change to `.travis.yml` so that it only attempts to use the token when it is set.

Does this help?

...of course, you may hit API quota limits.

**Comment by fisharebest** [comment]
I'm not 100% certain that I still need the access token.

Travis now lets you cache the /vendor folder so there shouldn't be so many requests to github...

**Comment by ddrury** [comment]
Fixed by d65f059c34ca2c864a5a64b4ad25d254e7a8b6b8
