### ISSUE TITLE
Proposal: Extend selection list for MARR.TYPE

### ISSUE THREAD

**Issue by Manja-S** [fisharebest/webtrees#3837]
Some time ago Bert Koor wrote a [post on marriage types](https://www.webtrees.net/index.php/en/forum/8-translation/35014-change-dutch-translation-of-registered-partnership#80768) in the Webtrees Forum. Based on this post, as well as on my own desires, I would like to have the selection list for MARR.TYPE extended. Here's a proposal, together with translations in German and Dutch. It is largely based on what I found at the [website of Tamura Jones](https://www.tamurajones.net/GEDCOMRelationships.xhtml). I've added the synonyms because I'm not always sure  which description is preferable / most commonly used.

MARR.TYPE value	|	description (en)	|	description (de)	|	synonyms (de)	|	description (nl)	|	synonyms (nl)
------------	|	------------	|	------------	|	------------	|	------------	|	------------
unknown	|	Relationship (type unknown)	|	Unbestimmte Verbindung	|		|	Relatie (type onbekend)	|	
marriage	|	Marriage	|	Verheiratet	|		|	Huwelijk	|	
not married	|	Not married	|	Nicht verheiratet	|	Uneheliche Verbindung, Nicht ehelich, Unverheiratet, Außerehelich	|	Ongehuwd	|	Niet gehuwd
civil	|	Civil marriage	|	Ziviltrauung	|	Zivil, Amtlich, Bürgerlich, Standesamtlich, Standesamtliche Trauung	|	Burgerlijk huwelijk	|	
religious	|	Religious marriage	|	Kirchliche Trauung	|	Katholisch, Evangelisch	|	Kerkelijk huwelijk	|	
common law	|	Common law marriage	|		|		|		|	
partnership	|	Partnership	|	Gemeinschaft	|		|	Partnerschap	|	Partners
registered partnership	|	Registered partnership	|	Eingetragene Partnerschaft	|		|	Geregistreerd partnerschap	|	
living together	|	Living together	|	Lebensgefährten	|	Lebensgemeinschaft	|	Samenwonend	|	
living apart together	|	Living apart together	|		|		|	LAT-relatie	|	Niet samenwonend

There is a catch, however, which I don't know how to solve easily:
"In the [current] Dutch version [...], 'Registered partnership' is translated as 'Samenlevingscontract'.
This is not the correct translation, because it should be 'Geregistreerd partnerschap'."
"One problem with changing an existing translation is that there are dozens of users that have picked the Dutch type 'Samenlevingscontract' from the drop-down list for ages, and upon an update will be confronted with an unwanted change of terminology."

**Comment by fisharebest** [comment]
We currently have `civil`, `religious` and `partners` (Registered partnership).

`partners` was deliberately vague, to include all officially-recognised relationships that are not legal marriages.
Each country has its own definitions and rules.

* `unknown` / `marriage` - I think these are the same as not having a `TYPE`.

* `not married` - This will break existing logic.  If a `MARR` record exists, then we use the labels "Husband/Wife".  If a `MARR` record does not exist, we use the label "Partner".  So, if we add this, then we will show unmarried people as husband and wife.

* `common law` - Here in the UK, this means `not married`, but living as if you were.

* `partnership`- Since you also list `registered partnership`, I guess this means "Unregistered partnership".   Is that the same as `common law`?

* `living together` and `living apart together` - How are these different to `common law`, `partnership`, etc.?

For each term, we would need clear definitions that can be translated into each language.

For 2.1, we have a [MarriageType](https://github.com/fisharebest/webtrees/blob/main/app/Elements/MarriageType.php) object, which is easy to modify.

**Comment by Manja-S** [comment]
My proposal was based on the [(incorrect) assumption](https://webtrees.net/gedcom/) that Webtrees uses GEDCOM 5.5.5: 
_FamilySearch GEDCOM 5.5.1 calls the MARR record the "marriage record". GEDCOM 5.5.5 keeps the record for compatibility, but uses more accurate terminology; "relationship record". The MARR record is the relationship record because it can and must be used for every couple relationship, not just marriage._

So, if I understand correctly, these are the current ways to register the types of relationships I mentioned above:

`MARR`

- 1 MARR => unspecified/`unknown` type of marriage

- 1 MARR
2 TYPE `civil` => a marriage performed, recorded and recognised by a government official

- 1 MARR
2 TYPE `religious` => a marriage performed by a minister, priest or pastor or person who has been registered as an officiant
 
- 1 MARR
2 TYPE `partners` => includes all officially-recognised relationships that are not legal marriages, like  `registered partnership`.

`_NMR`

- 1 _NMR Y => Unspecified/`unknown` type of `not married` relationship

- 1 _NMR Y
2 TYPE `partners` => includes all relationships that are not  officially recognised, may include `common law`, `partnership`, `living together` and  `living apart together`

If these GEDCOM snippets are correct, the only problem that will probably remain unsolved is the incorrect translation:
_In the [current] Dutch version, 'Registered partnership' is translated as 'Samenlevingscontract'.
This is not the correct translation, because it should be 'Geregistreerd partnerschap'._
=> One problem with changing an existing translation is that there are dozens of users that have picked the Dutch type 'Samenlevingscontract' from the drop-down list for ages, and upon an update will be confronted with an unwanted change of terminology.

**Comment by fisharebest** [comment]
Since 2.0, webtrees ignores `_NMR` records.
It can display them, but like all custom tags, they have no meaning.

A couple is married if a `MARR` exists.  They are unmarried if it does not exist.
This is only significant for choosing relationship names.

As far as I can tell, the `_NMR` tag was created by BrothersKeeper.  So, from webtrees 2.1, it will be necessary to enable the "BrothersKeeper compatibility" module to use this tag.

Personallly, I use `1 NOTE` instead of `1 _NMR`.

FYI, I just raised a related issue on the [GEDCOM 7.0 specification](https://github.com/FamilySearch/GEDCOM/issues)

**Comment by Manja-S** [comment]
> Since 2.0, webtrees ignores `_NMR` records.
> It can display them, but like all custom tags, they have no meaning.

I've got a feeling it would be wise to identify and cleanup my custom tags. Will the `_TODO` tag keep working? I'd hate to loose my  Research tasks  block.

> Personallly, I use `1 NOTE` instead of `1 _NMR`.

I'm curious why you use `1 NOTE`. I would have chosen `1 FACT`, or `1 EVENT` if the date when people started to live together is known.

**Comment by fisharebest** [comment]
> I've got a feeling it would be wise to identify and cleanup my custom tags. Will the _TODO tag keep working?

No functionality is being removed.  It is just being separated.  Standard GEDCOM is handled by the core code.  Non-standard extensions are handled by modules.

**Comment by Manja-S** [comment]
I'm glad that you won't remove functionality. I've been using Webtrees for some years now and I still marvel at all of the possibilities it offers.

**Comment by fisharebest** [comment]
I'm going to close this now.

The code for supporting custom tags is now pretty stable.

You would create `class MyCustomMarriageType extends MarriageType { public function values() {return [...]}; }
Add whatever types you want.

You would then create a custom-tags module which replaces the default GEDCOM element like this

```
public function customTags(): array
{
    return [
        'FAM:MARR:TYPE' => new MyCustomMarriageType(I18N::translate('Marriage type')),`
    ];
}
```
