### ISSUE TITLE
Add websites logs to replicate functionality of v1

### ISSUE THREAD

**Issue by r0cker99** [fisharebest/webtrees#3840]
As discussed in the forum thread and supported by various users, I would like to formally add this request to the issue tracker.

https://www.webtrees.net/index.php/en/forum/help-for-2-0/33968-website-logs#83827

**Comment by fisharebest** [comment]
I haven't looked at 1.7 for several years, and do not have easy access to a 1.7 test/dev environment.

Could you describe exactly the functionality you want.

There are several types of search.  Some can search multiple trees.  How should this work?

**Comment by hartenthaler** [comment]
In webtrees 1 there was a log file entry whenever a visitor searched for something. This allowed an administrator to see in the webtrees logfile in which topics (names, locations, ...) anonymous visitors are interested. It is not so interesting where they are searching and what they found, it is interesting what they are searching using the webtrees search function. This allows you to focus on persons and data in your tree which was interesting for your users. But maybe there are privacy concerns, even if the visitor is anonymous because if he is searching first for his own name and then for other topics, you can build up a profile of this user.

**Comment by r0cker99** [comment]
I think the most useful function for me (and likely those that commented on the forum thread) is the ability to see the searches that visitors have performing. It does help to know the levels of interest in certain family lines on your site.
There was also one time that I was sent 'possible record matches' via Ancestry that matched to my own not entirely 100% certain research. By trawling the logs for user login details, I worked out that one of my users must have copied my research directly into Ancestry. This was helpful because instead of confirming a second source of my research, rather it highlighted that my own work had been copied.
You could filter on user, tree, by date, IP address

**Comment by fisharebest** [comment]
> You could filter on user, **tree**, by date, IP address

So, if you have 50 trees, and someone uses the general-search to search all of them, you want 50 separate log entires, one for each tree?

**Comment by hartenthaler** [comment]
The probability that I have 50 trees visible to visitors is not so high, so the answer is "yes". Most of my users are using the Search located in the top right corner of the screen, so they are searching only in one tree. If they manage to find the general search and activating there all the trees, I'm fine to see in the log file that they are so experienced.
An important question is: should all searches be logged or only searches by anonymous visitors? I would prefer not to log searches of members. They know me and if they have problems with finding some information they could ask me. I trust them and would prefer not to log all their activities by privacy concerns.

**Comment by r0cker99** [comment]
> You could filter on user, tree, by date, IP address

I think what I was trying to describe in my previous comment that you referenced, was the functions/options of the user form in the v1.7 logs. In fact, this 1.7 user form is included in v2, with a slightly different layout, although obviously the full functionality not implemented.

Was it such an issue in 1.7 to have the potential to search across 50 trees and log each attempt? Most webtrees sites would have a handful of visible trees at most. And I am mostly interested in general searches from non registered visitors, with only one visible tree.

My observation is the same as hartenhaler above, in that users tend to use the top right search.

**Comment by PKlimis** [comment]
The recording of the search request was extremely useful in version 1.x for the administrator of the site. It helps to see the trends of the intersting of visitors and in many cases to see in which direction you can turn the interest of the genealogy research speaking for my case. The message (ex. Type: General Query: Panagiotis Klimis) mainly and timestamp are the most usefull informatios. The ip address, user and the Family tree are secondary for me since I have only on family tree.

**Comment by fisharebest** [comment]
> The probability that I have 50 trees visible to visitors is not so high, so the answer is "yes". 

I know of one site with 10000+ trees.  I am sure they would not want 10000 log entries for every search.

**Comment by Bogiegit** [comment]
Could it be a way to create a search-log option within the control panel?
It could be either a general option or valid only for a single tree.
And it got to be activated by default.
Only anonymous users (not logged in) got to be logged.
That option would enable every administrator to decide how to handle it.
I'm missing that option deeply since webtrees 2.x.
