### ISSUE TITLE
Request: repair tool for missing GIVN/SURN tags

### ISSUE THREAD

**Issue by bombaata** [fisharebest/webtrees#3845]
Hi,
When I migrated from Geneweb to Webtrees 2 a few years ago, all the names were imported with only "1 NAME" tag filled, ie "1 NAME Given Name /Surname/"

I think a repair tool to extract the SURN and GIVN from individuals who only have a "1 NAME" tag and set missing ones would be useful.

**Comment by fisharebest** [comment]
It is not possible to extract SURN and GIVN from a NAME - just as it is not possible to create a NAME from a GIVN and a SURN.

This is because names are complicated.  Some cultures use surname first, some have inflected surnames, some have zero or two surnames, etc.

The GIVN/SURN fields are optional in GEDCOM, and webtrees functions happily without them.

Even if it were possible, I'm not sure what you would gain from doing this.

**Comment by bombaata** [comment]
thanks for the info, indeed it works without these fields.

**Comment by fisharebest** [comment]
FYI, there was a lengthy discussion on this subject on the forum recently.  Search for "Nickname"...
