### ISSUE TITLE
Gedcom export validation error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3849]
ADDR lines in excess of the specification 60 chars are exported.

**Comment by hartenthaler** [comment]
Why is this a problem? There are many length restrictions in the GEDCOM standard which make no sense anymore. In the next GEDCOM standard (7.0), these restrictions will be deleted.

**Comment by ddrury** [comment]
> Why is this a problem?

As far as I'm concerned - none, but we make big play of the fact that webtrees is compliant with the standard so I'm pointing out a variation from the **current** spec

**Comment by fisharebest** [comment]
We have code for this in the `develop` branch - each GEDCOM element has a maximum length.

These are currently being used in a few places in the `main` branch.

For example, go to the demo site, log in as `editor`, and view the [`Header record`](https://dev.webtrees.net/demo-dev/tree/demo/header/HEAD/Header).

The edit menu for the page now has an "Edit" link - which edits the entire record in one form.
The text input fields all have `maxlength` attributes.  i.e. you cannot enter more than 15 characters into a "Version" field.

But what about existing data?  Perhaps imported from another application?  We need to be able to read/write this unchanged.

So we will always need to be able to write invalid data - but the webtrees UI should "encourage" you to create valid data.

I still have reserverations about this.  I'm thinking of change this from a hard-limit to a warning that appears when data is too-long or otherwise invalid.

**Comment by fisharebest** [comment]
webtrees encourages you to create valid GEDCOM.  But it can (and must) accept invalid GEDCOM.

There we must be able to export the invalid GEDCOM that we import - without losing data.

So, I think the current behaviour is correct.
