### ISSUE TITLE
Feature Request: Hide Commonly Hidden Folders

### ISSUE THREAD

**Issue by andrewgoz** [fisharebest/webtrees#3860]
app/Services/MediaFileService.php already has a function `isLegacyFolder()` that hides old folders that were used by earlier versions of webtrees.

In a similar fashion could folders that are traditionally considered hidden (at least on *nix systems) be also hidden? i.e. files and folders starting with a dot (.).

The code that works for me is:

`str_contains($path, '/.') ||`
`str_starts_with($path, '.') ||`

Could a similar thing be done to app/Http/RequestHandlers/AutoCompleteFolder.php? The following works for me:

`!str_contains($object['path'], '/.') &&`
`!str_starts_with($object['path'], '.') &&`

My reason for asking this is that my webtrees is hosted on a QNAP system, and it's media indexer (which I find useful) automatically creates dot-folders with index data and thumbnails.

There may be other places where this sort of check would be appropriate, but these are the two I've noticed to date.

**Comment by fisharebest** [comment]
Can you provide a list of folder names to hide?

**Comment by andrewgoz** [comment]
The folders created by the QNAP are ".@__thumb". I also use Adobe Bridge occasionally and that creates a file called "Thumbs.db" in each folder it is used.

**Comment by 06Games** [comment]
This feature would be very useful to me 
On Synology, a `@eaDir` folder is created inside each folder, and it contains the indexed files, suffixed with `@SynoEAStream`
The `@eaDir` folder should therefore be ignored, since it only contains system files. (As well as the `Thumbs.db` files left by Windows as mentioned in the previous comment)
