### ISSUE TITLE
Privacy restrictions access level for editors and moderators

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#3892]
It's possible to change privacy restrictions in Control panel > Manage family trees > Privacy.

The available access levels are visitors, members and managers.

Is it possible to add a access level for editors and moderators as well?

**Comment by fisharebest** [comment]
I guess this is the same question you asked on the forum:

https://www.webtrees.net/index.php/en/forum/help-for-2-0/35761-member-group-with-less-privacy-restrictions-but-w-o-edit-function

> I would like to make sources only available to a specific group of members, without making them editors/managers. Like a member+ group with less privacy restrictions but w/o edit function.

This is a very specific requirement.  As such, I think it belongs in a custom module.  In the forum post, I gave an outline of how it could be implemented.

**Comment by TheDutchJewel** [comment]
Making a custom module is one solution approach. 

But another is more differentiation in access levels. Thinking about that, I'm surprised that not all roles are available to associate with access levels. Hence my request to add the missing roles.

**Comment by fisharebest** [comment]
The access levels are based on the available values for the GEDCOM `RESN` tag.  GEDCOM only provides two values `RESN`

`RESN privacy`

> Indicate that information concerning this record is not present due to rights of or an approved request for privacy. For example, data from requested downloads of the Ancestral File may have individuals marked with ‘privacy’if they are assumed living, that is they were born within the last 110 years and there isn’t a death date. In certain cases family records may also be marked with the RESN tag of privacy if either individual acting in the role of HUSB or WIFE is assumed living.

webtrees uses this to indicate "show to members"

`RESN confidential`

> This data was marked as confidential by the user. In some systems data marked as confidential will be treated differently, for example, there might be an option that would stop confidential data from appearing on printed reports or would prevent that information from being exported.

webtrees uses this to indicate "show to managers"

We can't add more access levels because GEDCOM does not support them.

Note that webtrees has access-levels and roles.  These are different things.

Access level (visitor/member/manager) controls what you can see.

Roles (e.g. editor/moderator) controls what you can do with the data that you can see (e.g. edit, approve changes)
