### ISSUE TITLE
Use of PLAC in history modules

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3928]
Originally posted by @hartenthaler in #3924 (comment)

as discussed: should there be a possibility to add `PLAC` to history modules? Can `PLAC` be used, or is that by design not possible?

`There was one user who tried to add PLAC to the historic data records. Interesting, because many events are related not only to a date but to a location, too. But this is not foreseen by the location management of webtrees and I found no consistent way how to use this because every webtrees installation has its own location management. So we should not use `PLAC` in historic data files.`

**Comment by jon48** [comment]
Hello,

I agree with Hermann's comment: there is no standard way of recording places, so each site may have a different convention, and it is likely that the module will use a different convention than the one chosen in a specific site (even if you try to identify what is the most common naming convention, I am sure that many other will not use the same and will not be happy with having a place displayed differently from their own).

Even without getting into the lower levels, or addressing the problem of name changes in history, just at the country level, an administrator may take a different approach from another, depending on personal preferences: use one of the ISO codes for the country (e.g. ESP), use the name in one of the country's languages (e.g. España), use the English name (e.g. Spain), use the name in the site main language (e.g. Espagne if my tree is mainly dealing with French people). All those are possible, and are equally good, as long as this is the way the administrator has decided this is the standard in their tree.
As another example, and taking it from changes I can see in the PR, I could for instance argue with putting England at the top level (at least, it is not in my place hierarchy convention, I am using the sovereign country United Kingdom - which could as well be UK, or the United Kingdom of Great Britain and Northern Ireland if I wanted to be formal - and recording the home nations at the second level). This is only my choice, and other people may prefer to use England at the top, but again, neither way is wrong.

Worse (after a quick test), if the place structure or name is not in line with the site one, the historical event's place is recorded in the "geographic data" as a new place, potentially polluting the list with unwanted entries. I know some people (including me) have tried to keep that list of locations clean and updated, and may not appreciate seeing it forcefully polluted by a module.

So, whereas I appreciate the idea of localising the historical event, I fear that in the absence of a shared standard for place recording, adding the PLAC tag will more likely open a can of worms, and could refrain people from enabling the historical modules rather than encourage them to use  them.

**Comment by Lars1963** [comment]
@jon48

Hello Jonathan, thank you for your remarks. The `PLAC`-entries were IIRC only used in the existing British files. As I don't know, how was the original author, I left them in there on my overhaul of the files.

As stated by Herman and you, it would be better if I remove those entries. So if there is no argument to leave them there.

About my PR, I'll withdraw it for now and splitt it up (as @fisharebest suggested "between the lines"). It will make the discussion simpler.

**Comment by Lars1963** [comment]
`PLAC` is going to be removed in histor modules using it
