### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by Lars1963** [fisharebest/webtrees#3939]
On PR #3938 the unit test fails with error:

```
1) Fisharebest\Webtrees\EmbeddedVariablesTest::testAllEmbeddedVariables
TypeError: Return value of Fisharebest\Webtrees\Factories\FamilyFactory::Fisharebest\Webtrees\Factories\{closure}() must be an instance of Fisharebest\Webtrees\Family, null returned
```

**Comment by Lars1963** [comment]
The same on PR #3932

**Comment by fisharebest** [comment]
I am aware of this.

This particular test does two things.

1) it imports a GEDCOM file
2) it generates all the statistics.

The failure is caused by a value cached in the first part, and read in the second.

I'm not sure why this failure has recently surfaced - the test is unchanged for a long time.

But it is a problem with the tests, not the code.  You can safely ignore it.

**Comment by Lars1963** [comment]
> I'm not sure why this failure has recently surfaced - the test is unchanged for a long time.

After researching this a bit, I found this a problem with the newer versions of phpunit: Returning a value of `null` gives the `TypeError`. 

I most cases the solution seems to be changing `return null;` into `return;`. Maybe this can point you in the right direction. 

>

**Comment by fisharebest** [comment]
Merge this issue with #4026
