### ISSUE TITLE
favicon query

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#3948]
Why are the files favicon.ico and apple-touch-icon.png duplicated in both root and public while all the other resolution favicon files are only in public?

And btw why not use an svg (https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/)

**Comment by fisharebest** [comment]
Most of these "special files" are referenced from the document.  So, we tell the browser where to find them.

However, some browsers will fetch these two files without fetching a document.

Therefore they need to be in a fixed location, so that they can be found on site that do not use URL rewriting.
