### ISSUE TITLE
Beta throws report error

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#3975]
Trying to access array offset on value of type float …/app/Report/ReportPdfTextBox.php:181 #0 …/app/Report/ReportPdfTextBox.php(181): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 …/app/Report/PdfRenderer.php(123): Fisharebest\Webtrees\Report\ReportPdfTextBox-&gt;render() #2 …/app/Report/PdfRenderer.php(520): Fisharebest\Webtrees\Report\PdfRenderer-&gt;body() #3 …/app/Report/ReportParserGenerate.php(428): Fisharebest\Webtrees\Report\PdfRenderer-&gt;run() #4 …/app/Report/ReportParserGenerate.php(265): Fisharebest\Webtrees\Report\ReportParserGenerate-&gt;docEndHandler() #5 …/app/Report/ReportParserBase.php(74): Fisharebest\Webtrees\Report\ReportParserGenerate-&gt;endElement() #6 [internal function]: Fisharebest\Webtrees\Report\ReportParserBase-&gt;Fisharebest\Webtrees\Report\{closure}() #7 …/app/Report/ReportParserBase.php(92): xml_parse() #8 …/app/Report/ReportParserGenerate.php(213): Fisharebest\Webtrees\Report\ReportParserBase-&gt;__construct() #9 …/app/Http/RequestHandlers/ReportGenerate.php(132): Fisharebest\Webtrees\Report\ReportParserGenerate-&gt;__construct() #10 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ReportGenerate-&gt;handle() #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #12 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #14 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #15 …/app/Webtrees.php(239): Middleland\Dispatcher-&gt;dispatch() #16 …/app/Http/Middleware/Router.php(149): Fisharebest\Webtrees\Webtrees::dispatch() #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #18
...
...

**Comment by fisharebest** [comment]
It's been reported before, but I've not been able to reproduce it.

**Comment by jon48** [comment]
That can be reproduced for instance by running the Individual report in PDF format on Queen Elisabeth II, choosing "All" for "Show Photos" (This is required to trigger a specific part of the report): [report with error](https://dev.webtrees.net/demo-dev/tree/demo/report-run/individual_report?varnames%5B0%5D=pid&varnames%5B1%5D=sources&varnames%5B2%5D=notes&varnames%5B3%5D=photos&varnames%5B4%5D=pageSize&varnames%5B5%5D=colors&vars%5Bpid%5D=i1&vars%5Bsources%5D=on&vars%5Bnotes%5D=on&vars%5Bphotos%5D=all&vars%5BpageSize%5D=A4&vars%5Bcolors%5D=on&format=PDF&destination=view).

There is a fairly obvious code smell just looking at the incriminated lines in `ReportXXXTextbox`.

```php
$lw = $this->elements[$i]->getWidth($renderer);
$cHT += $lw[2];
```
The code does not check that `getWidth` returns an array, whereas that methods returns either an array or a float/int (and the documentation of the method explicitly refers those 2 return types.
Looking a bit further, it appears that the `ReportBaseElement`, `ReportBaseCell`, `ReportBaseImage`, `ReportBaseLine` (and other derived classes) return a number whereas `ReportXXXFootnote` and `ReportXXXText` return an array. 

The error does not appear very often because the `Textbox` element (which is the only one using the `getWidth` method) does usually contain only `Text` and `Footnote`, but for instance `individual_report.xml` contains the Textbox/Image sequence that would trigger the error:

```xml
<TextBox left="$pwidth" newline="1" pagecheck="0" padding="0" reseth="1" width="80">
  <RepeatTag tag="OBJE">
	  <Image file="@FILE" width="80" ln="N"/>
  </RepeatTag>
</TextBox>
```

The error does not appear in the Html report, because the logic is slightly more restrictive regarding the elements to display (the Image element above is silently ignored), but it is possible to trigger the same error when inserting the slightly more awkward:

**Comment by jon48** [comment]
That can be reproduced for instance by running the Individual report in PDF format on Queen Elisabeth II, choosing "All" for "Show Photos" (This is required to trigger a specific part of the report): [report with error](https://dev.webtrees.net/demo-dev/tree/demo/report-run/individual_report?varnames%5B0%5D=pid&varnames%5B1%5D=sources&varnames%5B2%5D=notes&varnames%5B3%5D=photos&varnames%5B4%5D=pageSize&varnames%5B5%5D=colors&vars%5Bpid%5D=i1&vars%5Bsources%5D=on&vars%5Bnotes%5D=on&vars%5Bphotos%5D=all&vars%5BpageSize%5D=A4&vars%5Bcolors%5D=on&format=PDF&destination=view).

There is a fairly obvious code smell just looking at the incriminated lines in `ReportXXXTextbox`.

https://github.com/fisharebest/webtrees/blob/d1da5ba430762bd82a5d57bc40552492431d11ee/app/Report/ReportPdfTextBox.php#L179-L181

The code does not check that `getWidth` returns an array, whereas that methods can return either an array or a float/int (and the documentation of the method explicitly refers those 2 return types).
Looking a bit further, it appears that the `ReportBaseElement`, `ReportBaseCell`, `ReportBaseImage`, `ReportBaseLine` (and other derived classes) return a number whereas `ReportXXXFootnote` and `ReportXXXText` return an array. 

The error does not appear very often because the `Textbox` element (which is the only one using the `getWidth` method) does usually contain only `Text` and `Footnote` elements, but for instance `individual_report.xml` contains the Textbox/Image sequence that would trigger the error (under the appropriate conditions):

https://github.com/fisharebest/webtrees/blob/d1da5ba430762bd82a5d57bc40552492431d11ee/resources/xml/reports/individual_report.xml#L138-L142

The error does not appear in the Html report, because the logic is slightly more restrictive regarding the elements to display (the Image element above is silently ignored), but it is possible to trigger the same error when inserting the arguably more awkward:
```xml
<TextBox width="100">
    <Cell style="text" width="100">
        <Now />
    </Cell>
</TextBox>
```

One way to fix could be to adjust the code in `ReportHtmlTextbox` and `ReportPdfTextbox` to check the returned type then assign the width accordingly, but I would suggest to review/rename/standardise the `getWidth` method, as I personally find quite ugly to have different return types depending on the class. Considering that the method is used only by Textbox, maybe it should always be an array, and the classes currently returning a number would return `[$width, 1, $this->getHeight()]` instead for instance.

**Comment by fisharebest** [comment]
> Considering that the method is used only by Textbox, maybe it should always be an array, and the classes currently returning a number would return [$width, 1, $this->getHeight()] instead for instance.

@jon48 - thanks for the thorough (as always) analysis.
