### ISSUE TITLE
2.1.0-dev - Close relatives events displays CLOSE_RELATIVE

### ISSUE THREAD

**Issue by jon48** [fisharebest/webtrees#3986]
I am filing the issue for reference, but it may just be due to the work in progress events refactoring.

In 2.1.0-dev, the events added for close relatives all displays the value 'CLOSE_RELATIVE'.
The `EventDescriptor` element is correctly handling the value for that case in its `value` method, but since 78fa3281a59b3821e582123be84e8aac9b13d53e, the 'INDI:EVEN' facts are handled by `CustomEvent`, which does not have the logic for the CLOSE_RELATIVE value.

![image](https://user-images.githubusercontent.com/5150782/129356837-f265b7ca-86ae-4445-830b-e2ae7e22f48f.png)

Not entirely related to that specific issue, but just throwing an idea here: what about creating a specific tag for internal use for close relatives events, that could maybe allow for more specific handling of those on-the-fly created events?

**Comment by fisharebest** [comment]
This is caused by

https://github.com/fisharebest/webtrees/blob/08b2f88/app/Elements/EventDescriptor.php#L63

and

https://github.com/fisharebest/webtrees/blob/08b2f88/app/Functions/FunctionsPrintFacts.php#L139

The element hides the special value `CLOSE_RELATIVE` - but the rest of the code expects to see it.

**Comment by fisharebest** [comment]
Actually, this is wrong.  But the use of `EventDescriptor` seems wrong too.
