### ISSUE TITLE
MySQL Password Logged on Error

### ISSUE THREAD

**Issue by KosherJava** [fisharebest/webtrees#400]
I found database ID and password logged in the error below. I believe that such data should never be logged
```
[27-Jan-2015 22:12:46 America/New_York] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /path/to/wt/library/WT/DB.php:116
Stack trace:
#0 /path/to/wt/library/WT/DB.php(116): PDO->__construct('mysql:host=loca...', 'MySQL_user_ID', 'MySQL_pass', Array)
#1 /path/to/wt/includes/session.php(357): WT_DB::createInstance('localhost', 'port_number', 'wbtrees_database', 'MySQL_user_ID', 'MySQL_pass')
#2 /path/to/wt/calendar.php(29): require('/home6/hershfe1...')
#3 {main}
  thrown in /path/to/wt/library/WT/DB.php on line 116
```

**Comment by fisharebest** [comment]
This error is being written to the log file because you have changed the PHP.INI setting of "error_log" from the default of "NULL" to a filename.

Your server is doing exactly what is asked of it.

Presumably this file is in a suitably protected folder?

These details are also stored in another file on the server (config.ini.php).

**Comment by KosherJava** [comment]
Thanks. Default of NULL means I leave it as
```error_log =```
or 
```;error_log```
or
```error_log = NULL```
thanks

**Comment by fisharebest** [comment]
Just `error_log=`
