### ISSUE TITLE
Suggestion re "My page" menu naming

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#401]
Change name of top level menu to "My pages" (plural) and possibly change dropdown menu "My page" to "My home page"

**Comment by fisharebest** [comment]
The primary menu contains both "Home page" and "My page".  Given their similarity, many users find this confusing, and I am looking at ways to simplify it.  Since these are referenced frequently in various help texts, if we're going to change them, it will require lots of text changes.

I like the suggestion of "My pages" to include "My account", "My pedigree", "My page" and "My individual page".  

What do you think of moving the current "My page" menu from the primary menu to the secondary menu?

What do you think of renaming "Home page" to "Family tree" or "Family trees", depending if there are more than one?

Where do you think the admin (Control panel) link should go?

**Comment by ddrury** [comment]
I'm struggling to come to a definitive conclusion on some of these things.

I agree with renaming Home page to Family tree(s)
at the moment my gut feel is to leave My page where it is and whilst we're at it, is it necessary to have "My account" in both primary & secondary menus

How about replacing "My account" on the secondary menu with "Control panel" and remove it from My pages

**Comment by fisharebest** [comment]
> is it necessary to have "My account" in both primary & secondary menus

The primary menu is focused on the genealogy data.
The secondary menu is focused on the user.

"My account" would clearly seem to belong in the secondary menu.

> How about replacing "My account" on the secondary menu with "Control panel" and remove it from My pages

That would make sense, for the same reasons.

> my gut feel is to leave My page where it is

Is there anything left to go under this menu - or is it now empty?

**Comment by ddrury** [comment]
Well, seeing as the "My page" block also covers account, pedigree & individual record then yes it could easily be dispensed with. Mind you when the complaints roll in, it's absolutely nothing to do with me!!

**Comment by ddrury** [comment]
The more I think about it, why not shift the entire "My Pages" menu to the secondary menu and also incorporate favourites into it (is it appropriate to have a favourites menu when not logged in?)

The secondary menu would then consist of login/logout, language, theme, my Pages

**Comment by fisharebest** [comment]
> is it appropriate to have a favourites menu when not logged in

I guess that this (like other modules that have menus) ought to be decided by the module's privacy settings - show to visitors / show to members...

**Comment by ddrury** [comment]
Yeah, thats true, but I thinking more of the relevance of whatever the admin decides are "favourites" to a casual visitor

**Comment by fisharebest** [comment]
I've just coded this to see what it looks like, and it seems much better.

One question.  In help/hint text, we have sentences such as

> ... on your "my page"

which doesn't read well.  "Your page" doesn't read well either.  Is there a clearer way to express this?

**Comment by ddrury** [comment]
Home page, Start page, Front page?

**Comment by wooc** [comment]
I like the idea of having My Page in secondary menu.

**Comment by fisharebest** [comment]
Done!
