### ISSUE TITLE
URLs in PUBL-tag/Publication and PAGE-tag/Citation details

### ISSUE THREAD

**Issue by bschwede** [fisharebest/webtrees#4021]
There is a different behaviour in handling PAGE-/PUBL-text which contains also an url:
- wt 1.7.14: only url-part is formatted as hyperlink
- wt 2.0.16: whole text is formatted as hyperlink and also used as target value, so we get an invalid link

I think the way used in version 1.x is more convenient.

**Comment by fisharebest** [comment]
This was already reported and fixed.  See #3973 and #3980

**Comment by FrankWarius** [comment]
Hi Greg

this is  slightly different in 2.1 Dev

Your fix in 2.1 formates the whole text als hyperlink with only the URL as link and solves the problem with the wrong full text as as target value.
My suggestion in #3973 just formats the url as a hyperlink and leaves the ohter text unchanged.

But i think your fix is sufficient

Thanks
Frank

**Comment by fisharebest** [comment]
> Your fix in 2.1 formates the whole text als hyperlink

No.  It only converts URLs into links.  For example

```
2 SOUR @s1@
3 PAGE foo https://example.com bar
```

<img width="410" alt="Screenshot 2021-09-02 at 14 44 13" src="https://user-images.githubusercontent.com/2306088/131854735-abab6ab8-ee6c-45a1-a774-f1d30912e5c0.png">

**Comment by FrankWarius** [comment]
You are right. (actual tested)

Sorry for that..

Regards
Frank

Von: Greg Roach ***@***.***>
Gesendet: Donnerstag, 2. September 2021 15:46
An: fisharebest/webtrees ***@***.***>
Cc: Frank Warius ***@***.***>; Comment ***@***.***>
Betreff: Re: [fisharebest/webtrees] URLs in PUBL-tag/Publication and PAGE-tag/Citation details (#4021)


Your fix in 2.1 formates the whole text als hyperlink

No. It only converts URLs into links. For example

2 SOUR @s1@

3 PAGE foo https://example.com bar

[Screenshot 2021-09-02 at 14 44 13]<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2306088%2F131854735-abab6ab8-ee6c-45a1-a774-f1d30912e5c0.png&data=04%7C01%7Cfrank%40warius.de%7Ccc817588175d4905949108d96e17feb8%7C32878959fb734fe8a460e98004e1576e%7C0%7C0%7C637661871606985035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TTXCHhLO6DrXUb7zt3cQZJUZHwTP9aHRvFQFuhyW81k%3D&reserved=0>

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffisharebest%2Fwebtrees%2Fissues%2F4021%23issuecomment-911701822&data=04%7C01%7Cfrank%40warius.de%7Ccc817588175d4905949108d96e17feb8%7C32878959fb734fe8a460e98004e1576e%7C0%7C0%7C637661871606994988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mTu5SCdRSkCIghnK%2FsmQy4cgPhC9ttWE%2FT4Mw2rIsgE%3D&reserved=0>, or unsubscribe<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD54IIHR3CN25FA4242GFE3T755ZLANCNFSM5DFABLXA&data=04%7C01%7Cfrank%40warius.de%7Ccc817588175d4905949108d96e17feb8%7C32878959fb734fe8a460e98004e1576e%7C0%7C0%7C637661871606994988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7yxFEyPILvCPDBMWCxKQCpuabgl%2FRuNzUUvEVErlpe4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfrank%40warius.de%7Ccc817588175d4905949108d96e17feb8%7C32878959fb734fe8a460e98004e1576e%7C0%7C0%7C637661871606994988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v8ofQeybwgUTvKvesth4gdQkpx03IskxSshY0verjsU%3D&reserved=0> or Android<https://deu01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfrank%40warius.de%7Ccc817588175d4905949108d96e17feb8%7C32878959fb734fe8a460e98004e1576e%7C0%7C0%7C637661871607004936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Ck7GRcoiMdRyOrQ8fp0YWz7BhQNVr3tosVkJq97M90%3D&reserved=0>.
