### ISSUE TITLE
Query re date display

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#4046]
Is there any way in code to specify that for a date containing a Gedcom modifier (eg 'between') that you want an abbreviated version? it's easy to change the day, month and year formatting characters so ultimately what is needed is to change
 `between 1 January 2021 and 1 March 2021`  to `bet 1 Jan 2021 and 1 Mar 2021`

**Comment by fisharebest** [comment]
The way you did it in https://github.com/magicsunday/webtrees-descendants-chart/issues/12 looks like the right approach.

If you decide to suppress the day numbers as well, then be aware of punctuation in the date format.  e.g. look at chinese.

You might also have problems with julian dates, as these use `CE`/`BCE` suffixes to indicate that they are julian - and are longer still.

e.g. `Between 12 January 1567 CE and 17 January 1567 CE`

**Comment by ddrury** [comment]
How about adding a parameter (say bool $short) to Date::display and then adjusting the translated text in the switch at about line 333 depending upon the value of $short

**Comment by fisharebest** [comment]
I plan to move the date formatting code to the language modules (similar to the work in progress for the relationship names).

Thus we can replace the current repeated translations with language-specific hard-coded logic.

Instead of PHP format codes, it might make sense for this new logic to have `longDate()`, `shortDate()`, etc.

A short date (or very short date?) might do things such are replace "between x and y" with "x-y", etc.
