### ISSUE TITLE
Pedigree tree module base individual is not connected to its family tree

### ISSUE THREAD

**Issue by ardhtu** [fisharebest/webtrees#4051]
I have two family trees in my webtrees installation.
I have set up a pedigree tree module in in front pages of of both family trees. There is only one parameter to set up the module, the base person. When I change the base person in one tree's module also the other tree's base person in that module changes probably to the same index number.
It looks like the base person for that module is not saved into the database with information into which tree it belongs to.

- Hannu

**Comment by fisharebest** [comment]
> I have set up a pedigree tree module in in front pages of of both family trees.

You have added it to your "user" home page - not to the "tree" home pages.

If you add it to the trees's home pages, then you will have two copies of the block, and two copies of the configuration settings.

I guess this block should not be allowed on "user" pages.

**Comment by JustCarmen** [comment]
> I guess this block should not be allowed on "user" pages.

I don't agree. As the my-page is the starting point for each member of a tree (they are redirected to that page after login and not redirected to the homepage), I think this block certainly belongs there, because it is the only block on the page that give them a quick insight in the connections between individuals and is very handy for newbies who can get lost easily in the jumble of data on a webtrees website.

Why not make a distinction in the database between userpage blocks and tree blocks?
