### ISSUE TITLE
Module administration

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#413]
Would it be an idea to split the module administration into two collapsable panels with the core modules in one panel and the custom modules in the other?

In this way it is easy for administators to see if a module is part of the webtrees core or not and it makes the list shorter and easier to view.

**Comment by fisharebest** [comment]
That is a good idea - it would be good to have some way to distinguish core from custom modules.

Perhaps we can also extend the module interface so that the module can provide a link to its author or home page?

I am thinking of changing the way we load custom modules.  Perhaps to make it similar to the Themes, where the module.php file returns a Module object.

Originally (in version 1.0.0), we planned for themes to be modules.

If we combined them, it might be easier for themes that also have configuration options.

**Comment by JustCarmen** [comment]
>>Perhaps we can also extend the module interface so that the module can provide a link to its author or home page?

Yes, I would like that. Something like Wordpress?
![1-2-2015 14-28-55](https://cloud.githubusercontent.com/assets/5641963/5992194/db239972-aa1e-11e4-8f6e-afe575f77dd4.jpg)

>>If we combined them, it might be easier for themes that also have configuration options.
Also a good idea. Both of my themes comes with a module to set some configuration options.
If this could be combined that would make it easier for users to upgrade.

**Comment by vytux-com** [comment]
I like both of those ideas too :-) looking forward to this feature

**Comment by fisharebest** [comment]
webtrees (like most modern PHP applications) uses `composer` to load its dependencies.

I wonder if there is a way to use composer to load third-party modules and themes?

This might be able to handle all the version compatibility and upgrade for us?

**Comment by JustCarmen** [comment]
That is beyond my knowledge but it sounds great.

**Comment by Art4** [comment]
I found this (a little outdated) composer wrapper. It can be used to execute composer commands inside a script. Maybe this will be a good start.

https://github.com/eviweb/composer-wrapper

**Comment by fisharebest** [comment]
I am finding it difficult to create a system that allows the module API to be updated without causing fatal errors in "old" modules.

There is a simple/obvious solution (PHP traits).  But this requires PHP5.4.

**Comment by Amgine0** [comment]
http://php.net/supported-versions.php

5.4 is on security fix only life support for another 6 months.

**Comment by vytux-com** [comment]
I would not mind moving webtrees to support later PHP versions, however I do know that there are still a lot of users out there that are on free or very cheap shared servers and some of those are still running 5.2 never mind anything recent/supported.

I guess it will have to be a decision that the webtrees dev team (being Greg) will have to decide on.

**Comment by Art4** [comment]
I would suggest to drop PHP 5.3 support because ist EOL and isn't on Security Support. One reason why other php libraries only support 5.4+ is a try to force the hosts to adopt newer php versions. I'd be glad if webtrees supports this try. Read more in this post from Anthony Ferrara http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

I've taked a look at the statistics: https://dev.webtrees.net/statistics.html 41% Servers are using PHP <= 5.3 and will be affected if you switch to PHP 5.4. 

But: There are 19% on Webtrees <= 1.4.6 and these must be instances with PHP 5.2 because they cannot or wont upgrade webtrees. Maybe this are a lot of "dead" instances witch aren't in use anymore. We don't know but in fact they wouldn't be affected if you switch to PHP 5.4 because they were allready affected by the switch to PHP 5.3.

However, if you subtract these instances: 41% - 19% = 22%. Only 22% instances couldn't update to the last webtrees version.

Is there a release date for webtrees 1.7? Maybe you can warn the users month before the release date that PHP 5.3 support will be dropped soon and they should update to PHP 5.6

**Comment by fisharebest** [comment]
> Read more in this post from Anthony Ferrara

I have seen it, and agree with everything it says ;-)

We have had similar discussions before - when we dropped support for PHP4 and again for PHP5.2.

In both cases, people were angry that they could not upgrade.  But they were not angy with their hosts, they were angry with the project :-(

> look at the statistics

I can filter the data by webtrees version.
For webtrees 1.4.x there are 64% using PHP5.3 or PHP5.2.
For webtrees 1.5.x there are 45% using PHP5.3.
For webtrees 1.6.x there are 35% using PHP5.3.
For webtrees 1.6.2, there are 32% using PHP5.3.

> Is there a release date for webtrees 1.7?

Perhaps end of April?

**Comment by Amgine0** [comment]
Like PHP itself, you can maintain security updates for a 5.3-compatible version. But do it for a prescribed period of time.

Or shift to a framework which makes the decision for you, and direct the complaints upstream.

(...says the lazy self-hoster who generally has to be dragged kicking and screaming into upgrade cycles.)

**Comment by fisharebest** [comment]
I have updated https://dev.webtrees.net/statistics.html to show statistics for the latest version of webtrees.

**Comment by fisharebest** [comment]
Custom modules are now identified on the module administration page.

A custom module can also set two constants `CUSTOM_VERSION` and `CUSTOM_WEBSITE`.  This information is also shown.
