### ISSUE TITLE
Request: add minister as relationship

### ISSUE THREAD

**Issue by TheDutchJewel** [fisharebest/webtrees#4132]
In [appElementsRelationIsDescriptor.php](https://github.com/fisharebest/webtrees/blob/cc4c83a826365b2c6c1f20f9c23ab588f402f280/app/Elements/RelationIsDescriptor.php#L120) there are two types of clergy (**priest** and **rabbi**), but no [minister](https://en.wikipedia.org/wiki/Minister_(Christianity)).

Is it possible to add **minister** as relationship?

**Comment by Norwegian-Sardines** [comment]
I'm not against adding additional relationship types, but the list could get rather lengthy.  If you have priest and want to add minister, we should add "pastor" as well.  If we have Rabbi, we should add "Kohen" and what about "Imam", "Shaman", "Bhikkhu" and I'm sure more exist!  

As this relates to the ASSO.RELA tag and that these terms are also translated to other languages, some form of "User Defined Value" with translation options could also be implemented as a long term solution.

**Comment by TheDutchJewel** [comment]
My request relates to the **CHR**istening and **MARR**riage facts.

In the Christian church these Christian sacraments are ministered/performed by the minister.

**Comment by mpwt** [comment]
For custom terms, I put them in the English spelling myself in the quoted file and translated them with a custom translation module. Due to the almost unlimited variety of designations, this is probably the easier (and faster) solution.

**Comment by TheDutchJewel** [comment]
Adding it to webtrees ensures that all users can make use of it without having to work with a translation module themselves.

For myself, an alternative to manually editing the file [appElementsRelationIsDescriptor.php](https://github.com/fisharebest/webtrees/blob/cc4c83a826365b2c6c1f20f9c23ab588f402f280/app/Elements/RelationIsDescriptor.php#L120 ) might be to use a module to extend the terms.

Is that possible? If so, how does that work?

**Comment by fisharebest** [comment]
We already have a problem where two items in English have the same translation in other languages - e.g. CHR and BAPM.

I think that Minister and Priest might cause the same problem.

I don't know the difference between these words, so I searched on google.  I still don't know the difference.
Bu tI found a non-English-speaker asking the difference, because the two words have the same translation in their own language.

https://www.christianforums.com/threads/difference-between-priest-and-a-minister.7851133/

> "Priest" and "minister" translates roughly as the same word in my language, but looking at the large variety of Christian "ministers" or "ministries" over the web as they call themselves (though I do doubt the authenticity of some) in English, it leaves me with some confusion.
> So, when we speak in English, what's the difference between a priest and a minister? 

So, I don't think we should add this.

> Is that possible? If so, how does that work?

It is straightforward.

1) extend the existing `RelationIsDescriptor` class and add your own extra definitions
2) create a module which implements `CustomTagsInterface`
3) add a `customTags()` method which registers your new class in place of the old class.

If I find time, I will create an example

**Comment by TheDutchJewel** [comment]
>I don't know the difference between these words

One important difference is that the term 'priest' is not used in [Protestantism](https://en.wikipedia.org/wiki/Religion_in_the_Netherlands#Protestantism), unlike, for example, [Catholicism](https://en.wikipedia.org/wiki/Religion_in_the_Netherlands#Catholicism).

>If I find time, I will create an example

Thank You!
