### ISSUE TITLE
Note Formatting Broken by v2.0.17

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#4136]
Versions 2.0.17 through 2.0.19 do not correctly display any linefeeds in any notes unless they are double linefeeds or unordered lists, making notes ugly and very difficult to read.  This is a significant regression for my website.  Previously reported as #4114

**Comment by ric2016** [comment]
Note that this occurs even if markdown is disabled, [as shown here](https://www.webtrees.net/index.php/en/forum/help-for-2-0/36316-note-cont-missing-line-breaks-2-0-19?start=20#88569).

**Comment by fisharebest** [comment]
67721f6fe545e33878bd31b73a960fe472601f42 adds a new config option - "markdown with line breaks"

**Comment by miqrogroove** [comment]
Was this never ported to 2.0?  I just tried upgrading to v 2.0.23 and it looks like nothing changed at all.

**Comment by fisharebest** [comment]
> Was this never ported to 2.0?

2.0 and 2.1 use different markdown libraries.
2.0 uses CSS for line-breaks
2.1 uses HTML for line-breaks

Completely different designs and code.  Back-porting is not possible.

**Comment by miqrogroove** [comment]
In case there is any confusion about my forum post, this issue was never resolved and should still be open.

**Comment by ric2016** [comment]
This isn't productive. It's not helpful to post in lots of different threads and closed issues about non-current webtrees versions. 

Please create a new issue IF there is still a bug in the 2.1 version, and describe exactly what still doesn't work. Older versions aren't relevant any more.

**Comment by miqrogroove** [comment]
Yes, please treat me as though I'm the cause of the problem when I try to communicate with you.  That's very mature.

**Comment by glarwill** [comment]
Have you tried 2.1 to see if the issue has already been resolved?

**Comment by miqrogroove** [comment]
I made an attempt this morning but the plugins aren't compatible yet.  Currently the only option is to run v2.0.16.

**Comment by ric2016** [comment]
Well then what exactly do you expect to happen here?

We know there are bugs in 2.0.x. They have been resolved in 2.1. So why do you claim "this issue was never resolved"?

Greg told you the fixes from 2.1 won't be back-ported (and this is very sensible: We cannot continue to provide 2.0.x releases until some unknown point when all custom modules are ready for 2.1). 

So why should this issue "still be open"? .

**Comment by miqrogroove** [comment]
The hostility here is remarkable.  I have one person telling me I never opened a ticket and another getting angry that I opened a ticket in the first place?

Can we come to some kind of more professional conclusion here such as: Notes are broken by v2.0.17 and will not be fixed in any v2.0 branch release?  It's much easier for me to work with a "wontfix" answer than reading angry replies to my bug reports.  With that, I would be able to patiently ignore the 2.0 branch updates and look forward to upgrading with 2.1 in the near future.

**Comment by fisharebest** [comment]
OK - here is what I want.

A bug report against the lastest code. If you post a bug report against 2.0.17, I will almost certainly ignore it, as the code has changed many times since then.  I don't care that there was a bug in an old version.

If you simply say "Notes are broken", I have nothing to go on.

If you say "version x is different to version y", then I need to install two version side-by-side and try to reverse engineer the differences.  This is quite time-consuming, especially that this is a feature I do not use myself.

If I have 20 minutes to work on webtrees, and it takes 20 minutes to read a long thread before I can set up a reproducable test case, then I'll spend the 20 minutes somewhere that I can be more productive.

Help me to help you.  Spend a little time going through the various combinations (markdown / text), line-breaks within and between paragraphs or other blocks.   With/without trailing double-spaces, etc.

If you invest time/effort in a well-written bug-report, then I'll invest the time/effort in trying to fix it.
