### ISSUE TITLE
Sorting by date fails in "On this day" block.

### ISSUE THREAD

**Issue by WGroleau** [fisharebest/webtrees#4155]
I clicked on the sorting icon in the date column of "On this day" and did not get a logical sequence.  After experimenting a little, I realized that when I clicked other sorting icons, the order changed, but when I click that one, nothing happens to the data.  The sorting icon highlights, but the data does not change.  the image shows the mixed up order right after clicking the sort.

Also, having the control at the right edge of the column isn't really user-friendly—it made me think it was for sorting the next column over. After a couple of tries, I realized my misinterpretation. I would suggest putting the control immediately before the column heading
![temp](https://user-images.githubusercontent.com/5910274/147868107-71b15942-2647-466e-b327-440231e97646.jpg)
.

**Comment by fisharebest** [comment]
This anniversary table is used for both "on this day" and "upcoming events".

The sort-key for the date column is the anniversary event (not the event date).

For "on-this-day", it makes no sense, as every event has the same anniversary (i.e. today).

I have added a secondary sort column, so that it sorts by anniversary date first, and then event date second.

**Comment by WGroleau** [comment]
Well, without the new column, the number of years column can be used to get the result I was expecting with the date column.  But I'm not sure it makes sense for the sort an a column to not use what the column displays.
