### ISSUE TITLE
Sorting of facts with only "FROM" or "TO"

### ISSUE THREAD

**Issue by ekdahl** [fisharebest/webtrees#4156]
A common situation for me is that I find fact about when a person moved from one place to another.
Then I create one residence with date like "TO 27 NOV 1905" as it is still unknown when the person moved there.
I also add another residence with date like "FROM 27 NOV 1905".
When displayed the sorting is not in chronological order (considering that the times are start and end of periods of time), see image below.
![image](https://user-images.githubusercontent.com/2682230/148041401-bc8696e9-7bbc-4dab-84cc-f1ac0da35b79.png)
Version 2.0.19

**Comment by fisharebest** [comment]
The sort algorithm says that if two dates overlap, then they sort equally.

These two dates overlap (both include `27 NOV 1905`), so they are treated as the same.

When you have the same type of fact (residence) and the same date, then webtrees keeps the facts in the original order.

So, to change the order, you should use the "Edit raw GEDCOM" option, and drag/drop these two facts into your prefered order.

**Comment by fisharebest** [comment]
That doesn't work because sorting algorithms require a [transitive](https://en.wikipedia.org/wiki/Transitive_relation) comparison function.  e.g.

`a = b` and `b = c` implies `a = c`
`a <= b` and `b <= c` implies `a <= c`
`a < b` and `b < c` implies `a < c`

The current logic (overlapping dates are equal) satisfies this requirement.

Adding additional logic breaks this requirement - especially when other overalapping dates are included.  For example, adding `1904-1906` to the above two dates.

**Comment by ekdahl** [comment]
When I thought about a "workaround", I was more thinking like this (I know it is a dirty hack):
If the timestamp is an ending of a time period, remove a millisecond (or whatever tiny time unit) before sending it to the sorting method.
That way the sorting algorithm is untouched, but the ending time is "upvoted" a tiny bit.

Anyway, it's not a big issue, and now I have the workaround with manually moving the facts. I will close the issue now.
