### ISSUE TITLE
Layout issue when using the interactive tree tab on the individual page

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#4365]
When clicking on the interactive tree tab the chart takes the whole width of the page, pushing the sidebar below the tabs.

I think the solution is to put a fixed width column on the right side as in wt-2.0 (col-sm-8, because the sidebar grid is col-sm-4).

https://dev.webtrees.net/demo-dev/tree/demo/individual/X9287/Princess-Alexandra-of-Saxe-Altenburg#tab-tree

**Comment by fisharebest** [comment]
We use `col` instead of `col-sm-8` because the sidebar is optional.
(We do the same for the image/names, as the image is optional.)

But I think you are right, we need `col-sm-8` (or `col-sm-12`) here.  The content includes a table, which will expand to fill its content, unless the parent element has a fixed width.
