### ISSUE TITLE
Data fix to capitalize media type / form

### ISSUE THREAD

**Issue by SnarfW** [fisharebest/webtrees#4368]
Since 2.1.1 the use of capitals for media types (document/photo) and media form (jpg/mp4) is encourage and even reported as an error. Will a future edition of Webtrees include a data fix routine to correct these "errors"?

**Comment by fisharebest** [comment]
> Will a future edition of Webtrees include a data fix routine to correct these "errors"?

They are not errors - just "information".

There will be something.  I haven't decided what.  

I would prefer to automatically fix these things when importing a GEDCOM file, so that we know the data in the database will always be consistent.  But I know that some people will get very upset if webtrees modifies their data...
