### ISSUE TITLE
MARR_CIVIL, MARR_RELIGIOUS, MARR_PARTNERS, MARR_UNKNOWN

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#4434]
Some applications create `FAM:MARR_CIVIL`, `FAM:MARR_RELIGIOUS`, `FAM:MARR_PARTNERS` and `FAM:MARR_UNKNOWN` tags.

Older versions of webtree supported these (by converting to MARR/TYPE xxxx ??).

This logic has been lost in 2.1.

Need to find out which application(s) create these tags.

Also, it seems that RootsMagic can create `1 MARR Civil` and `1 MARR Religious`.

**Comment by fisharebest** [comment]
Also, need to decide how to handle these tags when a `TYPE` already exists.  e.g. `1 MARR_PARTNERS / 2 TYPE PACS`.

Perhaps convert the `TYPE` to `NOTE`?

```
1 MARR
2 TYPE partners
2 NOTE PACS
```

**Comment by Norwegian-Sardines** [comment]
My understanding of P.A.C.S. is that it is a "Civil Union" authorized by the French government.  This would be different than a "partner" where the government does not provide a legal document to sign (possibly like a "civil marriage") so rather than "TYPE partners" this becomes either a "TYPE civil" or "TYPE PACS".  I'm not sure specifics but it seams to me that PACS is "on par" with Civil rather than to a lesser position.

Reading about the union it seams to me that PACS is sanctioned by the government granting specific legal rights (tax, rental contracts, time off) but not inheritance rights, which for me a "partner" is not government sanctioned and carries less rights.
