### ISSUE TITLE
Some plural translations doesn't shown on Turkish

### ISSUE THREAD

**Issue by ekremparlak** [fisharebest/webtrees#4502]
Version: 2.1.6

"Top %s given names"  and "Top %s surnames" shown as English if its plural
"Changes in the last %s days" doesn't work even if its only 1 days
![image](https://user-images.githubusercontent.com/6561198/177017058-7e8d5d16-0304-48c3-8bbb-0e5fb0fcc294.png)
![image](https://user-images.githubusercontent.com/6561198/177017063-7c75363f-d762-4324-925e-f2acc7c09a4a.png)
![image](https://user-images.githubusercontent.com/6561198/177017075-e711da77-e620-49c5-bbf3-e9b9b73c3e8d.png)
![image](https://user-images.githubusercontent.com/6561198/177017086-d21c10a9-b4f1-43e1-b397-a0866d248d1e.png)
This also happens with new install
When i look at the messages.php file i can see the translations.
When i change these lines to something else nothing happens. Like i change 
````
'Top %s given name' . "\0" . 'Top %s given names' => 'En çok %s verilen ad' . "\0" . 'En çok %s verilen adlar',
````
to
````
'Top %s given name' . "\0" . 'Top %s given names' => 'Les %s prénoms les plus fréquents' . "\0" . 'Les %s prénoms les plus populaires',
````
but webtrees still use English for that line

**Comment by fisharebest** [comment]
The translation library in webtrrees is based on the CLDR project.

There was a bug in an old version of this which says that Turkish does not use plurals.

So, none of the plural translations will work.

This bug has been fixed in the latest version of the CLDR.  So I need to update the [translation library](https://github.com/fisharebest/localization)
