### ISSUE TITLE
NAME:ROMN - TYPE is mandatory

### ISSUE THREAD

**Issue by hartenthaler** [fisharebest/webtrees#4656]
GEDCOM 5.5.1 says

> PERSONAL_NAME_STRUCTURE:=
> n NAME <NAME_PERSONAL> {1:1} 
> +1 TYPE <NAME_TYPE> {0:1} 
> +1 <<PERSONAL_NAME_PIECES>> {0:1} 
> +1 FONE <NAME_PHONETIC_VARIATION> {0:M} 
> +2 TYPE <PHONETIC_TYPE> {1:1} 
> +2 <<PERSONAL_NAME_PIECES>> {0:1} 
> +1 ROMN <NAME_ROMANIZED_VARIATION> {0:M} 
> +2 TYPE <ROMANIZED_TYPE> {1:1} 
> +2 <<PERSONAL_NAME_PIECES>> {0:1}

webtrees accepts NAME:ROMN without the mandatory subtag TYPE. 

There is no drop-down in webtrees when entering the TYPE. GEDCOM says:

> ROMANIZED_TYPE:= {Size=5:30}
>  [user defined | pinyin | romaji | wadegiles]
> Indicates the method used in transforming the text to a romanized variation.

Besides the named Chinese romanization types, there are additional user-defined types allowed. I'm using "ELOT 743" as a type for the romanization of modern greek.

**Comment by fisharebest** [comment]
> webtrees accepts NAME:ROMN without the mandatory subtag TYPE.

We must be able to accept invalid data.  Otherwise we could not import most GEDCOM files!

If we can import data without a TYPE, then we need to be able to create it.

> There is no drop-down in webtrees when entering the TYPE.

It is difficult to create a drop-down that also allows "other" values.

I could create a drop-down - and also allow add `ELOT 743` to the list...
