### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by ThomasKujawa** [fisharebest/webtrees#4675]
It would be good if the Google Fonts are integrated locally in the future. Reason: DSGVO / GDPR

**Comment by fisharebest** [comment]
Google fonts are part of Google charts, and we already plan to replace the charts with a non-google alternative.

To avoid Google tracking on your site, you can

1) disable the module "Statistics charts"
2) do not use embedded charts in HTML blocks.

This issue is covered by #3883. You can add other comments there.
