### ISSUE TITLE
Google Maps not working

### ISSUE THREAD

**Issue by andrewgoz** [fisharebest/webtrees#4702]
https://github.com/fisharebest/webtrees/blob/4088d8d3a616e1b30a663cd261932bb6c6b9b188/public/js/webtrees.min.js

If I knew where to find the non-minimized version, I would have reported against that.

Search for the text "t.mapProviders[0].children[0].layer". That expression should be assigned to "i", so the code looks like

`i=t.mapProviders[0].children[0].layer`

**Comment by andrewgoz** [comment]
Found it! Unwanted "let".

https://github.com/fisharebest/webtrees/blob/4088d8d3a616e1b30a663cd261932bb6c6b9b188/resources/js/webtrees.js#L736

**Comment by ddrury** [comment]
Andrew,
Whilst you are correct in removing the variable definition from the defaultLayer (defaultLayer is already defined earlier) The actual problem is caused by disabling the "OpenStreetMap"`provider in the Control panel - Modules - Map providers page.

@fisharebest the default layer code needs rethinking here. As we can now disable any of the map providers (If they are all disabled then we now throw an error) I think we either need to prevent disabling OpenStreetMap or always default to provider[0], layer[0].

BTW My PR https://github.com/fisharebest/webtrees/pull/4165 may be a partial solution (although at present it still has code for default layer)

**Comment by ddrury** [comment]
Thinking about this further, I think that implementing my PR https://github.com/fisharebest/webtrees/pull/4165 and doing away with the default layer code (always default to provider[0], layer[0]) is the best way to go.

BTW Andrew's PR https://github.com/fisharebest/webtrees/pull/4703 fixes a syntax error so is essential

**Comment by fisharebest** [comment]
@andrewgoz - thanks for the fix

@ddrury - could you add a description to #4165 explaining the issue being fixed.  i.e. how would I reproduce the problem, so that I could test the fix...
