### ISSUE TITLE
Need php 7.4 minium for version 1.7

### ISSUE THREAD

**Issue by Light-Wizzard** [fisharebest/webtrees#4856]
Virtualmin does not support 7.3 due to end-of-life.

Importing PhpGedView.

**Comment by LarsRabe** [comment]
See https://webtrees.net/install/requirements/
1.7 has also EOL-Status

**Comment by Light-Wizzard** [comment]
Maybe add the PhpGedView import to 2.x.

**Comment by arbor95** [comment]
No capacity.
Use a gedcom file.
Do the rest by hand.

**Comment by LarsRabe** [comment]
@Light-Wizzard 
Als stated by Greg: "_Webtrees version 1.7.20 was released  June 2022. It runs on PHP 5.3 - 7.3. This is the final release of webtrees 1.7. _"

It cannot be his concern that you waited so long with upgrading to the newer Version of webtrees. So now do it manually or use a older local LAMP-package to do the Import and upgrade.

**Comment by fisharebest** [comment]
> Virtualmin does not support 7.3 due to end-of-life.

webtrees 2.x does not support 7.3 due to end-of-life :-)

1) MAKE A BACKUP OF YOUR FILES AND DATABASE BEFORE YOU DO ANYTHING ELSE
2) MAKE SURE YOU CAN RESTORE FROM THIS BACKUP.

Many features in webtrees 1.7 do not run with PHP 7.4.  For example, the edit tools can silently corrupt your data.
However, you do not need all the features. You only need the migration tool.

So, try it with PHP 7.4.  It *might* work
If it does, then as soon as the migration is complete, upgrade to 2.x
But if it doesn't, then you have a backup.

You have other options.  Install a local web-server (e.g. XAMPP) that provides PHP 7.3 and move your files/database there to run the migration.

Or, follow the advice of @arbor95 - create a new installation of webtrees 2.x and import the GEDCOM file from PhpGedView.

If you don't have a GEDCOM file, then you'll need to extract the GEDCOM records from the various PhpGedView tables, and concatenate them to make a GEDCOM file.

> Maybe add the PhpGedView import to 2.x.

Sorry this would require disproportionate effort:

* The wizard needs to call many library functions which were the same/similar in PhpGedView/webtrees 1.7.  These library functions no longer exist in webtrees 2.x

* The PhpGedView configuration file was a PHP script, which won't run with the latest versions of PHP due to changes in the language.

This is why it was removed in 2.0
