### ISSUE TITLE
Custom module folders can only be named 30 characters or less

### ISSUE THREAD

**Issue by JesseWebDotCom** [fisharebest/webtrees#4857]
I noticed that if my custom module folder name is more than 30 characters, webtrees ignores it.

**Comment by fisharebest** [comment]
This is intentional.  (Sorry - I replied in the forum before seeing you had created this issue.)

The `module_name` column in the database is 32 characters long.

To prevent name-conflicts between core and custom modules, we add `_` before/after a custom module name.

e.g. `my-custom-module` becomes `_my-custom-module_`.
