### ISSUE TITLE
Fixes: #4948 - Update ckeditor-js.phtml extraAllowedContent (#4949) in 2.1.19?

### ISSUE THREAD

**Issue by photon-flip** [fisharebest/webtrees#4965]
Fixes: #4948 - Update ckeditor-js.phtml extraAllowedContent (#4949) doesn't seem to have made it to 2.1.19
Was I wrong in expecting that?

**Comment by fisharebest** [comment]
Fixes are applied to the main development branch (which will become webtrees 2.2).

Where applicable they are also back-ported into the 2.1 branch.

But it looks like I forgot to back-port this change.  Probably because it came via a PR, instead of my normal workflow.  Sorry!

I just copied it over to the 2.1 branch.  It will be in the next release.
