### ISSUE TITLE
Image files truncated

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#5042]
Latest dev version.
Photos on individual page are truncated.  If you log in you see the full picture
![image](https://github.com/user-attachments/assets/b0831781-6a4d-4eb0-95cb-1769ed4dbfaf)

![image](https://github.com/user-attachments/assets/eb5c2db2-1ac3-4276-a98a-b1ecf092f02c)

**Comment by fisharebest** [comment]
That will be the new version of the `intervention/image` library.

**Comment by FrankWarius** [comment]
Workaround:
Change in ImageFactory function mediaFileThumbnailResponse line 201

from `$watermark = $this->createWatermark(width: $image->width(), height: $image->height(), media_file: $media_file);`
 to     `$watermark = $this->createWatermark(width: $width, height: $height, media_file: $media_file);`

$image->width returns in this example 113 the value of the watermark and not the intended value 200 of the thumbnail

**Comment by FrankWarius** [comment]
Fix:
use function **scale** instead of **contain** for scaling the watermark
see scale https://image.intervention.io/v3/modifying/resizing#resizing-images-proportionally 
vs. contain https://image.intervention.io/v3/modifying/resizing#padded-resizing-with-upscaling

Change  ImageFactory function createWatermark line 255

`          ->scale(width: $width, height: $height);`

**Comment by fisharebest** [comment]
> Change in ImageFactory function mediaFileThumbnailResponse line 201

I don't think this is the answer.

If an image is 300x600, and we are creating a thumbnail to fit inside 100x100, then we will have an image 50x100.

The width of the watermark needs to be 50 (`$image->width()`), not 100 (`$width`).

I think the issue lies at line 263:

```php
return $image->place(element: $watermark, position:  'center');
```

This function takes another parameter "opacity".  Here's the result with values of 0, 25, 50, 75 and 100 (default):

![opacity-0](https://github.com/user-attachments/assets/4c00245d-41ab-4454-9865-69ce2cfdfdff) ![opacity-25](https://github.com/user-attachments/assets/488e868a-1b21-4c35-b6e4-b62e66b65f96) ![opacity-50](https://github.com/user-attachments/assets/7d6ab875-cdd1-4c33-a798-9cb3586edd9e) ![opacity-75](https://github.com/user-attachments/assets/d8fec3ee-1ec4-4a88-809c-80594920b722) ![opacity-100](https://github.com/user-attachments/assets/dcf10522-9cf1-496f-b895-148565894e2e)

I guess this function isn't doing what I expect...

**Comment by fisharebest** [comment]
Aha!  We are creating the watermark incorrectly....

**Comment by fisharebest** [comment]
@FrankWarius - I only saw your second comment after I had come to the same conclusion.  I could have saved an hour... :-)
