### ISSUE TITLE
Relationships Chart Module Settings are Broken

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#5064]
Steps to Reproduce:

1. Navigate to `/module/relationships_chart/Admin`
2. Change the Relationships selection to "Find relationships via ancestors".
3. Click Save.
4. Try using the Relationships chart.

Expected result:

Chart should default to "Find relationships via ancestors."

Actual result:

The relationship scope selector is missing, and the chart still defaults to finding any relationships.

Using v2.1.20

**Comment by raaspt** [comment]
I'm using v2.1.21 and the search works as expected when "Find relationships via ancestors" is set in the module options.

The relationships scope selector is missing with such setting for me as well, but it could be that it's working as expected by design, meaning that if an admin is restricting search via module configuration then a user must not be able to select a broader scope of search.

**Comment by fisharebest** [comment]
> The relationships scope selector is missing with such setting for me as well, but it could be that it's working as expected by design

This is correct.

These calculations can use a lot of resources.  On large trees / small servers, it may be necessary to restrict this function so that it can return results.

> suggest to add a note

With this configuration, the chart tells users that it is only looking for relationships via ancestors.

I'm not sure what we could say in a note.  To me, it all seems very clear(!)

Suggestions..?

**Comment by miqrogroove** [comment]
> These calculations can use a lot of resources. On large trees / small servers, it may be necessary to restrict this function so that it can return results.

We are getting off topic here.  My original report was for the chart displaying "any relationship" regardless of this setting.  This setting doesn't restrict anything for me.

I will gather more details.

**Comment by miqrogroove** [comment]
My test case is individual `X4572` on my personal server.

Config 1:

- `/module/relationships_chart/Admin`
  - Relationships: Find any relationship
  - Recursion: 1
- The "relationship to me" link points to `/tree/tree1/relationships-0-99/I1/X4572`
- If I click the "view" on the chart to refresh it, the address changes to `/tree/tree1/relationships-0-1/I1/X4572`
- Both of those addresses show me 2 relationship charts
  - "second cousin three times removed ascending"
  - "great-great-great-uncle’s sister-in-law’s first cousin once removed descending"
- Selecting "Find relationships via ancestors" on the chart page and clicking "view" changes the address to `/tree/tree1/relationships-1-1/I1/X4572` 
  - This page shows only 1 relationship chart for the 2nd cousin relationship.

Config 2:

- `/module/relationships_chart/Admin`
  - Relationships: Find relationships via ancestors
  - Recursion: 1
- The "relationship to me" link points to `/tree/tree1/relationships-0-99/I1/X4572`
- If I click the "view" on the chart to refresh it, the address changes to `/tree/tree1/relationships-1-1/I1/X4572`
- These charts correspond to the 2 _different_ chart selectors described above.
- `0-99`, the default chart, shows 2 relationships.
- `1-1`, the refreshed chart, shows 1 relationship.
- So, by default, the module configuration has no effect unless the user first views the wrong chart, then attempts to refresh it using the "view" button.

**Comment by fisharebest** [comment]
> The "relationship to me" link points to `/tree/tree1/relationships-0-99/I1/X4572`

Ah, so the "chart URL" link is using the default parameters, not the configured parameters.
