### ISSUE TITLE
Relationship chart in clouds theme - white background

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#539]
We should not see in the chart in clouds theme the relationship texts and the arrows with a white background.

**Comment by makitso** [comment]
Background color being set in php.  Greg,  want this to be handled in css?

**Comment by JustCarmen** [comment]
Also see: https://github.com/fisharebest/webtrees/issues/443

**Comment by makitso** [comment]
Removing the style from relationship.php and add a class would work?

**Comment by fisharebest** [comment]
We currently use background-image to display icons.

This is bad for lots of reasons.  One is this - what happens when there is an actual background.

The other is that it is bad for accessibility.  For example, Windows high-contrast mode does not display background images.

An alternative option is to replace `background-image` with `:after {content: ...}`

It's on my list to do this with all the current icons...

**Comment by fisharebest** [comment]
This works for the bottom of the page - but not for the top, where the background colour is different.

![untitled](https://cloud.githubusercontent.com/assets/2306088/7002067/69af671c-dc3c-11e4-934f-8d0279f69ee5.png)

**Comment by fisharebest** [comment]
Perhaps we simply need to move the text/arrow so that it does not overlap the line?

**Comment by fisharebest** [comment]
Perhaps this?

![untitled](https://cloud.githubusercontent.com/assets/2306088/7002334/f3506c6a-dc40-11e4-82a2-29c186bf59b9.png)

**Comment by fisharebest** [comment]
Another thought.  Do we actually need the arrows?

**Comment by makitso** [comment]
Personally, I like the arrows.  I would vote for your last example.

**Comment by fisharebest** [comment]
> I like the arrows. I would vote for your last example.

OK - done!
