### ISSUE TITLE
Minor issue: Ex-husbands wife is displayed as 'husband’s wife'

### ISSUE THREAD

**Issue by oogoofeo** [fisharebest/webtrees#568]
Hi!

Ex-husbands wife is displayed as 'husband’s wife' and vice versa. It should read 'ex-husband’s wife' .

**Comment by fisharebest** [comment]
For immediate relationships, we handle special cases such as "twin-brother", "ex-wife", "partner", etc.

For relationships involving multiple steps, we don't, because it would be too difficult to translate.

To handle the cases like "ex-husband's wife", "husband's ex-wife", etc., we would need

first person: male/female/unknown
relationship: marriage, unmarried, divorced
second person: male/female/unknown
relationship: marriage, unmarried, divorced
third person: male/female/unknown

This would require 3x3x3x3x3 = 243 new translations.

We cannot simply translate the two relationships separately and join them together, because you cannot join phrases together in a way that works for all languages.  Word order changes.  Prepositions/joining words change, etc.

So, it's not practical to do this in a framework that supports multiple/arbitrary languages.

**Comment by oogoofeo** [comment]
Hi fisharebest,

thanks for the explanantion! In that case it might be better to remove the relation of the ex-whatever's spouse. It's better to have no information instead of a wrong one.
