### ISSUE TITLE
Scollbars not appearing on colorbox gallery modal 

### ISSUE THREAD

**Issue by terah** [fisharebest/webtrees#583]
Hi,

Browser: Mac chrome latest and safari latest
OS: OSX Yosemite

Scrollbars are not appearing on the image gallery colorbox modal.

Visit http://sarahcullen.net/individual.php?pid=I00107&ged=GoodCopy.ged and click on the image with the caption 'Parish Map of Yarrunga'.

Terry

**Comment by JustCarmen** [comment]
Hi I see you are using the JustBlack theme. The colorbox code is theme related and since this theme is not a core theme you shouldn't have posted your message here.

Your message should be posted at https://github.com/JustCarmen/justblack/issues.

But I took a quick look and the scrollbar just works fine in both safari and chrome. But I've looked from a windows pc. So I think this is not a browser issue but it is the combination with Mac. And that's a problem because I can't test it since I don't have a mac.

**Comment by terah** [comment]
Ahh.. ok.. thanks for the response.  I'll move the issue to justblack.




Regards,

Terry Cullen
Freelance Senior PHP Programmer/Web Developer
--
Phone 1300-955-838 <+61-1300-955-838>Mobile 04-3836-8032 <+61-4-3836-8032>
Email terry@terrycullen.com.auWeb http://www.terrycullen.com.au/G-Talk
terry@terrycullen.com.au13 Jarrott St, ChelmerTerah Pty Ltd | ACN 135 365
552 <http://www.terrycullen.com.au/>[image: Terah Pty Ltd logo]
<http://www.terrycullen.com.au/>
