### ISSUE TITLE
Indi page starts with wrong tab

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#625]
On the individual page, if you select a tab, say Sources, and then select another individual, the tab is still on Sources.  Shouldn't the new individual page start with Facts and Events as the active tab?

**Comment by fisharebest** [comment]
A good question.  Like you, I would prefer each new individual page to start on the facts+events tab.

However, when this behaviour was introduced (many years ago), there was an overwhelming majority who wanted the "remember last tab".

I can't find it right now, but I'm sure there is an open github issue (called something like "tabs remembered by number which is volatile"?)because it remembers tab number, not name, and different pages have different tabs.

**Comment by makitso** [comment]
Drat :-(  I was sure that I saw behaviour on 1.6.2 -- oh well.
