### ISSUE TITLE
"New Page" not appearing after upgrade to 1.7.1

### ISSUE THREAD

**Issue by wtuser** [fisharebest/webtrees#670]
When a user logged in, he was directed to "My Page". It appears that after upgrading to 1.7.1, the user is presented with the "Welcome Page".

**Comment by fisharebest** [comment]
This change was not intentional.  It was a consequence of cleaning URLs...

Previously, the URL `index.php` could deliver different pages.  If you are logged in, you get "My page".  If you are not logged in, you get the farmily tree's "Home page".  If you have more that one family tree, then the URL could give different home pages.

Now, the URL `index.php` (with no parameters) will redirect to a specific page.

When you log in, you are returned to the previous page.  Before, we would be returned to `index.php`.  Now, we are returned to `index.php?ctype=gedcom&ged=XXX`.

To fix this, we need to add some logic:

If you are on a family tree's "home page", and you log in, you are redirected to your "my page".
