### ISSUE TITLE
Add TYPE subtag to _NMR tag.

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#688]
There are various states of being "unmarried" - some officially recognised and some inforation.  We need the TYPE qualifier to store this.

Should it be a fixed list (containing what values?) or free-format?

**Comment by StarJackie** [comment]
I guess a free-format would fit all possible types of "unmarried" around the world, wouldn't it?
I, for my self, need only one special TYPE which is "De Facto spouses" « Conjoints de fait ». 
Am I the only one who needs this?

**Comment by Amgine0** [comment]
Actually, there are various states of being married.

There has been a fair bit of research about marriage, and ultimately it is a legal status allowing the transference of legal property (and accruing certain rights, responsibilities, and privileges, mostly financial.) As such, there are four statuses: Legally married, legally conjoined (having some form of legally recognizable relationship whether or not there has been any formal recognition,) shared parentage with legal recognition of paternity, and shared parentage without legal recognition. The last two are only relevant where neither of the first two apply, but there are children - a pretty rare situation today. (A fifth status of 'not at all married or related' is implied, but probably also has little relevance.)

If you are looking to describe varying states of not-religiously-sanctioned marriage... use free form.

**Comment by NorwegianSardines** [comment]
I realize that it is late to weigh in on this but, I'm still trying to understand Jackie's need to have/use the _NMR tag for her "de facto spouses". When it is all said and done, does the Canadian government legally view these individuals as "married"?  If it does then you should not be using the _NMR.  This tag should only be used for couples that produce children who are not married in any legal form or are just cohabitation get without legal connection.

We still do not have a TYPE of "common law" as a marriage TYPE which is legally a form of marriage in many U.S. states and some other Western countries at various points in time.

So I guess we are all about defining what is marriage.  If it is ONLY a church sanctioned or civil function where you first must get a license and in front of an officiant of the government or church say some words, then any other type of arrangement is not marriage,, even common law, de facto or other legal binding can't be marriage, then must be _NMR and requiring a TYPE for "common law", "de facto" and "non-recognized".

I'm ok with this definition but then must be noted that way to reduce confusion.  The TYPE values on MARR tag must be set to either "civil" or "religious", rejecting "common law" as outline in GEDCOM.

If we don't reject GEDCOM and allow "common law" as a TYPE of marriage then any other government sanctioned or recognized marriage type historically must be added to the MARR.TYPE with _NMR reserved for all others and _NMR.TYPE left to be entered by the user at will.

**Comment by StarJackie** [comment]
Ken, the need of _NMR was to create the family and to have the label "Partners" displayed.
What I need is to create a family of two people (whatever their sex, it could be two men, or two women, or a man and a woman) with children and labeled Partners. I also need to be able to add the date and the place. I know a MARR (civil union) can be selected and is legitimate in Canada BUT people don't want to be labeled "Husband and Wife" when they are two men and/or two women.
If this create too much problems, then simply ignore my demand and I will create custom language on my website. As I said before, if this will benefit only me then forget about it. I thought I was not alone in my case. Thank you for your comments.

**Comment by StarJackie** [comment]
Just to say that I have 60 families with children in my tree who are "not married" couples. I suspect that will be more and more frequent in the future. There will sure be a need for it. Anyways, don't worry. I'll manage this for my own tree.

**Comment by NorwegianSardines** [comment]
This is cool, I am glad you are happy.  I am just worried that we are going down a slope that supports a definition of "marriage" that is not completely correct for all instances.   Since I don't understand the exact law in Quebec vs the rest of Canada or how different states in the U.S. define sanction marriage, vs unmarried.  I know that historically common law was a valid for of marriage in most of Europe until the Church had law enacted to make only the church a sanctioned place, but the law came into effect in various countries at different times.  Many of those same countries are now revisiting "marriage" and how they define it.

**Comment by NorwegianSardines** [comment]
As I've said much of this is based on perceptions that are personal and not legal.  Some people don't like to be labeled something they don't thing they are, yet every one else says they are.

Not for me to say.  If they are in the eyes of the legal bodies husband and wife, but don't like the term, then they have the right to be called whatever they like, but also know that many people don't see it that way, which is also their right.  I don't let myself get all bent over labels anymore, and one of the reasons I try to just tell the facts.  I would use a non description term like "supercalafagolistic" and let them figure it out.   :-)

**Comment by StarJackie** [comment]
"supercalafagolistic", hahaha!
Besides joking, those families "genealogically" exist and we need to record them. webtrees creates families with MARR et _NMR tags only.

**Comment by NorwegianSardines** [comment]
By this I mean, it is the label associated with the TYPE used not the tag MARR or _NMR.

So when adding an MARR, if we recognized that 'de facto' was a type of marriage rather than a type of not married, the label could be anything we want, including "partner" or "super......".

We get to wrapped around the tag we are using rather than the ability to use a TYPE subtag to redefine the parent tag.  MARR can be used to represent any type of union between two people in the FAMily record.  This is not any different than using WIFE or HUSB tags to represent either gender in a same sex union.  So when we combine two people to be a family we can say they are automatically married as a TYPE of (for example) "religious" then display that so the data entry person can change it to a type of "civil" or "de facto" or "partner" or "same sex" or any other number of options that we need to have to support the concepts each person has regarding the relationship.  For those relationships that are "not married" at all we can still have a TYPE of "not considered married" in the MARR.TYPE tag and create a second tag of _NMR if desired for those who round trip.  It is only these people, the round trippers, that care about the tag used, because their other systems either don't support TYPE or are too ridged in their definition and use of the MARR tag.  Internally to webtrees we can do what we want.

**Comment by Amgine0** [comment]
Well, as I pointed out, there are four generic forms of 'partnerships' which would be relevant to genealogy. These classes are not limited by gender or number of participants (as long as it is more than one.) There may be a fundamental assumption underlying this discussion of two people involved in any given family. Here is real, existing example:

* The mother (also the genetic, or 'egg', mother)
* The father
* The genetic father (sperm donor)
* The birth mother (surrogate)
* The child

Here in BC, Canada, this can be further complicated on the birth certificate, but all this *at least* can be there.

**Comment by NorwegianSardines** [comment]
So I think what I may be seeing is an addition of a _NMR.TYPE of maybe, "genetic parents" to indicate that the FAM record is just a place holder for some combination of individuals that lent genetic material to the children of the FAM record but are in no way a "family" from a marriage standpoint.

**Comment by fisharebest** [comment]
If I remember correctly, the original problem is that when a couple have a `1 MARR` event, they are labelled "Husband" and "Wife" - even if the event is `1 MARR/2 TYPE partners` ("Registered partnership").

Registered partners (officially called "civil partners" in the UK) are not technically husband and wife.

So, is the solution to change the labels for `1 MARR/2 TYPE partners` from "Husband" / "Wife" to "Partner"?

**Comment by Amgine0** [comment]
1 MARR/2 TYPE legal  "husband" / "wife"
1 MARR/2 TYPE conjoined "partner"
1 _NMR/2 TYPE lparent "father" / "mother"
1_NMR/2 TYPE parent "father" / "mother"

(in the exemplar, all four adults have ongoing legal rights in the family, and three adults are actively involved in the day-to-day raising of the child. How that would/should be represented in WebTrees is beyond me.)

**Comment by NorwegianSardines** [comment]
Greg, any TYPE on either MARR or _NMR that is not a form of marriage resulting in a man being called husband and a woman being called wife should be called partner.  I am not sure for all cultures or legal systems what values of TYPE should be applied to MARR and what are more considered a state of _NMR.  Since many coupling do not result in children and they are still recorded in GEDCOM and the least contentious is either Husband , Wife or Partner.

**Comment by fisharebest** [comment]
Review this before the 2.0.0 release

**Comment by NorwegianSardines** [comment]
I spent some time rereading this issue.  I do believe that the problem revolves around the label used rather than the tag _NMR.  Personally I would drop the use of _NMR in webtrees and provide a more robust way of controlling the label applied to the person in the family data display.  In my opinion the robustness should be added only via valid GEDCOM tags, either as a MARR.TYPE or an EVEN.TYPE tag.  Either primary tag would probably use the same TYPE list therefore the use of MARR vs EVEN would be moot in webtrees (I like the MARR.TYPE better) but for round trippers EVEN may be better. The robustness could be a function of someone using the TYPE term of "custom" and the software allowing a "language translation" to give it whatever display value they want their readers to see.  

Again, it can't be over stated that much of this "controversy" is because some groups in this world believe that they have a monopoly on the term "marriage" or the they dislike being called wife or husband because it harkens back to some way of life or a label they reject.  I see it in my life on a daily basis, some people dislike "partner" because to them it implies a gay relationship, but the next person says it does not. An unmarried friend of mine call her "man" my husband, and he calls her wife.  Others become confused because they then ask "when was your wedding?" and are told "we did not have one."

Thus, most software programs have invented various ways of noting all kinds of variation.  Most of these programs are not international in nature so they only care about the specifi user base.  For webtrees to remain international and general, we need to create some easy to implement custom translation for a MARR.TYPE list that gives the data entry person some control over the display value they present to their users.  Everyone has some bias in the terms they want to use or have applied to them, I know I have mine.  This is one area that we should try to cater to the whims of the reader.

**Comment by fisharebest** [comment]
> I do believe that the problem revolves around the label used

If there are no `MARR` events, we use "husband/wife".

To override this (and use "partner" instead), we must add a custom tag `_NMR`.

As you say, the `_NMR`tag is used to **prevent** the labels husband/wife being used.

Another option is to reverse this logic.  When no `MARR` events exist, we would use "partner".  To override this (and use "husband/wife"), you would need to add `1 MARR Y`.

Given that unmarried couples may eventually marry, the `_NMR` tag is always going to be problematic.

With this change in logic, we might be able to ignore any special meaning of this tag, and simply display it - as we do with other custom tags.

**Comment by NorwegianSardines** [comment]
With Greg's new logic, a 1 MARR Y would be required at a minimum. I would say this is good logic since an unmarried couple would have no MARR thus "not married" or "unknown".  If they were married between one date and another, i.e. "Divorced" a date of "FROM married date TO divorced date" would be entered.  Again good logic.  Then with this you would enter a 1 DIV with a date of the divorce.  Good logic too!  Unmarried with children has no bearing on the MARR tag.  No MARR tag = "partner" and MARR tag = gender based husband/wife. 

 If they were partners for some period, then married later I would advocated 1 MARR, 2 TYPE partner 2 DATE FROM/TO.  Later adding a 1 MARR Y or a 1 MARR, DATE FROM/TO

**Comment by fisharebest** [comment]
A couple with neither `_NMR` nor `MARR` is now assumed to be unmarried, rather than married.

It is no longer necessary to use the custom tag `_NMR`.
