### ISSUE TITLE
Updating a name that includes a Hebrew Married Name, deletes the Hebrew Married Name

### ISSUE THREAD

**Issue by melizaa** [fisharebest/webtrees#691]
In the Duck tree I have Daphne Duck I11
1 NAME Daphne /Duck/
2 GIVN Daphne
2 SURN Duck
2 _AKA Doris /Anka/
2 _AKA Dora /Ankka/
2 _HEB דפנה /דאק/
2 _MARNM Daphne /Gander/
2 _MARNM דפנה /גנדר/

When I update any part of the name, the Hebrew married name is deleted.

**Comment by melizaa** [comment]
Could we solve this issue?

**Comment by fisharebest** [comment]
The problem is caused by having two MARNM fields with different given names.  The "auto fill" logic assumes that only the surname will change on marriage.  You can see this with a much simpler example

1 NAME Daphne /Duck/
2 _MARNM Daphne /Gander/
2 _MARNM Doris /Goose/

You'll see that Doris gets changed to Daphne.  The problem is just more obvious when you have latin given names and hebrew surnames, as the "don't mix latin/hebrew" names prevents either from being used.

The entire MARNM editor may need rewriting.
