### ISSUE TITLE
can not update webtrees with 2 ged databases to 1.7.2

### ISSUE THREAD

**Issue by ferdiga** [fisharebest/webtrees#707]
Export all the family trees to GEDCOM files…
The family tree has been exported to /var/www/webtrees/data/mydb-2015-08-26.ged.#0 /app/Tree.php:596 Exception("Statement::execute() called twice.")

only one DB is exported

**Comment by fisharebest** [comment]
This was already reported and fixed:

https://github.com/fisharebest/webtrees/commit/195d09d8958a83dd9691b4af3225af8c9a5ece13

It is a simple one-line change.

**Comment by ferdiga** [comment]
thanks - please update the release

**Comment by makitso** [comment]
See this link for a fix

https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-2/30607-update-tips-and-tricks

**Comment by fisharebest** [comment]
> thanks - please update the release

The bug was introduced in 1.7.0
The bug was identified in 1.7.1 (because 1.7.1 cannot upgrade itself if you have more than one tree).
The fix was included in 1.7.2

So, if you have 1.7.1 and more that one tree, you will need to either
1) apply the one-line fix manually and auto-upgrade
2) upgrade manually.
