### ISSUE TITLE
Convert markdown-generated url's in the form of an @xref@ to webtrees url's

### ISSUE THREAD

**Issue by onstrees** [fisharebest/webtrees#712]
Apart from the regular markdown syntax, MarkDownExtra has 2 features, `[link text](url)` to include hyperlinks, and `![alt image text](imageurl "image title")` to include images. 

Webtrees could scan the result of the markdown conversion for url's in the form of `href=@xref@`, to convert them to regular webtrees url's for linking to a webtrees record of the appropriate type, and image url's in the form  of `src=@xref@`, to convert them to a regular webtrees image object's thumbnail.

Also invoking markdown processing for the `1 TEXT` level of a `0 @source-xref@ SOUR` record too, just like it is done for `0 @note-xref@ NOTE` and `n NOTE` texts, would be welcome.

This would make it easy to link from comment texts to other records in webtrees, e.g. to other individuals mentioned in a source text, and to ornament some notes with images, just enough to make them a viable alternative to the separate stories module.

Additionally you might consider a small modification that I have made to my own webtrees installation. Switching ON the markdown option of webtrees interfered with a lot of texts that already existed in my genealogy, and that where not intended to be processed by markdown. Therefor I added some simple logic that invokes markdown not for all texts, but only for those texts that end with the marker text `.markdown` (which is removed before the call).

**Comment by bmhm** [comment]
I don't think it is possible to enable markdown only on `.markdown`, but instead disabling it eplicitly on `.nomarkdown`. The reason is that your solution would break existing markdown texts from a lot of users.

About the markdownextra-extra-pass: I'd love to see that on one hand, but the links should be included in facts anyway, shouldn't they? Can you give us a use case?

**Comment by webtrees** [comment]
The way I implemented `.markdown` checking, is with an extra test on that text, if webtrees' markdown option is OFF. That way it doesn't break any existing case for users with the markdown option already ON.

The case for using webtrees url's in note and source texts, is not for relating one person to another, but for linking from a text directly to a person or other webtrees record named in that text. I have for instance source texts that name several generations where grandfather, father, son etc. share the same name. After untangling that, a link to the correct person is clarifying.

**Comment by fisharebest** [comment]
Converting @XREF@ to a link seems a good idea.

We already do a similar thing in other places, such as the batch-update module.

**Comment by fisharebest** [comment]
The current markdown library was chosen because it is compatible with PHP5.3.  See #479.  We need to check that any solution will work with the markup generated by phpleague/commonmark.

XREFs are supposed to be temporary identifiers - for use in data transmission.  They are not designed as permanent identifiers.

webtrees will change them when it merges records or trees.  Other applications will change them every time they import/export data.

UUIDs would be much better for this.

**Comment by bmhm** [comment]
@webtrees sorry for trying to contact you here, but there is no message functionality that I know of.

Is it ok for you to rename your account? it is being confused with this project and also prevents this project from getting the url https://github.com/webtrees/.

Looking forward to your reply.

**Comment by fisharebest** [comment]
@onstrees Many thanks!

**Comment by onstrees** [comment]
**fisharebest** commented (9 sep 2015)
> XREFs are supposed to be temporary identifiers - .... webtrees will change them when it merges records or trees. Other applications will change them every time they import/export data.

I wrote my own xref-renumbering program (java) before webtrees had a gedcom merge function. For fear of missing any custom xref usage (like webtrees own  _WT_OBJE_SORT) I search/replace all `@xxx@` where `xxx` matches the xref of a 0-level record. The gedcom rules for using and escaping the @ character prevent mistakes.
