### ISSUE TITLE
Media challenges

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#736]
I am probably doing something dumb but here is the issue. 

1)  I have created a "sub" folder in both the media folder and the thumbs folder.  Then, if I upload a media file for an individual and specify the sub folder, everything works as expected, e.g. thumbs sub folder contains thumbnail of the image file.  However, if I do the same thing under the Manage Media screen the thumbnail is not generated, but the normal image is in the media/folder.  

2)  While in the Manage Media, if I do an edit on an existing image and then select a folder from the drop down "Folder name on server", the image and thumbnail files are moved to the sub folder.  However, on the Manage Media page the error exists "This media file does not exist"

**Comment by fisharebest** [comment]
>  However, if I do the same thing under the Manage Media screen the thumbnail is not generated

The manage media page does not create a thumbnail.  Because of some horrid design decisions inherited from PGV, we cannot do this.  e.g. the thumbnail size is a per-tree setting.  So, until we have created a media object (in a tree) we cannot create a thumbnail.

My preference would be to replace the current (single) thumbnail with a range of derivative images at various sizes, ranging from the tiny ones used in autocomplete, the medium ones used in individual boxes, and the larger ones on individual page.

But, we have historically allowed people to create custom thumbnails (e.g. a cropped face from a larger photo), and making any changes would upset these people.

As for the second point (one issue per issue!), I'm not sure.  I don't use sub-folders myself, so I'd need to set up some test data to see if I can reproduce what you describe.

**Comment by makitso** [comment]
Yea, I figured I would catch it for doing two problem in a single issue :-)
The reason for all this is that I have quite a few image files, all stored in the media folder.  So, I thought I might organize them better with sub folders.  The move works in that I get an acknowledgment that the media and thumbnail have been moved.  But, only the thumbnail is visible. I looked at table wt_media and the file name still reflects being in the media folder not the sub folder.

**Comment by fisharebest** [comment]
Moving files is problematic.  We must update two things.  The file location on disk (immediate) and the corresponding media object (when the pending change is accepted).

Rejecting the change to the media object would leave missing/orphaned files...

So, this may be an issue of pending changes, as the wt_media table won't be updated until you accept the change.

**Comment by makitso** [comment]
OK, I think I got hung up on with the accepting the change.  I have tried moving several other images and it appears to work.

**Comment by fisharebest** [comment]
Perhaps any changes to the filename should always be auto-accepted - regardless of the setting?

**Comment by makitso** [comment]
> Perhaps any changes to the filename should always be auto-accepted - regardless of the setting?
I would vote for this -- IMHO, I think any change made in the admin section should be accepted automatically.

> The manage media page does not create a thumbnail. Because of some horrid design decisions inherited from PGV, we cannot do this. e.g. the thumbnail size is a per-tree setting. So, until we have created a media object (in a tree) we cannot create a thumbnail.

The problem is that the manage media page imples that thumbnails will be created "if" you don't supply one yourself.  Would it be possible to add a dropdown to select the tree?
