### ISSUE TITLE
Media Type missing from Lists/Media Object or Control Pannel/Media pages

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#742]
I have been working with media objects and organizing items by Media Type, Photo, Tombstone, etc.  When your under the media tab for an individual and there are media objects, the media Type is listed.  However, when your logged in and are looking at Lists/Media Object or on the Control Panel/Media page, the media Type is not shown.  One must select a media item for edit to see the Media Type.

**Comment by makitso** [comment]
I am going to submit code to add Media Type to the Lists/Media Object.  But, the fixing the Media page in Control Panel is beyond me.

**Comment by JustCarmen** [comment]
I've just fetched the latest code and I am not very happy with this adjustment. I think the media type is a superfluous addition to the media list page.

I have already divided all my media into subfolders.
All items in the subfolder 'photos' are of the media type 'photo'
All items in the subfolder 'family notices' are of the media type 'newspaper'
and so on

I do have 'mixed' subfolders with different media types in it, but it still doesn't make sense because the regular visitor doesn't care what the type of the media item is. They will just click on the thumbnail.

I do think this can be a helpful addition for the media list in control panel. In my opinion that's the only logical place to list the media types. Then an admin could easily detect and correct the media types.

**Comment by makitso** [comment]
Carmen,
You have your media very well organized.  However, not everyone has this degree of structure.  IMHO, having the media type displayed on List/Menu Objects page is a very minor change.  Aside from the fact that you don't like it, can you help me understand what problem that it causes?

> addition for the media list in control panel.
Actually, I wanted to do this but could not figure out the code :-(

**Comment by JustCarmen** [comment]
I do think it could be helpful for administrators to have an easy way to see the media list type of an media object. But in my opinion it is not interesting information for regular visitors. So the control panel should be the place to go and not the media list page in the front site.

It is true I have my media well organized. So on a regular medialist page I know see 20 times the same message, i.e. media type = newspaper. So in my case superfluous. But I can hide it with css if I have to.

So I am not saying it shouldn't be listed, but I think it should be moved to control panel. I've looked into the code and I think this should be part of the mediaFileInfo function to get it on the left side of the table. But it then needs the $media variable in this function in order to use it. I don't feel comfortable enough to change it myself because it is against the current code structure. I think Greg has to decide.

But if you decide to leave it on the medialist page then make sure the media type text is translatable. At the moment it is not.

The code should be:

>>$mediatype = $mediaobject->getMediaType();
if ($mediatype) {
    echo GedcomTag::getLabelValue('TYPE', GedcomTag::getFileFormTypeValue($mediatype));
}

This is a copy from the same code in the FunctionsPrintFacts file.

**Comment by makitso** [comment]
> But in my opinion it is not interesting information for regular visitors.

IMO, human behavior suggests that a typical visitor will just do a search with the default parameters.  This will return a list of everything -- that are not in a subfolders.  As they look through the objects returned they will be able to see the media type of each object -- which will give them a clue that they can filter on this attribute.  

>  It is true I have my media well organized. 

With all your objects in subfolders, IMO, the "include subfolders" box should be checked by default so that everything is visible?

> I do think it could be helpful for administrators to have an easy way to see the media list type of an media object. But in my opinion it is not interesting information for regular visitors.

Perhaps it can be changed to only be visible to users who are logged in?

> I don't feel comfortable enough to change it myself because it is against the current code structure. I think Greg has to decide.

I agree, the code was is very tricky.

> But if you decide to leave it on the medialist page then make sure the media type text is translatable.

Good point, I will fix this.

**Comment by alvin101** [comment]
My 2 cents,

I appreciate the clean interface for visitors, but those of us that spend most of our time doing admin could use some more help here.

When I click the media tab I would like to see information like true file name (name before, Title is inserted), the subfolder it is in, (you can see this on click edit, but this takes time). and the media object ID (M1452) this ID would be very helpful in adding a media object to another individual.

Anyway I was thinking... What about an admin theme that would show much more information about media objects etc.

**Comment by JustCarmen** [comment]
>>With all your objects in subfolders, IMO, the "include subfolders" box should be checked by default so that everything is visible?

That's true. Therefore in both my themes I have implemented an option to move the media menu to the top-menu and list all the media items in subfolders. Clicking on a menu-item will automatically bring you to the subfolder list which shows all media items in this subfolder immediately. 

>>this ID would be very helpful in adding a media object to another individual

You can see the ID in the bottom of your browser when hovering over a thumbnail.

>>Anyway I was thinking... What about an admin theme that would show much more information about media objects etc.

We don't need an extra theme for that. We can make differentiations between admins and other users already and besides that we have the media list in control panel.

>>Perhaps it can be changed to only be visible to users who are logged in?

Good point. I can live with that.

**Comment by fisharebest** [comment]
Re-opening so that I can look at this when I get back online.

**Comment by fisharebest** [comment]
The control panel `admin_media_manage.php` should show as much information as possible.

The genealogy page `medialist.php` does not really need the details.  I do not think that visitors will care if a file is in JPEG format or how many KB it takes on disk.  They are interested in pictures and people.

But the control panel has limitations.  Particularly, It must shows all media from all trees together.  (Media files can be linked to zero, one or more trees.)

So, I have added a "Show details" option to the media list.

The "type" and all the file information is only shown when the option is selected.

The default is a much simpler display, but the information is available if you require it.
