### ISSUE TITLE
Language menu does not page refresh for Android devices

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#745]
Issue is visible on both stable and beta demo sites. Picking something from the themes menu triggers a page refresh.  Picking a language from the language menu does not refresh the page.

Behavior is the same with either chrome or Firefox browser.

**Comment by makitso** [comment]
The problem is that the page refresh is missing after selecting the new language.  Makes no difference if the browser is has "Request desktop site" set to true or not.

**Comment by fisharebest** [comment]
There is code to reload the page (webtrees.js, line ~1270).

In firebug, you should see an XHR request to update the session/language, and then a page reload.

Do you see any javascript errors?

**Comment by makitso** [comment]
I am not sure that firebug is available on Android is it?

**Comment by makitso** [comment]
Well,  I installed firefox on my tablet and added firebug.   But for the life of me I can't see how to invoke it😮

**Comment by makitso** [comment]
Greg,  line 1274 is:
	}, function() { window.location.href = window.location.href; /*location.reload();*/ });

It works if I change it to what the themes code is:
	}, function() { location.reload(); });

**Comment by makitso** [comment]
From what I can see,  window.location.href does not work  on Android.

**Comment by fisharebest** [comment]
On pages generated by POST requests, `location.reload()` will resubmit the POST data.

There was a bug report that changing language during some edits/updates would cause updates to be made twice.  Hence it was changed...

However, since then, I have updated all (I think!) logic so that after a POST, we redirect to a GET, so that this won't happen.

So, I think we can now re-instate the original code `location.reload()`
