### ISSUE TITLE
WT_LOGIN_URL is being generated incorrectly.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#746]
On my production site skatekey.net, on the login page - Request new user account, the URL being generated is wrong.  It is:   https://www.skatekey.net/login.php?url=index.php?action=register

However, on my localhost development system the same request is generating a URL of http://localhost/login.php?action=register

This suggests that in session.php,  WT_LOGIN_URL is being set incorrectly?  This "may" be due to an inconsistency in the data contained in table wt_site_settings.  Let me explain.

In my product system, wt_site_settings has an entry under settings_name of LOGIN_URL which contains the value https://www.skatekey.net/login.php?url=index.php.  This should be correct (??) in that under Control panel Website preferences, the Website URL is https://www.skatekey.net/

However, on my localhost system, the database table wt_site_settings has "no" settings_name of LOGIN_URL even though the Control panel Website preferences for Website URL is set to "http://localhost/".

**Comment by fisharebest** [comment]
LOGIN_URL will be generated dynamically if left blank.  By default it should be left blank. You should only set this if you need to force a specific login URL (e.g. HTTPS or integrating with a custom login system).

**Comment by makitso** [comment]
Actually, the database entry LOGIN_URL on my prod system was wrong, and I corrected it and fixed that problem.  However, I am not sure how this database entry exists.  I can't seem to generate it on my dev system even after I upgrade the Website preferences.  Is this an old obsolete entry?

**Comment by jpb999** [comment]
I think this may be related:
I run webtrees on a server attached to my router.  Externally my webtrees site is accessed by  www.myfamilytreesite.com or myfamilytreesite.com.  From computers on my home network, it is accessed at 192.168.0.8/webtrees.  

When an external user requests a login they get the following email which correctly directs them to myfamilytreesite.com to complete the login confirmation.

Notification to user of registration:
Hello Jbtest jb…

You (or someone claiming to be you) has requested an account at http://myfamilytreesite.com/ Family Tree (Baccellieri, Cozzoli, Messina, Pino, DiJulio, Bruno - Jones, Foshee, Broom, Fee, Audesey, Giles) + more using the email address gf011@yahoo.com. Information about the request is shown under the link below.
Please click on the following link and fill in the requested data to confirm your request and email address.

http://myfamilytreesite.com/login.php?user_name=Jbtest%20&user_hashcode=5c042fedb1859afbdb0c5c6f80a878e8&action=userverify

Username - Jbtest 
Verification code - 5c042fedb1859afbdb0c5c6f80a878e8
Comments - Jbtest 7am 
If you didn’t request an account, you can just delete this message 
------------------------------------------------------------
After I approve the new user, webtrees sends the following email incorrectly directing them to 192.168.0.8/webtrees instead of www.myfamilytreesite.com (or myfamilytreesite.com).

Approval message sent to user:
The administrator at the webtrees site http://192.168.0.8/webtrees/ has approved your application for an account. You may now login by accessing the following link: http://192.168.0.8/webtrees/

Accessed externally, control panel, manage family trees, general, url has: http://myfamilytreesite.com/?ged
Accessed internally, it has: http://192.168.0.8/webtrees?ged

I don't see a way to correct this with the settings available.  Am I missing something?
Thanks.

**Comment by fisharebest** [comment]
> I don't see a way to correct this with the settings available. Am I missing something?

I presume that you can access http://myfamilytreesite.com from within your home network.

1) login at this URL.
2) from the control panel, set the server-url setting to be this URL.

Your problem is that your site is available at multiple domains, and your server does not give webtrees the information to determine which was used.

An alternative to the above is for you to update your webserver configuration to specify the desired host/server name.

**Comment by fisharebest** [comment]
> However, I am not sure how this database entry exists. I can't seem to generate it on my dev system even after I upgrade the Website preferences. Is this an old obsolete entry?

Control panel -> website -> login and registration -> login URL

**Comment by jpb999** [comment]
I set the website url as you suggested above and it solved the problem.  I don't know where the database entry came from as I've been running webtrees for several years.  I normally access the site from the local network side of the router via 192.168.0.8/webtrees as this is the assigned address of the server on the router.  Externally, the site is access from the myfamilytreesite.com url.  Thanks for helping with this.
