### ISSUE TITLE
Scroll blocks on the home (front) page.

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#773]
On the Home Page there is the option to place blocks.  Some of these block, with variable data scroll and some do not.  For example,  “Top n surnames” has a max-height of 200px and scroll whereas “Top n given names” does not have a max height and displays all entries.  

So,  my question is, should all block display all entries configured or, should all blocks scroll – which would require changing “Top n given names” to have a max-height?

**Comment by wkitty42** [comment]
i think the blocks should scroll if the data is larger than the given window area...

**Comment by fisharebest** [comment]
Scrollbars within scrollbars are not generally encouraged.  We have a long page (with a scrollbar) and inner regions with their own scrollbar.

Typically, they are used when it is necessary to show both the scrolling region *AND* some other content at the same time.  For example, a list products and a list of product-filter options.

The inner regions have a fixed max-height which was set for a typical desktop screen, and may not be appropriate on small screens.

Indeed, on small touchscreens, users are happy to have very long pages as scrolling is easy - a vertical swipe action.  Furthermore, some devices do not make scrollbars particularly visible, so the inner scrollbars may be difficult to notice.

For some blocks, the height is unpredictable, and can be very large.  For example "on this day".  There were (historically) given the option of scrollbars.  For others, we can easily control/predict the height - for example by setting the number of "top given names" to display.

So, I would think that scrolling regions should be used only where absolutely necessary.  Instead of adding them, perhaps we should ask where they can be removed?

**Comment by fisharebest** [comment]
An alternative to scrollbars is to truncate the initial display, and have a "show more" link which exposes the rest of the data.

**Comment by makitso** [comment]
Typically, the Top n value set to 10.  I would be in favor of displaying all entries -- no scroll bars.

**Comment by fisharebest** [comment]
The following blocks have the "add scrollbars" option

* Most viewed pages
* Top given names
* Top surnames
* On this day
* Recent changes
* Research tasks
* Upcoming events
* Yahrzeiten

I've removed the option from the first 3.
I'm inclined to remove the rest.  Thoughts?

**Comment by Manja-S** [comment]
If you'd remove them, you are taking away (sometimes much appreciated) options for end users. Why would you want to do that? Why not set the standard value to 'no scroll bars', and leave the final decision up to the end users? Personally I'd hate to miss scrollbars on the blocks you mentioned above.

**Comment by JustCarmen** [comment]
> An alternative to scrollbars is to truncate the initial display, and have a "show more" link which exposes the rest of the data.

Yes, please do. Better than the long lists of data.

**Comment by Fa10175** [comment]
Like Carmen I would rather have something like:

> An alternative to scrollbars is to truncate the initial display, and have a "show more" link which exposes the rest of the data.

Or let the administrator choose what he prefers.

On the long lists, people stop very quickly and do not go further.

**Comment by melizaa** [comment]
I have problems with the long block lists.
The scrollbars have worked well till now.

If we will truncate the initial display and have a "show more" link, then I think that we should also have a "show less" link (also?) at the top for the long display.
It is not easy to reach the bottom of the list for the bottom scroll bar.

**Comment by melizaa** [comment]
If the problem to use scrollbars exists on small screens, could we include scrollbars when the site runs on desktop screens and not have them on small screens?

For the long block lists we should at least enable at the top of the block to jump to the bottom of it or preferrably to enable users to show or hide the contents of blocks.

I have problems to scroll down and to see where the block ends. I assume that my users will have bigger problems.
