### ISSUE TITLE
Computation of living people

### ISSUE THREAD

**Issue by MartinWetterwald** [fisharebest/webtrees#788]
I have a tree where all persons are dead for a long time (all more than 200 years ago).
There is a problem every time webtrees tries to estimate who is dead and who is alive, when the death date is not known.

Look at the "Oldest living individuals" table. A lot of people are shown to be alive and some are 300 years old!

Click on the "Alive" button on the top.
- First problem: Inconsistency. Here, it seems that 7 persons are alive. But the previous page showed a lot more of alive person (there should be 0 alive persons).
- Second problem: take Agathe Amm for example. OK, we don't know her birthday. But having a look at her husband André who was born in 1775, it should be obvious that 1775 + 100 = 1875 ; 1875 < 2015 so both André and Agathe should be considered dead.

The graph Total living/Total dead should indicate 100% dead. Why does it consider that 28 are living? There is also an inconsistency because previously it considered that only 7 are living.

**Comment by fisharebest** [comment]
> First problem: Inconsistency

The individual list uses the full privacy calculations.  (e.g. checking dates of spouses, children, grandchildren, parents, grandparents).

The statistics simply check for a "Death" record.  It would take too much server resources to apply full privacy calculations to thousands (or millions) of individuals.

There is a batch process which will add "Death: yes" records to individuals who can be calculated to be dead.  (Control panel -> Modules -> Module administration -> Batch update -> Add death records)

So, I think this is working correctly.

> Second problem: take Agathe Amm for example. OK, we don't know her birthday. But having a look at her husband André who was born in 1775, it should be obvious that 1775 + 100 = 1875 ; 1875 < 2015 so both André and Agathe should be considered dead.

I can see both Andre and Agathe on your site.  This means that webtrees DOES assume they are dead.  Otherwise they would be private - and I would not be able to see them.

So, I think this is working correctly.


TIP: If you have two issues, create two separate issue reports.  Otherwise it is impossble to mark just one as "fixed", or to assign them to different developers.

TIP: There are hundreds of experienced webtrees users on the forum (www.webtrees.net) who could have answered these questions.  There are only 1 or 2 developers who read these bug reports.  Unless you are certain there is a bug, it is normally much more efficient to ask on the forum.

TIP:  The privacy calculations are very complicated.  If you think there is a problem, please try to create a new tree / GEDCOM file that demonstrates the problem.   (Perhaps use the clippings cart function).  If you cannot reproduce the problem, we will not be able to do it!

**Comment by fisharebest** [comment]
TIP: there is an option "show estimated dates of birth/death on individual lists".

This uses the same rules as the privacy calculations.  You may find it useful.

**Comment by MartinWetterwald** [comment]
Thank you very much for your answer.
« I can see both Andre and Agathe on your site. This means that webtrees DOES assume they are dead. Otherwise they would be private - and I would not be able to see them. »

Even if webtrees assumes they are dead, they are in the list when you apply the filter "Alive".

I just run the batch and everything is fine now!
Actually when I read the source code, I saw a mention in the comments talking about "batch update" but I couldn't find it. When I explored the menus, in didn't think that "Module administration" could be the place to launch batches. When I see the word "administration", I think of adding or deleting modules.

So it's actually not a bug. It's just the way webtrees work. It assumes that all dead people have a dead record, which often may not be the case.

I have 2 suggestions:
- Mentioning this batch update in the FAQ
- or even better: add a link to the batch module in the family tree import page.

Thank you for this awesome project!
