### ISSUE TITLE
Latest code fatal error

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#802]
Am now getting the following

    Fatal error: require(): Failed opening required 'D:\david\vhosts\webtrees\174\vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php' (include_path='D:\david\vhosts\webtrees\174\vendor/bombayworks/zendframework1/library;.;D:/wamp/bin/php/php5.6.16/PEAR') in D:\david\vhosts\webtrees\174\vendor\composer\autoload_real.php on line 59

I Pulled from Github yesterday for the first time in a week or so, so probably a recent commit

**Comment by fisharebest** [comment]
If you have composer installed, just run `composer install`.

We are not supposed to include the contents of the `vendor` folder, but we have for historic reasons.  It allows people to simply `git clone` or download a `.zip`.

But this creates problems.  Developers want all the test/dev files, such as `phpunit`.  Users don't.  So, we don't include these, and hence github contains an inconsistent set of data - `composer.lock` (including dev files), and `vendor/*` (excluding dev files) and the autoloader (shouldn't include dev files, but probably does.).

We have the additional complication that we can only run `composer update` from a PHP5.3 machine, otherwise we'd pull in libraries that won't run on PHP servers :-(

**Comment by ddrury** [comment]
Ooh, getting technical but that fixed it.

I also got a few warnings at the end

	symfony/event-dispatcher suggests installing symfony/dependency-injection ()
	symfony/event-dispatcher suggests installing symfony/http-kernel ()
	phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
	phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
	sebastian/global-state suggests installing ext-uopz (*)
	phpunit/phpunit-mock-objects suggests installing ext-soap (*)
	phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
	phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
	guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
	satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
	Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
	
I guess in the main they can be ignored, but should the last one be taken into account (ramsey/uuid) ?

**Comment by fisharebest** [comment]
> should the last one be taken into account (ramsey/uuid) ?

rhumsaa/uuid is the PHP5.3 compatible version.
ramsey/uuid is the PHP5.4+ compatible version.

To support PHP5.3, we must use the obsolete package :-(

**Comment by fisharebest** [comment]
Leave this open - it needs fixing (but from a PHP5.3 VM).

**Comment by ddrury** [comment]
OK thanks for the info

**Comment by makitso** [comment]
So, I don't have composer installed but get the error -- php 5.5.9.

**Comment by fisharebest** [comment]
@Rob - I can't fix this until I can get to a PHP5.3 machine.

Installing composer is easy - just download https://getcomposer.org/composer.phar

Run it by typing `php composer.phar install`
