### ISSUE TITLE
Webtrees Upgrade MITM

### ISSUE THREAD

**Issue by ghost** [fisharebest/webtrees#815]
Removed for impermanence

**Comment by arcsign** [comment]
The following two articles talk about issues with package signing/updates in composer and wordpress.

https://github.com/composer/composer/issues/1074

https://core.trac.wordpress.org/ticket/25052

There are really two likely types of attacks which are 

1. Attacker compromises update server and modifies files on the update server to infect clients
2. Attacker is able to MITM connection between user and update server, but hasn't compromised the update server.

Using SSL will basically make the second attack much harder because assuming SSL is being used securely (e.g. verifying SSL certificates, etc.). It would be difficult for an attacker in a MITM type position to push out a malicious update. However, if the update server is compromised then SSL is not going to do anything, but digital signatures would help with that because even if the file is modified the attacker still needs access to the signing key in order to push out a malicious update. Note it is necessary that version information is included with signed packages in order to ensure an attacker cannot perform some sort of downgrade attack.

There is also the issue of what to do if a installation does not support secure upgrades. One option is to give the user a choice for secure downloads and if using HTTPS to download updates is not supported they can then select the option to use insecure update and realize that they may be vulnerable. 

My only concern with this is that this same concept has been applied to java, microsoft office, and HTTPS in web browsers and email clients. The main problem with this sort of solution is often times people do not read warning messages and just click okay and continue because they just want things to work. In the case of Java this is a well known technique of embedding a malicious java applet in a page and telling the user that they need to run the applet for the page to render correctly (this is documented in Social engineering toolkit SET) similar social engineering issues also affect microsoft word documents. Also, with email clients and web browsers many times people will click through "could not verify SSL certificate warnings" because they just want the website they are trying to access to work so they can get things done (kind of defeating the entire purpose of SSL though!). I guess the only point I mean to make with this is that 

people don't always reading warning messages nor do they likely understand what they mean (e.g. most people do not understand how HTTPS works so they just click through HTTPS could not verify certificate dialogue). If you give the user a choice in security and they make a poor decision based on ignorance it can cause major issues

"Researchers said hackers had used backdoors to spread the KillDisk wiper module through booby-trapped macro functions embedded in Microsoft Office documents across the Ukrainian power authorities."

and this happened to a power plant didn't even use a crazy duqu style 0day just powershell macros in word documents to take down a power plant?!?!?!?!!!!!! 

"Therefore, it is believed that the initial point of infection with BlackEnergy caused after employees opened Microsoft Office files containing malicious macros."

I guess my point is just putting security in hands of users can have bad consequences at times! 

https://thehackernews.com/2016/01/Ukraine-power-system-hacked.html

**Comment by arcsign** [comment]
I had some extra time so I did a little research on fixing webtrees MITM issue.

Basically there are two possible solution in my mind

1. Secure connection using HTTPS - basically protects against classic MITM attack, but if update server is compromised then files can be backdoored

2. Use digital signatures (e.g. RSA + SHA512) - using digital signatures protects against modification on server and in case of MITM attack if attacker is not able to steal signing key for packages

As far as implementing this goes you can use OpenSSL for implementing digital signatures (basically hashing update + version information) then encrypting hash with private key clients decrypt hash with public key and hash the update and compare it to the encrypted hash sent by the server. If they match is means the update hasn't been tampered with.

This paper describes implementing digital signatures this would likely need to use openssl or you could use some sort of PHP crypto library which would likely be slower than openssl (native code)

http://www.cgu.edu/include/AMCIS2004.pdf

This also provides a good description also

http://searchsecurity.techtarget.com/definition/digital-signature

As far as using HTTPS in order to protect against MITM attacks without using digital signatures I would recommend using CURL for this

http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/

**Comment by fisharebest** [comment]
> Secure connection using HTTPS - basically protects against classic MITM attack, but if update server is compromised then files can be backdoored

The update server has been HTTPS since December (thanks to https://letsencrypt.org)

**Comment by fisharebest** [comment]
> Use digital signatures (e.g. RSA + SHA512) - using digital signatures protects against modification on server and in case of MITM attack if attacker is not able to steal signing key for packages

.ZIP files have had a digital signature (GPG) since v1.0.0 (2010).
See https://launchpad.net/webtrees/+download

This precedes the auto-upgrade by many years, and it was originally assumed to be an optional / manual step.

**Comment by arcsign** [comment]
Alright, it looks like the version on github has been changed to download files using HTTPS (in apps/Functions/Functions.php fetchLatestVersion function (but the current 1.7.3 release uses HTTP). I tried looking for the File::fetch function it does not seem like it is a PHP function (at least from googling) but I would be interested how that works internally (whether it actually verifies SSL certificates) I have tried searching through the code and using google, but have not found a reference to it.

However, it also raises the question what if the host doesn't support HTTPS will it fall back to HTTP. I would also be curious if SSLStrip type attacks could be performed against the update (e.g. telling the client that HTTPS is not supported and having them downgrade to HTTP. I suppose this is another thing to look out for also depending on how this function is implemented and what APIs it calls.

There is also always the question on what if the host doesn't support using SSL which is just another one of the issues with deploying software in a heterogeneous environment. One solution is to prompt the user and ask them if they want to update even if it is possibly vulnerable to a MITM attack, however, there is always the concern that the user might not understand the dialogue or might just click okay or something..

**Comment by fisharebest** [comment]
> File::fetch function it does not seem like it is a PHP function

This is a webtrees class.  It's a simple wrapper around the low level functions, and paves the way for using external libraries (e.g. FlySystem), once we drop support for old PHP versions.

It just uses fsockopen()  and doesn't check certifications.

**Comment by fisharebest** [comment]
> It just uses fsockopen() and doesn't check certifications.

PHP 5.6 and onwards **do** check SSL certificates when using `fsockopen()`.
PHP 5.5 becomes obsolete on 10th July (3 weeks).

As far as I can tell, using SSL and checking the certificate prevents this problem.
