### ISSUE TITLE
W3 HTML Validator shows errors

### ISSUE THREAD

**Issue by HonkXL** [fisharebest/webtrees#824]
I just analyzed my webtrees page with the W3 HTML validator. It showed me 6 errors for the starting page. I already heared that google ranking depends on valid HTML, so I think HTML errors should be fixed.

The validator is here - there you can verify it:
https://validator.w3.org/

This are some of the errors reported:

    Error: Bad value search for attribute role on element form.
    From line 1, column 7052; to line 1, column 7113
    ></li><li><form action="search.php" class="header-search" role="search"><input

    Error: Stray end tag a.
    From line 21, column 761; to line 21, column 764
    <br>49,9 %</a></div>

    Error: The valign attribute on the tr element is obsolete. Use CSS instead.
    From line 53, column 5255; to line 54, column 23
    in:auto;">↩						<tr valign="top">↩					

    Error: End tag main seen, but there were open elements.
    From line 56, column 2542; to line 56, column 2548
    div></div></main><foote

    Error: Unclosed element div.
    From line 1, column 14055; to line 1, column 14074
    le="main"><div id="home-page"><div i

**Comment by fisharebest** [comment]
> Error: Bad value search for attribute role on element form.

The ARIA spec (https://www.w3.org/TR/html-aria/#docconformance) says explicitly that `role="search"` may be used on a `<form>` element.

It's purpose is to notify assistive technology that this form is a search form.

Perhaps an error in the validator?

> Error: Stray end tag a.

Which site did you run this on?  I don't see it on my own site.  Perhaps these mis-matched open/close tags are caused by custom content on your own site?

**Comment by HonkXL** [comment]
You can find my site here: https://webtrees.weiland24.de
