### ISSUE TITLE
Composer issue with latest dev version

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#861]
Getting

> Fatal error: require(): Failed opening required '[path]\vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php' (include_path='[path]\vendor/bombayworks/zendframework1/library;.;[path]/bin/php/php7.0.3/PEAR') in [path]\vendor\composer\autoload_real.php on line 59

It seems all the dev stuff is required again, I'm aware I can do composer install (or whatever the syntax is) but that leaves loads of files that I need to commit to the master branch. What's the proper way of dealing with this?

**Comment by fisharebest** [comment]
> What's the proper way of dealing with this?

The proper way to deal with this is **not** to include any of the `vendor` folder in the source files.  They really shouldn't be there.

To create distributions, we need `composer install --no-dev` and it must be run in a PHP 5.3 environment.

This, of course, won't have things like `phpunit`.  You won't be able to install these using `composer install --dev`, because the dev dependencies aren't listed in `composer.lock`.

So, the only option for developers is to run `composer update`, which brings in PHP5.5/5.6/7.0 versions of everything and which will also update `composer.lock`.

Once you've done this, you need to be careful not to commit any changes to `composer.lock` or `vendor` - something I've missed a few times :-(

This summer, I will create a 1.7 branch based on the current code.  The master branch (i.e. 1.8) will bump the PHP requirement to 5.5.9 and will remove the vendor folder.

Of course, this means that any developer/tester/early-adopter will no longer be able to simply fetch the latest code from github.  They will also need to install the vendor code.  Not everyone has command line access, so I'll probably have to create a dev-build-release system that does all this for them...
