### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#865]
I installed webtrees on IIS with PHP 5.5 and the timezones seem all screwed up.

The Server Information screen in the webtrees environment correctly shows "Default timezone	America/Detroit".

But everytime I add a news article or a new user, the server adds 5 hours to the correct times, effectively showing only UTC times.

Changing the timezone in my user profile seems to have no effect.

**Comment by fisharebest** [comment]
The "Server information" page shows PHP info first, and MySQL info second.

There are several timezone settings.

As well as `Default timezone`, there is also `date.timezone` and (in the MySQL section) `system_time_zone`.

Do the others show the same time zone?  If not, what do they show?

**Comment by miqrogroove** [comment]
This is an interesting point, and yet they all seem correct.  So I'm thinking this has to be a PHP bug or a webtrees bug.

"Olson" Timezone Database Version	2013.9
Timezone Database	internal
Default timezone	America/Detroit
date.timezone	America/Detroit	America/Detroit

system_time_zone
Eastern Standard Time

time_zone
SYSTEM

**Comment by miqrogroove** [comment]
I also have America/Detroit set under Website Preferences and in my user profile.

**Comment by miqrogroove** [comment]
Also noticed, the Timestamp column in the Website logs page appears to show the correct local time.  This is the only place I see it working so far.

**Comment by fisharebest** [comment]
See also #812 which is related.

**Comment by fisharebest** [comment]
The problem is that the timestamps from the database are converted (by MySQL) to "local/server" time.

We don't know what conversion has been applied - which makes it difficult to convert it to the user's local time.

One solution is to set the MySQL connection to use UTC.

This would be great for all the timestamp columns.

But we also use the database time for the "last change" times in webtrees.  These are date/time fields, which do not include a time-zone.  We would therefore need to convert these to some common timezone (e.g. the one specified for the tree).

Users might get confused by seeing their edits with change times in the future, etc.  Additional help text is needed

**Comment by andrewgoz** [comment]
I noticed this the other day (news items showing in UTC), and fixed it the same way UserMessagesModule.php fixes it - by adding WT_TIMESTAMP_OFFSET to the retrieved news updated field: "FunctionsDate::formatTimestamp($news->updated + WT_TIMESTAMP_OFFSET)"

**Comment by fisharebest** [comment]
> by adding WT_TIMESTAMP_OFFSET

I think this assumes that the PHP timezone is the same as the database timezone.

A more general solution must work when they are different.

**Comment by miqrogroove** [comment]
This is not fixed at all.  Updated to webtrees 1.7.8.  The very first thing I checked was the User Administration screen.  It shows my last sign in as 7:45 pm, which is exactly four hours in the future.
