### ISSUE TITLE
US 1940 census columns

### ISSUE THREAD

**Issue by ddrury** [fisharebest/webtrees#870]
Related to closed PR #810 

Just noticed, I have a US 1940 census image which broadly matches that given in http://www.mymcpl.org/_uploaded_resources/MGC-1940censusblank.pdf as noted above (layout different - columns the same) but neither of these match the column list in CensusOfUnitedStates1940.php.

I'll submit a PR if necessary but I'd like someone with more knowledge that me to :-
a) confirm I'm right and
b) determine which columns (if any) could be ignored

**Comment by fisharebest** [comment]
> neither of these match the column list in CensusOfUnitedStates1940.php

Could easily be my mistake.  I'm away from home for a few days, so will investigate when I get back.

**Comment by fisharebest** [comment]
The current columns were taken from a supposedly "official" exemplar census page.
The URL above seems to be from a Genealogy Society - and is presumably a secondary copy?

Since nobody (i.e. US person with an actual census scan that differs from what we have) has commented, I suggest we leave this until they do...

**Comment by Ziris85** [comment]
Hello all,

I can confirm that the 1940 census template with the builder is inaccurate, as I'd been finding myself using it to get started, but then going back and editing the shared note by hand to make it reflect the census properly. It looks like the above-linked template is mostly accurate when compared to an official U.S. gov't template:

https://www.archives.gov/files/research/census/1940/1940.pdf

For example, in the assistant template there are Mother/Father birthplace columns that aren't in the census; conversely, there aren't any residence columns in the assistant template (such as city/county) where they exist in the census.

I tweaked the script to reflect the census properly:
```
public function columns() {
        return array(
                new CensusColumnNull($this, 'Home', 'Home owned or rented'),
                new CensusColumnNull($this, 'V/R', 'Value of house, if owned, or monthly rental if rented'),
                new CensusColumnNull($this, 'Farm', 'Does this family live on a farm'),
                new CensusColumnFullName($this, 'Name', 'Name'),
                new CensusColumnRelationToHead($this, 'Relation', 'Relationship of each person to the head of the family'),
                new CensusColumnSexMF($this, 'Sex', 'Sex'),
                new CensusColumnNull($this, 'Race', 'Color or race'),
                new CensusColumnAge($this, 'Age', 'Age at last birthday'),
                new CensusColumnConditionUs($this, 'Cond', 'Whether single, married, widowed, or divorced'),
                new CensusColumnNull($this, 'School', 'Attended school since March 1, 1940'),
                new CensusColumnNull($this, 'Grade', 'Highest grade of schoole completed'),
                new CensusColumnBirthPlaceSimple($this, 'BP', 'Place of birth'),
                new CensusColumnNull($this, 'Nat', 'Citizenship of the foreign born'),
                new CensusColumnNull($this, 'City', 'Place having 2,600 or more people, or R if less'),
                new CensusColumnNull($this, 'County', 'County'),
                new CensusColumnNull($this, 'State', 'State/Territory/Foreign Country'),
                new CensusColumnNull($this, 'Farm', 'On a Farm'),
                new CensusColumnNull($this, 'Work', 'Was this person AT WORK for pay or profit during the week of March 24-30'),
                new CensusColumnNull($this, 'Emerg', 'If not, was this person assigned to public EMERGENCY WORK during the week of March 24-30'),
                new CensusColumnNull($this, 'Seeking', 'Was this person SEEKING WORK'),
                new CensusColumnNull($this, 'Job', 'If not, did they HAVE A JOB'),
                new CensusColumnNull($this, 'Nojob', 'Indicate whether engaged in home housework, in school, unable to work, or other'),
                new CensusColumnNull($this, 'Hours', 'Number of hours worked during week of March 24-30, 1940'),
                new CensusColumnNull($this, 'Unemp', 'Duration of unemployment up to March 30, 1940 - in weeks'),
                new CensusColumnOccupation($this, 'Occupation', 'Trade, profession, or particular kind of work done'),
                new CensusColumnNull($this, 'Industry', 'Industry, business of establishment in which at work'),
                new CensusColumnNull($this, 'Emp', 'Class of worker'),
                new CensusColumnNull($this, 'Weeks', 'Number of weeks worked in 1939'),
                new CensusColumnNull($this, 'Income', 'Amount of money, wages, or salary received'),
                new CensusColumnNull($this, 'Other', 'Did this person receive income of $50 or more from sources other than money wages or salary'),
        );
}
```
Naming the columns appropriately proved difficult since in some places there's somewhat-overlapping info, but I did the best I could and it seems to be working for me. It's also kinda long, but that seems unavoidable with the amount of info in that census.

Hope this info is of some use to you!
