### ISSUE TITLE
McDonald vs MacDonald / not showing all names.

### ISSUE THREAD

**Issue by allendex** [fisharebest/webtrees#889]
I have reported this in the forum.  I have many McDonalds and it wants to lump the Mc with MAC and becasue I have so many McDonalds in my database nothing in webtrees will display a full listing of anyone with the McDonald name.

I see great value in this as I also have LewALLEN LewELLYN LewELLEN's in my tree and it would be nice to lump them under the most common spelling.

Would like the McDonald to work but as we believe MC and MAC are two different clans we would like to be able to turn this off on their spelling.

I also have Prunty's that are spelled as Prenty and Printy would like to lump them under Prunty.

This is a good feature but would like to see it a bit more customized... or at least FIXED for now that if we click MacDonald it will show all McDonalds for the time being.

I'm catching a lot of hell from my family that looks at this site and they want to see a listing of their family.  As it is now I can't display a list of any McDonalds as it just shows the letters A B C D ... X Y Z and nothing listed in between.  I was told by greg i't becuse I have too many McDonalds (How can you have too many when your site is mostly from that family)

Thanks Guys you have a great system.

Allen

**Comment by fisharebest** [comment]
Bugs cannot be fixed unless they can be reproduced.  You will need to give me some help to reproduce your problem on a server that I can control (so that I can add debug code, look in the database, test fixes, etc.).

On the demo site (which gets reset at 03:00 UTC every day), I created 4 Macdonalds with various spellings.  This is how they are shown on the surname list.  They are grouped together, but counted separately.  If you only had one variant, you'd just see that.

![screen shot 2016-04-08 at 07 17 03](https://cloud.githubusercontent.com/assets/2306088/14375520/dfdc7292-fd59-11e5-8aba-d7e5e687ad91.png)

Then, clicking on any of the 4 surname variants will take me to the same page - where I see all variants

![screen shot 2016-04-08 at 07 17 26](https://cloud.githubusercontent.com/assets/2306088/14375521/e23dc1e4-fd59-11e5-8171-dcd41f6a6314.png)

> it just shows the letters A B C D ... X Y Z and nothing listed in between

Please - only one bug on each issue tracker.  Also, I don't understand what you are saying here.

**Comment by fisharebest** [comment]
>  You will need to give me some help to reproduce your problem

Did you, by any chance, update the database or the code?

**Comment by allendex** [comment]
When I get home tomorrow I will create a c-panel password for you. And ftp and etc

Send me an email to send it to

**Comment by fisharebest** [comment]
> Send me an email to send it to

Sorry - missed this.  My email is available here on github,the webtrees forum, etc.

fisharebest@gmail.com

**Comment by fisharebest** [comment]
There have been some changes in the latest code, which now display the "actual" name, not the internal "sorting" name.

If you still have problems with webtrees 1.7.5, then create another issue with details.

**Comment by allendex** [comment]
Actually this is not resolved.  I have 1.7.7 now.  I've been in the hospital and missed your response.

I have over 400 McDonalds and when I log in and display the surname it will not show any of them by the surname search or index.  I'm still getting the same behavior.

My URL is http://mcdfamily.org

I don't mind giving you cpanel access but not here on this forum.

Allen
