### ISSUE TITLE
Feature request: option to prevent relationship through sibling in relationship chart

### ISSUE THREAD

**Issue by gvd** [fisharebest/webtrees#913]
I often want to search what the relationship is between two individuals through just their ancestors. Currently I often get back a relationship chart that connects the individuals through the spouse of a sibling.

**Comment by ric2016** [comment]
I have implemented a modified relationship chart for my tree a while ago, which provides this functionality.
[See here for an example](http://cissee.de/webtrees/relationship2.php?ged=mueller&pid1=I1089&show_full=1&show_full-GUI-ONLY=1&pid2=I1090&find=4). This is not the most recent version, but you get the idea.

Option 4 uses the original algorithm. Option 3 is based on a modification of the Dijkstra algorithm (using weights to model a preference for blood relations), and the first two options use common ancestors only. I plan to provide this as a custom module (once the 'Charts as Modules' functionality is released), but at least the modified Dijkstra could also be integrated directly.

**Comment by gvd** [comment]
That looks great! Would you possibly share the code for that?

**Comment by ric2016** [comment]
Sure, but it's probably easier to do this after the next webtrees release (it will be possible, then, to add additional charts, like this one, to the list of charts via the control panel - in the current version, you'd have to adjust the code).

**Comment by fisharebest** [comment]
> Option 3 is based on a modification of the Dijkstra algorithm (using weights to model a preference for blood relations)

I'm curious to know what you did here.  I did try to use weightings, but didn't get satisfactory results.

**Comment by ric2016** [comment]
The algorithm is based on weights plus a cost function (i.e. the weights are not just added up):

The general idea is to view a path from one individual (or family) to another as a series of either ascending (FAMC, HUSB, WIFE) or descending (FAMS, CHIL) steps, and to find a path with minimal turns, where a turn is defined as a descending step, followed by an ascending step (these turns are undesirable because the individuals (families) at the ends of such a turn are not related by blood).

Example: The relation
`father's mother's daughter's husband`
is
`FAMC-HUSB-FAMC-WIFE-FAMS-CHIL-FAMS-HUSB`
i.e.
`a(scending)-a-a-a-d(escending)-d-d-a`
and therefore a path with one turn (right at the end).

The algorithm uses a cost function based on the weights of the last two edges in the path to the current node: Descending edges are weighted d, ascending edges are weighted a. If the last two edges have weights d and a (i.e. a turn), the cost for the step is some large number, e.g. 10000, otherwise the cost is 1.

**Comment by ric2016** [comment]
Now for a more straightforward solution ... The general idea is still the same.

The algorithm uses additional edges to model the switches between ascending/descending steps. For each individual and family X, we add two nodes A_X and D_X to the graph, connected by an edge from A_X to D_X with weight 0 (represents a non-critical switch from ascent to descent), and an edge from D_X to A_X with weight 10000 (represents an undesirable turn from descent to ascent).
We then add edges (all with weight 1) for 'descending' relationships (FAMS, CHIL) using the respective D_ nodes, and edges for 'ascending' relationships (FAMC, HUSB, WIFE) using the respective A_ nodes.

Examplary graph for a family F1 with husband I1, wife I2, child I3:
(FAMS) D_I1 to D_F1 (weight 1)
(FAMS) D_I2 to D_F1 (weight 1)
(CHIL) D_F1 to D_I3 (weight 1)
(HUSB) A_F1 to A_I1 (weight 1)
(WIFE) A_F1 to A_I2 (weight 1)
(FAMC) A_I3  to A_F1 (weight 1)
plus
A_I1 to D_I1 (weight 0) etc
D_I1 to A_I1 (weight 10000) etc

The shortest distance from X to Y is then determined via Dijkstra's Algorithm, using A_X as source and D_Y as target. We have to cleanup the resulting path by stripping the node prefixes, and removing any remaining duplicate consecutive nodes.

In the example:
I1 to I2: distance 10002 (they are not related) via
A_I1 - D_I1 - D_F1 - A_F1 - A_I2 - D_I2
or (cleaned up)
I1 - F1 - I2

**Comment by ric2016** [comment]
You can find the current version of the module (for 1.7.5-dev) [here](http://www.cissee.de/extended_relationships.latest.zip).
Feel free to reuse any code for the main relationship chart.

**Comment by gvd** [comment]
@ric2016 I've installed the 1.7.7.2 version and it works great!

**Comment by fisharebest** [comment]
The latest code includes an option to find relationships through ancestors only.
