### ISSUE TITLE
How to change SERVER_URL?

### ISSUE THREAD

**Issue by bblanchon** [fisharebest/webtrees#946]
Hi,

I want to redirect all my users to HTTPS instead of HTTP.

As I understood from [the documentation](https://wiki.webtrees.net/fr/Sécurité), I need to set the `SERVER_URL` to my HTTPS URL.
Unfortunately, the `<select>` element on `admin_site_config.php` only allows to select blank or the current HTTP URL.

When I select blank, I can manually type HTTPS in my browser, and it works fine until I click a few links and it goes back to HTTP.
Of course, I could add a rewrite in my apache settings, but this would require some extra (insecure) requests to the server every time the user clicks on an HTTP link.

How can I solve this issue?

Thanks

**Comment by fisharebest** [comment]
> Unfortunately, the `<select>` element on `admin_site_config.php` only allows to select blank or the current HTTP URL.

This is intentional.  If you typed in an invalid URL, you would be locked out of your site.

You should first leave it blank.  (i.e. no forced redirect).

You can then visit your site using HTTPS, and set the URL to the desired URL.

> Of course, I could add a rewrite in my apache settings, but this would require some extra (insecure) requests to the server every time the user clicks on an HTTP link.

If you visit the site using HTTPS, then webtrees will generate HTTPS links.  If it doesn't, it means that your apache configuration may be wrong.  webtrees uses the apache headers to know whether the request is HTTP or HTTPS.

If you are using a reverse proxy (e.g. apache receives HTTPS requests, and then makes HTTP requests to webtrees), then you need to add headers to tell webtrees that the original request was HTTPS.

**Comment by bblanchon** [comment]
Thanks to your help, I managed to fix it this way:

1. Select the blank URL and save
2. Open the Chrome dev tools (F12) and check "Disable cache" (important since the redirect is a 301)
3. Go the main page with HTTPS (opening the admin page wasn't enough, apparently)
4. Go to the admin page and select the HTTPS URL in the combo.

Thank you @fisharebest.
