### ISSUE TITLE
Possessive case problem in translation

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#947]
Unfortunately I found grammar incompleteness in the Hungarian translation of "wife’s husband" and "husband’s wife". The shown individual is either husband of that woman (or wife of that man) who married more than once. See on individual's page on Families tab or on the Sidebar the second married person's title.

If it is possible instead of
"feleség férj" ("wife’s husband" in English)
"férj feleség" ("husband’s wife" in English)

this would be the correct translation:
"feleség férj**e**"
"férj feleség**e**"

Only letter "e" is missing at the end of the second words. Please complete phrases with letter "e" if you can.

If that is not possible it would be better to get at least a right arrow between the words "feleség férj" and "férj feleség" like "épouse → mari" got in French. It is not too nice solution, but better than without the arrow.
Are there more such named relationships not included in Weblate translation? If yes, unfortunately they have to be reviewed because the inflectional suffix varies in Hungarian--it depends on the word's vowels...

Do you plan to transfer these phrases to Weblate? Probably other translators (and users) would be glad as well.

**Comment by fisharebest** [comment]
The same problem exists in German.  See #928.

The current system requires a translation into every language for every relationship that exists in any language.  If one language has a special rule, then every language must also translate it.

We now have over 1000 translations for relationship names.  This is not sustainable.

The problem of inflection and possessive suffix cannot be solved using translation.

I have started to write a replacement system that allows each language to have translations **and** logic.  It will not be necessary for any "special relationships" to be translated into other languages.

The fix for this will need to wait until the 1.8.0 release.

**Comment by fisharebest** [comment]
Support for this is now planned for version 2.1 - #2331
