### ISSUE TITLE
Gedcom error not listed

### ISSUE THREAD

**Issue by JustCarmen** [fisharebest/webtrees#980]
By accident I discovered an error in my Gedcom file. In a family record I had recorded as part of a 2 SOUR entry: '3 OBJE M56' in stead of '3 OBJE @M56@'. I check my gedcom file for errors on a regular bases but this one was never listed. According to the output of 'check for errors' my Gedcom doesn't contain any errors. Is this intended or is this a bug?

**Comment by fisharebest** [comment]
The checker only looks at the links (table wt_link).  
There is no link in this record - therefore it is not examined.

This is because many servers would not have enough resources to load the entire GEDCOM file into memory for analysis.

It would be easy to write a more comprehensive checker.
But is is hard to do this on a server with limited resources - and webtrees aims to run on budget/economy web hosts.

**Comment by JustCarmen** [comment]
Ok, I understand. But it is good to know the limitations of the error checking option. With this knowledge I did a search (with batch update) to find out if there were any other occurrences of 'OBJE M' but I didn't find any, so this was a one-off mistake. Batch update is a good alternative to find more specific errors which can't be found using the error checking option, but you need to know what you're looking for.
