### ISSUE TITLE
An old I18N: comment to change

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#998]
Please replace word "surnames" with phrase "given names" in [#3696](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=10ae9fc7d453b0dd525d0edf2ede7961) in Weblate:

![list_in_weblate](https://cloud.githubusercontent.com/assets/15856891/16153649/7e9b316e-34a7-11e6-8903-cae6d12c5f7e.png)

**Comment by tunandras** [comment]
I see you fixed the issue in [this commit](https://github.com/fisharebest/webtrees/commit/9665bf31440f9f472384f2a08f743e2bc9bb314c#diff-ecbcfa114d33793848619b8e7facf8ee) but sorry, it remained... I'm sorry! I make for you so many tasks and you worked all night... It's my fault. Seems it was not in that file which I found.

The new Weblate location is [#3681](https://translate.webtrees.net/translate/webtrees/webtrees/en-US/?checksum=10ae9fc7d453b0dd525d0edf2ede7961).

It is probably an unused translation because I couldn't find "Layout option for lists of surnames" string in any files. Could it be? Is it possible? What did I wrong?

**Comment by fisharebest** [comment]
> but sorry, it remained

The fix is in github.

It will appear in translate.webtrees.net - eventually.  Perhaps several weeks.

Each time I regenerate the .PO files, it adds 10MB to the size of the repository.  This is because all the line numbers in the files change, and the repository stores every version of every file.

The repository is already 500MB, and it is unfair on users with slow internet connections to increase the size unnecessarily.

So, I only regenerate the .PO files when it is essential.  Hopefully once for each release of webtrees.

When I have finished all the language changes for 1.7.7, then I will update the .PO files.
